### ISSUE TITLE
Regression in cabal-install-3.12.1.0: cabal check disregards inherited bound on `base`

### ISSUE THREAD

**Issue by andreasabel** [haskell/cabal#10162]
Version 3.12.1.0: `cabal check` fails hard if testsuite has no bound on `base` even if the library component has one.  This is a regression over 3.10.  I think it violates the semantics of bounds for testsuites: they should be inherited from the library.
```
$ cabal check
The following errors will cause portability problems on other environments:
Error: [missing-bounds-important] The dependency 'build-depends: base' does
not specify an upper bound on the version number. Each major release of the
'base' package changes the API in various ways and most packages will need
some changes to compile with it. The recommended practice is to specify an
upper bound on the version of the 'base' package. This ensures your package
will continue to build when a new major version of the 'base' package is
released. If you are not sure what upper bound to use then use the next major
version. For example if you have tested your package with 'base' version 4.5
and 4.6 then use 'build-depends: base >= 4.5 && < 4.7'.
Error: Hackage would reject this package.
```
In the wild: https://github.com/andreasabel/map-syntax/actions/runs/9734510558/job/26862619974?pr=1
Cabal file: https://github.com/andreasabel/map-syntax/blob/1ca83570980dd3a3b7c114c1ce55af307b4babe5/map-syntax.cabal

**Comment by ffaf1** [comment]
This is because `build-depends` for `Testsuite` does not import `map-syntax` (i.e. the library). Instead adding `src` to `hs-source-dirs/`, alongside with `test/`.

https://github.com/andreasabel/map-syntax/blob/1ca83570980dd3a3b7c114c1ce55af307b4babe5/map-syntax.cabal#L63-L70

As far as `cabal` is concerned, those are two separate entities.

---

> I think it violates the semantics of bounds for testsuites: they should be inherited from the library.

There is no indication the testsuite is testing a specific library.
Adding a default inheritance in the age of multi-libraries for `cabal` leads to the question: “What library?”.

I am inclined to say asking the user to add a `build-depends: my-library` or missing that a bound is correct. Does this make sense?

----

How to solve this for `map-syntax`?

- principled solution: add a `map-syntax-internal` library, expose everything in there; import it in `Testsuite`, import and re-export what appropriate in main library.
- two-lines solution: in `Testsuite` import `map-syntax`, axe `Data.Map.Syntax` from `other-modules`.

**Comment by andreasabel** [comment]
Oh, my apologies, my bad.  I did not notice that the testsuite does not depend on `map-syntax` the library.
Of course, the new check is absolutely right about the complaint!
