### ISSUE TITLE
`cabal-validate`: Output is too verbose and not verbose enough

### ISSUE THREAD

**Issue by 9999years** [haskell/cabal#10569]
`./validate.sh` starts by printing 93 lines of output (runtime configuration, tool and compiler versions, the names and versions of all transitive dependencies and local packages) before anything gets built. This is regardless of whether or not `--verbose` is passed.

Then, unless you pass `--verbose`, it hides the `cabal build` output! A clean build can take several minutes, so it's annoying to have no indication of how close it is to being done or what it's doing.

Then, regardless of if `--verbose` is passed, test suites won't output any indication that they've run a test! This is because the default Tasty arguments include `--hide-successes`, there's no `--no-hide-successes` option, and `./validate.sh --tasty-arg ...` can only _add_ arguments, not replace the default ones.

**Proposal:**
- `print-config`, `print-tool-versions`, and the full build plan output (currently inseparable from the `build` step) should be hidden by default, unless `--verbose` is given.
  - If we want, we could write this information to a file somewhere to preserve it.
- `cabal build` output should be shown by default. Maybe a `--quiet` option could be added to hide it?
- `--verbose` should toggle `--hide-successes` for test suites.

**Comment by geekosaur** [comment]
Small suggestion: if `stdout` isn't a tty, maybe output [GitHub Actions grouping](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions#grouping-log-lines) that can be collapsed or expanded by the viewer instead of the ANSI escapes. Then we can make everything verbose in CI without overwhelming people trying to go through the log.

**Comment by 9999years** [comment]
That's a great idea, but let's push it to another PR. I'm not sure what it'll require.

**Comment by geekosaur** [comment]
#10595
