### ISSUE TITLE
Errors from setup-exe-cache during parallel build

### ISSUE THREAD

**Issue by rrnewton** [haskell/cabal#1076]
Since I started using cabal-0.16 and GHC-7.6.1 (Mac OS 10.8) I've started getting a lot of errors like this:

```
/Users/rrnewton/.cabal/setup-exe-cache/setup-Cabal-1.14.0-ghc-7.6.1:
/Users/rrnewton/.cabal/setup-exe-cache/setup-Cabal-1.14.0-ghc-7.6.1: cannot execute binary file
/Users/rrnewton/.cabal/setup-exe-cache/setup-Cabal-1.14.0-ghc-7.4.2:
/Users/rrnewton/.cabal/setup-exe-cache/setup-Cabal-1.14.0-ghc-7.4.2: cannot execute binary file
```

I tried blowing away the cache but that doesn't solve it, but if I remove the "-j" to turn off parallel builds, I don't run into the problem and my build succeeds.

**Comment by simonmichael** [comment]
Adding to this issue, since it does sound possibly similar to the below and I can find nothing else like it on the interwebs:

In my github mac CI workflow, I see a recurring failure like "hledger-lib> /Users/runner/.stack/setup-exe-cache/x86_64-osx/Cabal-simple_mPHDZzAJ_2.4.0.1_ghc-8.6.5: /Users/runner/.stack/setup-exe-cache/x86_64-osx/Cabal-simple_mPHDZzAJ_2.4.0.1_ghc-8.6.5: cannot execute binary file". 

If I invalidate the cache, causing everything to be redownloaded/rebuilt, it goes away. Then it comes back (possibly the first time the build reuses cached files). Similar workflows on linux and windows don't have this problem, and similar builds on a local mac don't have this problem.

**Comment by matsumonkie** [comment]
I'm facing the exact same [issue](https://github.com/patchgirl/patchgirl/pull/17/checks?check_run_id=1192908036). 
So far, I don't have any hints on what and where to look for... :-S
