### ISSUE TITLE
Provide a CABAL_VERSION CPP macro to Setup.hs 

### ISSUE THREAD

**Issue by cartazio** [haskell/cabal#1320]
some sort of MIN_VERSION_Cabal(a,b,c) cpp macro should be baked into Cabal, because the normal way of making those cpp macros isn't run till after setup.hs is run!

**Comment by 23Skidoo** [comment]
This was fixed by the setup dependencies work.

**Comment by erikd** [comment]
I actually don't think this issue is properly resolved.

I have a custom `Setup.hs` file in which I trying to use the `Version` type from `Distribution.Version`. Unfortunately that type changed between Cabal 1.24 and Cabal 2.0 and I would like to use CPP to work around the differences. Unfortunately I cannot find a CPP macro that will tell be the Cabal version in this `Setup.hs` file.

Happy to close this and open a new ticket if you'de prefer.

**Comment by erikd** [comment]
Nevermind. Added:
```
custom-setup
  setup-depends: Cabal >= 1.24 && < 2.0
```
and I seem to be over that hurdle.

**Comment by 23Skidoo** [comment]
@erikd If you have a `custom-setup` stanza, you should be able to use the `MIN_VERSION_Cabal` macro in your setup script.

**Comment by erikd** [comment]
Ah ok. Thanks.

However if I have a `custom-setup` stanza I can just set `Cabal == 2.0.*` and not need any CPP nastiness :).

**Comment by phadej** [comment]
Erik: the MIN_VERSION_ macros are provided by cabal only if you have custom-setup stanza, and only for packages in setup-depends. If you saw different behavior, please provide a repro case.

Note that GHC-8+ also provides MIN_VERSION_ pragmas, and pre cabal-install-1.24 don't know about custom-setup. In that case you could default to older Cabal versions

**Comment by erikd** [comment]
It was my fault. My `custom-setup` stanza was incorrect.
