### ISSUE TITLE
Insufficient bug reporting instructions

### ISSUE THREAD

**Issue by Blaisorblade** [haskell/cabal#1420]
Upon discussing/reporting a bug (https://github.com/haskell/cabal/issues/618#issuecomment-22671983), I was rather confused by this comment:

> What I'd like to see is step-by-step instructions for reproducing this bug with HEAD.

Am I only supposed to report bugs after testing with HEAD? Does the stable branch get no maintenance?

If that's the case, I'd require two things:

- this should be mentioned when I report a bug - which it isn't here: http://www.haskell.org/cabal/. There's only a link to a free-form bug reporter.

- moreover, it's not obvious how to use cabal-install from HEAD while insulating it from my Haskell installation. Hence, I'd like step-by-step instructions for how to test that without messing up everything.

After looking at

http://www.haskell.org/cabal/
https://github.com/haskell (that is, the README)
https://github.com/haskell/cabal/blob/master/HACKING
http://www.haskell.org/cabal/code.html

I found no detailed installation instructions. I found something more here:

https://github.com/haskell/cabal/tree/master/Cabal
https://github.com/haskell/cabal/tree/master/cabal-install

but still, they only describe how to install cabal, not how to deal with development versions. I suppose that something better could be achieved with cabal-dev, but I'm not familiar enough with the tool to use that just to report a bug.

Could the documentation be improved?

**Comment by ttuegel** [comment]
Bug reports against release versions are perfectly acceptable. In some cases, bugs are fixed in the `master` branch before they are actually reported, so it can be helpful to test against `master` to see if we simply need to cherry-pick a patch to a release branch. There are now detailed instructions for building Cabal and cabal-install from Git in [HACKING.md](https://github.com/haskell/cabal/blob/master/HACKING.md).
