### ISSUE TITLE
Needlessly dire warnings when reinstalling dependencies in a sandbox

### ISSUE THREAD

**Issue by zopa** [haskell/cabal#1566]
When developing two packages concurrently, with the downstream package sandboxed, cabal (properly) reinstalls the upstream package each time upstream changes. Each time, cabal complains, "Warning: Note that reinstalls are always dangerous."

Given that we're in a sandbox, I think cabal is overreacting. Just reinstall already, without all the drama.

Is there any reason not to suppress that warning in the sandbox case? Not the hugest issue, but potentially frightening to new users.

**Comment by mietek** [comment]
#1275 has a different focus, and is not going anywhere. This is purely a UI issue. Warning the user that performing an action is “dangerous” immediately before performing the action, without allowing the user to abort the operation, is not helpful.

If we’re performing reinstalls automatically because it’s safe to do so, there should be no warning.
