### ISSUE TITLE
Cabal-install as a library

### ISSUE THREAD

**Issue by wdanilo** [haskell/cabal#1597]
Hello! I would love to use `Distribution.Client.* tree` as a library - it has got a lot of useful functions, we can use to create custom behaviours. Right now it is used only by the `cabal` executable, but I do no think it will take much time to separate it as a library and create a simple `Main.hs` using this library to produce `cabal` executable.

I've asked about it on Haskell's IRC and I'm not the only person who finds this idea to be usefull.

**Comment by BardurArantsson** [comment]
-1000. This is a terrible idea *unless* there is some specific design which considers the API *very* thoroughly[1] and ensured that no process-wide state (or termination and such) can possibly leak. Cabal-install is designed as and must remain an-executable-only, for reasons mentioned by @dcoutts and @ttuegel.

[1] ... and even so, it might unduly constrain what are essentially internal APIs and needlessly slow down or outright prevent global refactoring.

In addition there are just too many way cabal-install potentially affects the current process state, e.g. signals, std I/O buffering, current working dir (not currently, but potentially), etc.

We should just work to make cabal-the-executable more flexible so that you don't *have* to write something which uses it as a library.

**Comment by BardurArantsson** [comment]
Just to clarify: I'd consider this a WONTFIX and close it with prejudice. But maybe that's just me.

**Comment by bgamari** [comment]
@BardurArantsson I think we need to be a bit more nuanced here. There are portions of functionality currently implemented in `cabal-install` which can be cleanly split out and the community as a whole can easily benefit from. Take, for instance, the solver.

I agree that just adding a library section to `cabal-install.cabal` is probably not the right way to go, but with little effort we can end up with something much more extensible than we have now. As someone who has worked on Haskell tooling in the past, my opinion is that `cabal-install` currently impedes tool development where it should be helping it.

**Comment by BardurArantsson** [comment]
I agree that e.g. the solver should perhaps be split out, but then perhaps there should be an issue for separating the solver out? (Perhaps there already is, haven't looked.)

I detest abstract issues like "Make this a library" because they're not really actionable unless there's a concrete plan. It's fine to think about these things and come up with plans, but IMO this kind of discussion should probably take place on a mailing list[1] where enough people will actually have a chance to see it. I certainly know that I would never ever have discovered this particular issue (and subsequent discussion) unless I'd happened to be trawling through the issue track since I've starting developing a bit for Cabal. I *was*, however, lurking on the development mailing list for a *long* time before that (several years, I think).

[1] Since that's what this particular project seems to be using for general development discussion.

**Comment by bgamari** [comment]
@BardurArantsson indeed there is, #2768.

Fair enough, I agree that this sort of discussion of general direction should probably occur in a more visible forum.

**Comment by quasicomputational** [comment]
Another significant use-case: reading and writing `.project` files. Reading freeze files is a significant thing that programs are going to want to do, and there are also cases for generating `.project` files. Currently, the best way to get at a build plan is to grub around with `plan.json`, even if you've got a freeze file sitting there that has all the information anyway, which feels needlessly fragile and silly.

**Comment by hvr** [comment]
minor nitpick: no, the `.freeze` does *not* yet uniquely determine the build-plan in the presence of qualified goals (there's a ticket about which describes how to make the constraint-syntax expressive enough to achieve that). So in fact, the `plan.json` file is currently the most accurate description of the build-plan we have, and the `plan.json` has also been intended to serve as date interchange format to communicate the build-plan to other tooling.

**Comment by gbaz** [comment]
Arguably, rather than an umbrella thing, we could granularly consider which
individual components of cabal-install could be migrated to
Cabal-the-library on a case by case basis.

**Comment by BardurArantsson** [comment]
It's completely unrealistic to think that anything like this will happen. There's way too much inertia in the code base and in the project. (Being hamstrung by a very long backward-compat 'guarantee' for Cabal doesn't help either. For one thing it makes it very "dangerous" to move things from cabal-install to Cabal because then the project it stuck with those possibly-bad decisions, effectively forever.)

I gave it a good shot by splitting out the solver[1], but actually creating a separate "intermediate" solver package 'between' Cabal and cabal-install stalled on much hemming and hawing over (of all things) the minutiae of version numbers... It would actually have been very little extra work and would trivially have prevented the back-sliding mentioned in [1]. AFAICT this happens with almost every major change anybody who's not already "an insider" tries to do... and that wasn't even a major externally visible change. (I'm not particularly bitter though it may sound like it. Just disappointed.)

The only way forward to avoid complete ossification is disruption, I'm afraid. I have no idea where that disruption would come from, but certainly Stack has provided some of that (for better or worse, I haven't ever even used it knowingly). I also get the gut feeling that a lot of the inertia in the project is due to fear of disruption or of being rendered irrelevant.

[1] It was split into a separate module with no dependencies back to cabal-install. Of course those dependencies then crept back because there was no mechanism in place to prevent that such as keeping it in a separate package.

**Comment by 23Skidoo** [comment]
I think that with the more frequent release schedule forced on us by GHC HQ (which I consider a good thing for the project) this is now more realistic. If we can't backport a patch because it introduces a breaking API change, it's less of a problem if major releases are frequent.

**Comment by phadej** [comment]
I'm against growing the API surface of Cabal-the-library. It's already too big. Splitting parts of cabal-install into auxiliary libs is OTOH not a bad idea. (Case example: hackage-security, though it has been developed as a separate lib from the beginning)

**Comment by hvr** [comment]
@BardurArantsson 

> It was split into a separate module with no dependencies back to cabal-install. Of course those dependencies then crept back because there was no mechanism in place to prevent that such as keeping it in a separate package.

But we do have that mechanism! We just couldn't use it yet as it was too new. But soon we can!

**Comment by BardurArantsson** [comment]
@hvr Which mechansim are you talking about? Multiple private libraries in a package?
