### ISSUE TITLE
cabal does not support https remote-repo

### ISSUE THREAD

**Issue by Perseid** [haskell/cabal#1616]
Hi,

apparently cabal does not support access to `remote-repo`s via _https_ (i.e. using TLS). If I change 

```
remote-repo: hackage.haskell.org:http://hackage.haskell.org/packages/archive
```

to 

```
remote-repo: hackage.haskell.org:https://hackage.haskell.org/packages/archive
```

in my `~/.cabal/config` I get the following error message when running `cabal update`:

```
$ cabal update
Downloading the latest package list from hackage.haskell.org
cabal: https not supported
```

Unfortunately this means I cannot use cabal in hostile networks like public WLANs for example.

**Comment by DaveCTurner** [comment]
FWIW, I would like to be able to use `https` URLs for privacy (not integrity, that's what #936 is about).

We have a corporate package repository that contains company-internal packages. At the moment this is exposed inside the company network over `http` and you have to do all sorts of mucking around with the VPN to get to it when on the road. Pretty much every other internal service is available over `https` which is significantly more convenient while still ensuring that the data is still private on the wire. We can't do that here since `cabal` doesn't support `https`.
