### ISSUE TITLE
Sandboxes will install from hackage if locally-added source doesn't fit the constraints.

### ISSUE THREAD

**Issue by chowells79** [haskell/cabal#1648]
If you add a local source location to a cabal sandbox, cabal will still install the package from hackage if the local version doesn't satisfy constraints and a version on hackage does.

I tested this by modifying a project to uselessly depend on one of my libraries, then adding its source to the cabal sandbox, and updating its version number.

```
$ cabal sandbox add-source ../nano-cryptr
$ cabal install --dependencies-only --dry-run
Resolving dependencies...
In order, the following would be installed (use -v for more details):
nano-cryptr-0.1.1.3 (latest: 0.2.0.0)
```

The version 0.2.0.0 exists in my local source only.  0.1.1.3 is the latest version on hackage. The .cabal file for the current project restricted the version of `nano-cryptr` to `< 0.1.2`.

I'm strongly of the opinion that if you add a local source, it should constrain builds in that sandbox to getting the package it contains only from the local source. If the constraints end up not being satisfiable, it's an issue with the code being developed that needs to be corrected. Falling back to a version on hackage to satisfy constraints means you can fail to test the local code you were intending to test.

**Comment by ttuegel** [comment]
There's another facet to this issue: add-source packages won't be used (even if they satisfy the constraints) unless their version number is *greater* than the version number of an already-installed instance of the same package. For example, our GHC HEAD test on Travis is failing right now because cabal-install is built against the Cabal-1.23 that comes with GHC HEAD, rather than the add-source Cabal-1.23 that coming from our repository.

**Comment by phadej** [comment]
sandbox functionality is removed.
