### ISSUE TITLE
cabal repl failed on Windows

### ISSUE THREAD

**Issue by Zane-XY** [haskell/cabal#1797]
I am using cabal 1.20 on Windows 7 64 bit.
run `cabal repl` inside cabal project, get the following error:

```
Loading package ieee754-0.7.3 ... ghc.exe: m: The specified module could not be found.
<command line>: can't load .so/.DLL for: m.dll (addDLL: could not load DLL)
```

**Comment by Kludgy** [comment]
Just  had a similar looking symptom while attempting to `cabal repl` a project with a `cairo-0.13.0.6` dependency.

```
Loading package cairo-0.13.0.6 ... ghc.exe: libz: %1 is not a valid Win32 application.
<command line>: can't load .so/.DLL for: libz.dll (addDLL: could not load DLL)
```

`%1 is not a valid Win32 application` looks like an OS error caused by an unexpected file format. (Perhaps mismatched 32/64 bit?)

What's really strange is that I have no `libz.dll` (it should resolve to `zlib1.dll`), but there is a suspicious looking `gtk+-bundle_2.22.1-20101229_win64/lib/libz.dll.a` in my path. Chalking this one up to quirks with 64-bit right now.


Environment:
* Win7 Home Premium SP1
* MinGHC: GHC 7.8.4 (64-bit) [1] with cabal upgraded to 1.22.
* `gtk+-bundle_2.22.1-20101229_win64.zip` [2]

----
[1] https://s3.amazonaws.com/download.fpcomplete.com/minghc/minghc-7.8.4-x86_64.exe
[2] http://www.gtk.org/download/win64.php

**Comment by gbaz** [comment]
Are we sure this isn't a ghci issue rather than a cabal repl issue?

**Comment by 23Skidoo** [comment]
Not sure, `cabal repl` may need to set up some paths for ghci. Someone should investigate.

**Comment by Mistuke** [comment]
I think this issue can be closed. This issue is related to the runtime linker of GHC. GHCi prior to 7.10 (maybe 7.12) doesn't support import libraries. So this was never going to work. To explain the error:

```
<command line>: can't load .so/.DLL for: m.dll (addDLL: could not load DLL)
````

when the linker absolutely can't find a library, it assumes it must be a `dll` and that the system loader must be able to find it. It doesn't so it errors out. It doesn't find the `libm.a` dummy stub.

`libm` is a dummy on Windows and instead `libmingwex` needs to be used. This is all taken care of by ghci nowadays.

> What's really strange is that I have no libz.dll (it should resolve to zlib1.dll), but there is a suspicious looking gtk+-bundle_2.22.1-20101229_win64/lib/libz.dll.a in my path. Chalking this one up to quirks with 64-bit right now.

This is how dynamic linking on Windows works. In short, Windows externalizes the `PLT` and `GOT` sections. So instead of having everything in one shared library, it splits them into two, 1. an import library and 2. a dll.

You're supposed to link against the import library and never against the dll itself. In fact, the latter is only a quirk that `ld` allows and Microsoft linkers don't.

The runtime linker is quite different now, all these scenarios should be working fine now.
