### ISSUE TITLE
Use per-component cabal_macros.h 

### ISSUE THREAD

**Issue by bennofs** [haskell/cabal#1893]
I have a project that builds a library and has some benchmarks. Now, everytime I switch the benchmarks from disabled to enabled (I don't enable them all the time to make building faster when only working on the library), `cabal_macros.h` changes because it has different dependencies than the library. This causes parts of the library to be recompiled.  Using a per-component cabal_macros.h would solve the issue.

**Comment by ezyang** [comment]
I think in the course of #3022 I will fix this bug.

**Comment by ezyang** [comment]
No, I'm bailing. The problem is that if we have separate `cabal_macros.h` per library, the preprocessors need to know about what component they are building. Currently, the `Preprocessor` interfaces does not get this information, so we'd need to extend this interface. Unfortunately, the preprocessor hooks are a very commonly used interface in Custom setup files, so we need to decide if we're going to break it for more recent Cabal, or try to support this in a backwards compatible way.

**Comment by 23Skidoo** [comment]
> But actually, I think this is OK, because with custom-setup, people who depend on old Cabal won't pick up a breaking version of Cabal.

You mean `setup-depends`? Yes, that's what it's for. We should start taking advantage of it!

**Comment by 23Skidoo** [comment]
#3022 has been merged, I believe that this is fixed now.
