### ISSUE TITLE
cabal format adds empty lines with trailing whitespace

### ISSUE THREAD

**Issue by tibbe** [haskell/cabal#1966]
If you run `cabal format` on e.g. in the `cabal-install/` directory, you'll see that `cabal format` adds empty lines with trailing whitespace (i.e. 4 spaces). It shouldn't do that.

**Comment by osa1** [comment]
Cabal file generators(`cabal format`, `cabal init`, probably some other commands?) always do this. As also pointed out by @23Skidoo this is related with `pretty` library, which generates trailing space if we have a code like `nest 4 (text "" $+$ ...)`.

I can think several solutions:

1. We can modify `pretty` library and add a new `EmptyLine` constructor to `Doc`, then handle that in vertical composition functions specially to not generate any whitespace, only generate a "\n". Then we can use `emptyLine` instead of `text ""`.

2. We can make significant refactoring in Cabal pretty printer to not have any `text ""` inside `nest`. (this is probably very hard to do, and resulting code may not be very good)

3. We can wrap `writeCabalFile` and `writeGenericPackageDescription` with a function that removes trailing white space with the cost of an extra copy.

(3) seems to be the easiest solution, however I think (1) is the best, because as far as I can understand from the API docs of `pretty`, it doesn't provide a way to insert newlines, without having them indented and this seems to be a limitation of the library.

What do you think? Should we go with (3) for now?

**Comment by 23Skidoo** [comment]
I like option (1) best, (3) could be a temporary workaround.

**Comment by osa1** [comment]
I implemented (1), but I need some reviewers. I'm trying to get in contact with `pretty` maintainers, hopefully we can fix this in a principled way.

**Comment by 23Skidoo** [comment]
@osa1 Great, thank you for working on this.

**Comment by byorgey** [comment]
What's the status of this?  @osa1 , can you post here a link to your implementation of (1)?

**Comment by osa1** [comment]
I feel like it's trivial to implement for someone who knows internals of `pretty`, and I asked for help here https://github.com/haskell/pretty/issues/26 because I don't know the internals, and lack of documentation is a problem. Main problem is that even though it's possible to do without adding any new `Doc` constructor, some internals, documentation and maybe even invariants need to be changed, and it's not trivial for me to figure out what to change. I think I can spare some time for this after tomorrow.

**Comment by gbaz** [comment]
Is this resolved?

**Comment by phadej** [comment]
Not yet. #5737 resolve this though.

**Comment by jneira** [comment]
#5737 is merged so I am gonna close it, @tibbe feel free to reopen if it is not resolved for you
