### ISSUE TITLE
cabal-install does not search for .cabal-sandbox in parent directories

### ISSUE THREAD

**Issue by kgadek** [haskell/cabal#2004]
## Currently

cabal-install does not search for .cabal-sandbox in parent directories, which — I believe — is expected.

Example (cabal 1.20.0.3):

```
mkdir -p ~/X/Y/Z && cd ~/X
cabal sandbox init
cd ~/X/Y/Z && cabal install hello  # this installs hello in ~/.cabal/bin
cd ~/X     && cabal install hello  # this installs hello in ~/X/.cabal-sandbox/bin
```
## Proposal

Search recursively for .cabal-sandbox in the parent directories, up to the `/` (root dir):

```
mkdir -p ~/X/Y/Z && cd ~/X
cabal sandbox init
cd ~/X/Y/Z && cabal install hello  # this should install hello in ~/X/.cabal-sandbox/bin
```

Probably we could add an option to `cabal.sandbox.config` telling it to not propagate in the tree (current behaviour), so:

```
mkdir -p ~/X/Y/Z && cd ~/X
cabal sandbox init --no-propagate
cd ~/X/Y/Z && cabal install hello  # this should install hello in ~/.cabal/bin
cd ~/X     && cabal install hello  # this should install hello in ~/X/.cabal-sandbox/bin
```

**Comment by seanparsons** [comment]
This behaviour totally caught me off guard because when using cabal exec it didn't flash up anything saying "By the way, I'm not using a sandbox because there isn't one in this folder." it just ran ghc and then I sat there bemused as to why the library wasn't present.

If the default behaviour is to not search I'd say it would be much more preferable for it to just fail if the sandbox isn't present, principle of least surprise and all that.

**Comment by yaccz** [comment]
:+1:

**Comment by phadej** [comment]
sandbox functionality is removed.
