### ISSUE TITLE
--allow-newer suddenly requires Cabal >=1.19.2 to be available

### ISSUE THREAD

**Issue by edsko** [haskell/cabal#2023]
```
# cabal install pandoc-1.12.4.2 -j1 --avoid-reinstalls --allow-newer --constraint texmath==0.6.7
Resolving dependencies...
Failed to install pandoc-1.12.4.2
cabal: Error: some packages failed to install:
pandoc-1.12.4.2 failed during the configure step. The exception was:
user error (The package 'pandoc' requires Cabal library version >=1.19.2 &&
>=1.10 but no suitable version is installed.)

[scratchpad-783 ~/env]
# ghc-pkg list | grep Cabal
    Cabal-1.18.1.3
```

This seems a spurious requirement, and is annoying because it very useful that the `cabal` binary can be copied from one Haskell install to another without bootstrapping it (more specifically, without copying anything else -- just the binary).

**Comment by 23Skidoo** [comment]
Reopening: error message should be improved.

**Comment by ulysses4ever** [comment]
Couple notes:

- The source of the error message: https://github.com/haskell/cabal/blob/45b2c34514e12b625dc86281b61d031870dd7897/cabal-install/src/Distribution/Client/SetupWrapper.hs#L683-L686

- The restriction with 1.19.2 if allow-newer/older specified is implemented here: https://github.com/haskell/cabal/blob/45b2c34514e12b625dc86281b61d031870dd7897/cabal-install/src/Distribution/Client/Configure.hs#L99-L101

The error message could be something like: `Current build configuratiion/flags requires Cabal library version >=1.19.2 && >=1.10 to build 'pandoc', but no suitable version is installed` (instead of `The package 'pandoc' requires Cabal library version >=1.19.2 && >=1.10 but no suitable version is installed`). But I'm not sure if this message can appear under circumstances other than those presented in this issue (i.e. `--allow-newer`+ only `Cabal < 1.19.2` available).

Another way to fight it could be to  drop the check (referenced in the second bullet-point above) altogether on the grounds that `cabal-install-3.x` and future would hardly build with `Cabal < 1.19.2`. How does that sound?

**Comment by Mikolaj** [comment]
> Another way to fight it could be to drop the check (referenced in the second bullet-point above) altogether on the grounds that `cabal-install-3.x` and future would hardly build with `Cabal < 1.19.2`. How does that sound?

That's a good idea. Cabal 1.19.2 is way beyond our 5 years support window (https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md). We are currently on the verge of dropping 1.22 or 1.24 IIRC.
