### ISSUE TITLE
cabal sandbox delete should reset $GHC_PACKAGE_PATH

### ISSUE THREAD

**Issue by mpickering** [haskell/cabal#2381]
Currently if you delete a sandbox whilst inside `cabal exec bash` then `$GHC_PACKAGE_PATH` is still set to point to a non-existent file.

**Comment by tibbe** [comment]
Is this even possible. I don't think a running process (i.e. cabal sandbox delete) can affect the environment of the shell it's running in.

**Comment by 23Skidoo** [comment]
I don't think it should do that, but printing a warning is reasonable.

**Comment by BardurArantsson** [comment]
As @tibbe notes, deletion from the owning process environment is impossible. The remaining bit, namely a warning on pointing to non-existent dir/file/whatever could perhaps just be merged with #2224? It seems that it would be trivial to implement both at the same time. (Unless I'm missing something.)

**Comment by BardurArantsson** [comment]
(This is, i'd suggest this issue simply be closed as merged with #2224.)

**Comment by BardurArantsson** [comment]
Actually, I take that back. The fixes are sufficiently different that my suggestion doesn't make sense.

**Comment by BardurArantsson** [comment]
Ok, so here's a suggested fix: https://github.com/BardurArantsson/cabal/commit/7c4452b0beec1524384e706c04ee5734f3dc82ab

I'm quite uncertain about this one since it appears the relevant code is actually only run on `cabal exec` and I'm not sure whether that's sufficient for what the reporter had in mind. However, it *is* the only place GHC_PACKAGE_PATH is actually read, so... I suspect a full fix would require GHC to be more picky and/or informative if given an invalid GHC_PACKAGE_PATH.
