### ISSUE TITLE
Undocumented fields in the user manual

### ISSUE THREAD

**Issue by osa1** [haskell/cabal#2481]
Cabal accepts `extra-include-dirs` field in the file, but 1) it's not working 2) it's not documented 3) seems to be replaced with `include-dirs`.

EDIT: I wasted an hour trying to fix a linker problem and here's what I found:

Cabal has `lib-dirs`, `include-dirs` and `libraries` fields, and a `extra-` prefixed version of each. In the user manual:

`extra-lib-dirs` is documented , but `lib-dirs` is missing.
`include-dirs` is documented, but `extra-include-dirs` is missing.
`extra-libraries` is documented, but `libraries` is missing.

And clearly those are not the same, i.e. `extra-lib-dirs` and `lib-dirs` are used differently. (I had to use both in my program to make it working)

So I think user guide needs improvements.

**Comment by osa1** [comment]
(also changed the title)

**Comment by bollu** [comment]
This doesn't work even now AFAIK. I've been trying to write bindings to `SymEngine`, and cabal just doesn't accept `--extra-lib-dirs`. It's frustrating.

[Here is the travis.yml](https://raw.githubusercontent.com/bollu/symengine.hs-1/basic-libs/.travis.yml)

[Here is a cabal build that is failing](https://travis-ci.org/symengine/symengine.hs/jobs/130275588)


On the other hand, [here is the succeeding stack build](https://travis-
ci.org/symengine/symengine.hs/jobs/130275588) for the same commit.

I find this *insane*, that cabal still has problems that shouldn't be problems, which stack solves this perfectly.

How can I help fix this error / how do I solve this anyway? cabal doesn't accept `--lib-dirs` as a command line parameter either so I really don't know how to tell cabal that I have a library in a non-standard location

**Comment by ezyang** [comment]
I am confused. `cabal configure --extra-lib-dirs` works for me:

```
ezyang@sabre:~/Dev/labs/cc$ ls
A.hs  cc.cabal  ChangeLog.md  LICENSE  Setup.hs
ezyang@sabre:~/Dev/labs/cc$ cabal configure --extra-lib-dirs=/tmp
Resolving dependencies...
Configuring cc-0.1.0.0...
ezyang@sabre:~/Dev/labs/cc$ cabal build -v
Component build order: library 'cc'
Building cc-0.1.0.0...
/usr/bin/ghc-pkg init dist/package.conf.inplace
creating dist/build
creating dist/build/autogen
Preprocessing library cc-0.1.0.0...
Building library cc...
creating dist/build
/usr/bin/ghc --make -fbuilding-cabal-package -O -j1 -static -dynamic-too -dynosuf dyn_o -dynhisuf dyn_hi -outputdir dist/build -odir dist/build -hidir dist/build -stubdir dist/build -i -idist/build -i. -idist/build/autogen -Idist/build/autogen -Idist/build -optP-include -optPdist/build/autogen/cabal_macros.h -package-name cc-0.1.0.0 -hide-all-packages -package-db dist/package.conf.inplace -package-id base-4.7.0.2-5ef1e7e809bc3b18d74efc783356e209 -XHaskell2010 A
[1 of 1] Compiling A                ( A.hs, dist/build/A.o )
Linking...
[(SimpleUnitId (ComponentId
"base-4.7.0.2-5ef1e7e809bc3b18d74efc783356e209"),ModuleRenaming True [])]
/usr/bin/ar -r dist/build/objs-8806/libHScc-0.1.0.0-LmHDApNUJXzLN6FQsTlkp7.a dist/build/A.o
/usr/bin/ar: creating dist/build/objs-8806/libHScc-0.1.0.0-LmHDApNUJXzLN6FQsTlkp7.a
/usr/bin/ghc -shared -dynamic -L/tmp '-dynload deploy' -optl-Wl,-rpath,/usr/lib/ghc/base-4.7.0.2 -optl-Wl,-rpath,/usr/lib/ghc/rts-1.0 -optl-Wl,-rpath,/usr/lib/ghc/ghc-prim-0.3.1.0 -optl-Wl,-rpath,/usr/lib/ghc/integer-gmp-0.5.1.0 -no-auto-link-packages -package-db dist/package.conf.inplace -package-id base-4.7.0.2-5ef1e7e809bc3b18d74efc783356e209 dist/build/A.dyn_o -o dist/build/libHScc-0.1.0.0-LmHDApNUJXzLN6FQsTlkp7-ghc7.8.4.so
/usr/bin/ghc-pkg recache '--package-db=dist/package.conf.inplace'
```

(look for `-L`).

I don't really know what is going on with `extra-lib-dirs` in the package description format, but that was added by ekarttun in a693cd597847549f9711daa857d7dbf0af6382d0; the flag was added later by Pepe Iborra in 6040df41d4b17ae6694f1f761b748e1b31a9bb65.

**Comment by bollu** [comment]
hm, interesting. And no, I'm not passing it through the `.cabal` file, I'm passing it through the `cabal install`.

Here is the exact `cabal install` invocation: [Link](https://travis-ci.org/symengine/symengine.hs/jobs/130275585#L1964)

As I have said, a similar `stack build` works: [Link] (https://travis-ci.org/symengine/symengine.hs/jobs/130275590#L1865)

Thanks a lot for your help, I really appreciate it!

**Comment by ezyang** [comment]
Can you run this with `-v`? I want to see if `-lsymengine` is being passed to the compiler.

And just a random idea, but can you try a more recent version of Cabal/cabal-install?

`cabal install` passes `--extra-lib-dirs` just fine for me too:

{{{
ezyang@sabre:~/Dev/labs/cc$ cabal install --extra-lib-dirs=/tmp -v
<snip>
/usr/bin/ghc -shared -dynamic -L/tmp '-dynload deploy' -optl-Wl,-rpath,/usr/lib/ghc/base-4.7.0.2 -optl-Wl,-rpath,/usr/lib/ghc/rts-1.0 -optl-Wl,-rpath,/usr/lib/ghc/ghc-prim-0.3.1.0 -optl-Wl,-rpath,/usr/lib/ghc/integer-gmp-0.5.1.0 -no-auto-link-packages -package-db dist/package.conf.inplace -package-id base-4.7.0.2-5ef1e7e809bc3b18d74efc783356e209 dist/build/A.dyn_o -o dist/build/libHScc-0.1.0.0-LmHDApNUJXzLN6FQsTlkp7-ghc7.8.4.so
}}}

In any case, the error is not consistent with `--extra-lib-dirs` not being passed to Cabal, because the error you are getting during compilation is a missing symbol rather than a missing library. So this seems to suggest that the library is not making it to the build in the first place. I can't tell from your Travis log because it doesn't have enough information.

**Comment by bollu** [comment]
@ezyang  - Thanks for the help, but I think I figured the issue out.

For the library to link, it supposedly needs to have the other module in the `other-modules`.

Here's the edited [`.cabal`] file(https://github.com/symengine/symengine.hs/blob/master/symengine.cabal)

The build passes and runs the tests: [Here's a `travis` log](https://travis-ci.org/symengine/symengine.hs/jobs/130454900#L1871)

I think the `cabal` error message is terrible though, since it simply tells you the linker fails, but it doesn't tell you _why_ it does.

For the sake of documentation, here's how you fix it

#### Fix for the error

I'm writing the down for SEO.

##### Error
```
In function `___':
(.text+__): undefined reference to `___'
```
##### Keywords
```
haskell cabal build travis test source-modules undefined reference FFI
```

1. The fix is to added the module the un-linkable functions are present into `other-modules` in your `.cabal` file.

2. If the module can't be found, then add the source folder of the module into the `hs-source-dirs` part of the `.cabal` file

**Comment by ezyang** [comment]
I am very confused by your proposed fix. I don't see any change to `other-modules` in your Cabal file history.

**Comment by bollu** [comment]
@ezyang  - Apologies, I pointed you to the `.cabal` file on the wrong branch. I've edited the comment to point to the right one.

[Here is the link](https://github.com/bollu/symengine.hs-1/blob/basic-libs/symengine.cabal#L35)

**Comment by gbaz** [comment]
The `extra-` versions of all are now documented, and it appears the non-extra versions are no longer around/used?  Which suggests to me this can be closed... (unless the non-prefixed versions are still there, undocumented, and of some possible use...)

**Comment by linearray** [comment]
I just checked and `lib-dirs` is gone, `libraries` appears to be gone, `include-dirs` and `extra-include-dirs` are here and well-documented. Closing this.
