### ISSUE TITLE
Properly merge preferences (dependency resolution)

### ISSUE THREAD

**Issue by lspitzner** [haskell/cabal#2645]
Preferences, as in "soft constraints" on package versions are not properly merged. The primary symptom is that for any package with any "preferred versions" defined via hackage, any preferences given on the commandline are ignored.

In the output of

~~~~.bash
> cabal install --dry-run gl --preference="gl<0.7" -v3
~~~~

contains the following two (!) lines for the gl package:

1) `gl <0.7` (from commandline flag)
2) `gl <0.7.2.1 || >0.7.2.1` (hackage preferred version)

And seemingly, the second one blindly overwrites the first. (You can observe the changed behaviour by editing the index.cache in ~/.cabal/packages/.. and temporarily removing the gl preference.) I believe changing the order as a solution for the issue is not sufficient, because then hackage preferences are ignored as soon as the user provides some preference. Instead, the two preferences should be merged. (This merging functionality must already exist for hard constraints, so this should be no problem, right?)

I would suggest giving info to the user (even without verbose) when such a merging happens.

**Comment by martinvlk** [comment]
Hi, I'll fix this one.

**Comment by martinvlk** [comment]
Hi, I think it wouldn't make sense to merge preferences. Instead, we should make the value from the command line override the Hackage preferred version.

What are these soft constraints? They are meant to specify what version range we prefer for given package, if possible. If not possible, we are willing to accept what's available, but ideally as close to our preferred range as possible.

In the case where Hackage has a preferred version range specified for a package, it means that when I install that package and don't specify any preferences of my own, I'll get what Hackage specifies.

Now say I do specify my own preferred version range on the command line.
Surely that means I want the range I specified, and not my specified range combined in some arbitrary way with a range somebody else specified.

I'm happy to hear objections and corrections on this, before I go off implementing the agreed solution.

**Comment by lspitzner** [comment]
> Surely that means I want the range I specified

No; you prefer _one version from_ the range specified. The output (install plan) contains just one version.

If maintainer says 0.2 or 0.3, and user says 0.1 or 0.2, it seems to make sense to choose/prefer 0.2 over the other. There of course still is this question of how to weight, cases like: there are install plans `A` and `B`; `A` violates one user-provided preference, `B` violates three maintainer-provided preferences. Which plan should be chosen?
(Or the more direct case of conflicting constraints for a single package.)

The user can always give hard constraints if she desires (but that is not necessarily a counter-argument).

.. on the other hand, i am not even sure if there are any specific use-cases that would hint at the "correct" solution to this design decision, and if weighting is possible given the current solver impl.
And any solution is ok if it is sufficiently verbose (e.g. if it tells you about ignored hackage preferences your solution is solid).

**Comment by grayjay** [comment]
I think that Hackage's deprecated version ranges should still apply, though they're currently combined with non-preferred ranges.  We might also want to treat deprecated version ranges more like constraints, as discussed in #1792.

@lspitzner The solver applies preferences by sorting all versions of a package by preference in the search tree and then trying the versions in order.  Handling more granular preferences in the solver would be relatively easy.

**Comment by martinvlk** [comment]
Hi, thanks a lot for the input!

Reading and re-reading your comments I figure I need more information
here before implementing a solution.

First of all, at which layer should a solution be implemented?

I first thought I can do it in `Distribution.Client.Dependency` at the
point where package preferences collected from different sources are
being "interpreted" and then passed into the solver (the
`interpretPackagesPreference` function). Here I can detect there is
multiple preferenfces for a single package and combine these in some
rudimentary way. Currently the preference which appears last in the
list is used and all other ignored.

But from what I read in the dicussion above in order to allow for more
refined/granular strategies there may be beneft in somehow passing in
all the collected ranges unchanged and let the solver work out the
best install plan. If we go this way I am not sure this bug qualifies
as "easy" any longer (I'm only starting to hack on cabal so don't have
necessary know-how).

Next - currently we don't have enough information to know which
preference comes from what source. No way to distinguish for example a
preference from the command line and a preference from Hackage. In one
way or other I think we'll need to refactor so that this kind of
information is available.

I would appreciate your views here to help me choose a good solution
to implement.

Thanks
Martin

**Comment by grayjay** [comment]
@martinvlk I can see several ways to handle this issue.  The simplest would be to combine version preferences in `interpretPackagesPreference` in a way that loses less information.  For example, you could change `data PackagePreferences = PackagePreferences VersionRange InstalledPreference` in `D.C.Dependency.Types` to use `[VersionRange]`.  Then you could update `preferredVersionsOrdering` in `D.C.Dependency.Modular.Preference` to compare versions on the number of preferences that they satisfy.

How would you weight preferences from different sources differently?  Currently, preferences are either downloaded from Hackage or specified with a `--preference` flag, which can come from the commandline or a config file.  Hackage's deprecated and preferred ranges are combined before they are added to the package index (https://github.com/haskell/hackage-server/blob/e0bd7fc2a8701a807a5551afc1ab1e9df4179e81/Distribution/Server/Features/PreferredVersions.hs#L312), so if you wanted to handle them differently, you would have to start with `hackage-server`.  As long as the two types of ranges are lumped together, I think it makes sense for them to be given the same weight as `--preference` preferences.

**Comment by martinvlk** [comment]
So I did some exploratory coding here and I see that the preference is used in three places, basically corresponding to the types of solvers we have: modular, top-down and the one ignoring dependencies.

The modular solver currently reorders packages by the fact whether they satisfy the given preference or not. If we will newly pass in a list of preferred ranges instead of one range, we can reorder packages by the number of ranges they satisfy, as @grayjay suggested.

The top-down and the simple no-deps solvers currently check whether a package is preferred by checking whether its version is within the preferred range. Then they use this bit of information along with two others to reorder packages and pick the one that satisfies most conditions. Similar concept to the modular solver, but implemented in a different way. If we will newly pass in a list of preferred ranges, we could again include a number of ranges the package satisfies as a condition in reordering instead of a simple boolean.

Does that sound like a plan?

My experimental implementation of the above seems to work, but I don't have a good way to test this, apart from running the test suites. How could I test this? Is there existing tests or do I need to come up with new ones myself?

**Comment by BardurArantsson** [comment]
@martinvlk There's been a bit of hemming and hawing about it, but AFAIUI the plan is still to remove the top-down solver at some point in the semi-near future. Perhaps it's not worth even trying to update it?

**Comment by martinvlk** [comment]
@BardurArantsson, thanks, although for now I am mostly concerned about the overall approach - the effort of updating the top-down solver code is in itself negligible. And if I want to make this change elsewhere the types will force me to update it anyway.

**Comment by grayjay** [comment]
@martinvlk Your plan sounds fine to me.  You could test preferences with the solver DSL by adding a field to `SolverTest` and then handling preferences similarly to the independent goals option.

**Comment by martinvlk** [comment]
This is being fixed in [pull/2984](https://github.com/haskell/cabal/pull/2984)

**Comment by hvr** [comment]
@BardurArantsson @martinivik is there some more concrete description of which behaviour this patch changes? the commit msg is rather terse and doesn't really explain the consequences IMO. For starters, what is considered a preference? A `--constraint` are clearly not mere "preferences", I'm rather confused.

**Comment by martinvlk** [comment]
@hvr: I hear you, fair point.

**Comment by BardurArantsson** [comment]
@hvr: Was the concern only about the commit message, or are you concerned about the actual content of the PR?

If it's just the message... I don't think there's any constent guideline for commit messages, is there? If that's the thing you were asking about, I'll try to add something with #3001.
