### ISSUE TITLE
Install Cabal into sandbox as needed

### ISSUE THREAD

**Issue by ttuegel** [haskell/cabal#2668]
Packages with `build-type: Custom` should be built with the same Cabal version as cabal-install was built with because cabal-install needs to read the saved build config written by the package. When we are in a sandbox, it is safe to install the identical Cabal library version, as needed.

See also #2214.

**Comment by DanielG** [comment]
I need essentially the same functionality for ghc-mod, would it be possible to expose this somehow? A flag to just print the path to whatever package-db this Cabal was installed into would be awesome.

I hope that by
>  [...] it is safe to install the identical Cabal library version, as needed.

you don't mean installing an arbitrary version of Cabal from source, I'm doing that in https://github.com/DanielG/cabal-helper and that's certainly not always safe I've gotten bug reports from users who have cabal-install executables with a certain version of cabal (1.22.0.0 or so) but if cabal-helper tries to install that version it fails, my guess is because whoever built the GHC distribution they were using patched Cabal/cabal-install or something ...

**Comment by ttuegel** [comment]
> that's certainly not always safe I've gotten bug reports from users who have cabal-install executables with a certain version of cabal (1.22.0.0 or so)

IIRC that was a bug in that specific version of cabal-install which was since fixed. The GHC team once shipped a patched version of Cabal, but that's a bug in their distribution; I won't tie my own hands because they're doing bad things.

**Comment by DanielG** [comment]
Ah ok, that's fine then.

**Comment by phadej** [comment]
sandbox functionality is removed.
