### ISSUE TITLE
Specify what's needed for migration away from HsColour in Haddock

### ISSUE THREAD

**Issue by Fuuzetsu** [haskell/cabal#2698]
We have a GSOC student over at Haddock who has been working on Haskell source highlighter with the notable feature of hyperlinked identifiers/types/whatever, in the style of Agda files. https://github.com/haskell/haddock/pull/410

If everything works fine on our end, we'll be looking to migrate away from HsColour though not straight away.

What would we have to do to make the process easy for cabal, past and present? Likewise for Hackage. For example, do you foresee any issues with us just changing what files `--hyperlinked-source` flag results in? Maybe there are some assumptions that cabal/hackage are making that we should be aware of. Let us know. If there's nothing then great.

**Comment by 23Skidoo** [comment]
I think we'll just a version bump once the feature is merged in so that we can distinguish between the old and new behaviour.

**Comment by Fuuzetsu** [comment]
Is there no need to worry at all about older versions?

**Comment by 23Skidoo** [comment]
With old versions of `haddock`, Cabal'll just continue using `hscolour`. Looking at [`D.S.Setup`](https://github.com/haskell/cabal/blob/master/Cabal/Distribution/Simple/Setup.hs#L1265) I see that we have a flag for specifying a CSS file for `hscolour`, so it'd be nice if Haddock continued to support `hscolour`-compatible CSS files. Other than that I don't see any potential problems -- do you?

If you will continue to support `--source-{module,entity,entity-line}`, then old versions of Cabal will continue to work with new versions of Haddock. The users won't be getting the new source hyperlinking hotness, since old Cabals will still be using `hscolour` with new Haddock, but that is fine.

**Comment by Fuuzetsu** [comment]
Not really, was just double checking. Maybe @mrhania has some questions but for now I'll close.

Thanks.
