### ISSUE TITLE
Strange "cabal sdist" warning

### ISSUE THREAD

**Issue by svenpanne** [haskell/cabal#2755]
Cabal from HEAD started to issue the warning `Warning: Cannot run preprocessors. Run 'configure' command first.` when running `cabal sdist` after a `cabal install`, see e.g. https://travis-ci.org/haskell-Opengl/OpenGL/jobs/74581138#L264. Previous versions didn't do this, see e.g. https://travis-ci.org/haskell-opengl/OpenGL/jobs/74581137#L264. Somehow the warning doesn't make sense, because the package has obviously been built before, so configuration must have happened, too.

IMHO the warning is bogus, but perhaps I misunderstood how things are supposed to work...

**Comment by svenpanne** [comment]
Just for the record: This is still the case with recent cabal versions, and ``cabal test`` behaves similarly, see https://travis-ci.org/haskell-opengl/OpenGLRaw/jobs/114109605#L929. Things have already been configured, including ``--enable-tests``, but cabal says ``Re-configuring with test suites enabled. If this fails, please run configure manually.``.

**Comment by ezyang** [comment]
The problem seems to be when you enable tests and benchmarks simultaneously. On a trivial package:

```
ezyang@sabre:~/Dev/cabal-tmp/cabal-install/tests/IntegrationTests/regression/t2755$ rm -Rf dist 
ezyang@sabre:~/Dev/cabal-tmp/cabal-install/tests/IntegrationTests/regression/t2755$ cabal configure --enable-tests --enable-benchmarks
Resolving dependencies...
Configuring test-t2755-0.1.0.0...
ezyang@sabre:~/Dev/cabal-tmp/cabal-install/tests/IntegrationTests/regression/t2755$ cabal test
Re-configuring with test suites enabled. If this fails, please run configure
manually.
Resolving dependencies...
Configuring test-t2755-0.1.0.0...
Package has no buildable test suites.
```

**Comment by ezyang** [comment]
Actually, apparently, this just doesn't work at all.

**Comment by ezyang** [comment]
OK, so the problem is related to OpenGL (and my test package) having no test suite sections. You can see this by configuring with `--enable-tests` on  `-v`:

```
ezyang@sabre:~/Dev/cabal-tmp/cabal-install/tests/IntegrationTests/regression/t2755$ cabal configure --enable-tests  -v
[snip]
Using internal setup method with build-type Simple and args:
["configure","--verbose=2","--ghc","--prefix=/home/ezyang/.cabal","--user","--ipid=test-t2755-0.1.0.0-BReSicMX0IP22iudDoBilg","--dependency=base=base-4.8.2.0-0d6d1084fbc041e1cded9228e80e264d","--disable-tests","--exact-configuration","--disable-benchmarks"]
```

Say what?! The reason for this is `cabal-install` determines whether or not `--enable-tests` should be passed to `./Setup configure` is NOT, as you might imagine, what flags were passed, but rather, whether or not the solver decided to enable the stanza. So I guess, if there is no test suite in the package, the solver disables it. But then when we reconfigure for `cabal test` we check if `--enable-tests` was passed (it wasn't) and (uselessly) reconfigure if it wasn't.

Workaround: if you don't have tests, don't call `cabal test`.

Maybe the `sdist` bug is different.
