### ISSUE TITLE
Detailed-0.9 test suite freezes on Windows

### ISSUE THREAD

**Issue by grayjay** [haskell/cabal#2762]
The test suite in `Cabal/tests/PackageTests/TestSuiteTests/LibV09/LibV09.cabal` freezes, whether I run the Cabal package tests or run `Setup.exe test` directly.  I also tried running the simpler test, BuildTestSuiteDetailedV09, which was replaced in #2508, and it also freezes on Windows.  Both tests pass on Linux.

I played around with the code that runs the tests as a sub-process and found something that works.  I'm not proposing it as a fix, since I still don't know the cause of the problem.  Here is the commit: grayjay@e69fe268a92592f122b67f4232249736e211ba5e

Summary:
* Allow `System.Process.createProcess` to create the handles to the sub-process, instead of creating the handles with `D.Compat.CreatePipe.createPipe` and passing them to `createProcess`.
* Read and write to the handles after the process is created.
* `rawSystemIOWithEnv'` is a modified copy of `rawSystemIOWithEnv`, since `rawSystemIOWithEnv` is called elsewhere.

**Comment by ttuegel** [comment]
@grayjay At one point, this is what we did. However, this can cause the subprocess to deadlock if it fills the output buffer. (It turns out, it will also deadlock anyway if compiled without `-threaded`.) What we need to do in the Cabal library is just open a log file and give the subprocess that handle for its stdout and stderr. We can do threaded things in cabal-install; we'll have to move the fancier test code there. Are you up to implementing this?

**Comment by grayjay** [comment]
@ttuegel  I would like to work on this issue, but I'm not sure I understand the problem.  I see that I ignored the subprocess' stderr in the commit that I linked to, but is there another reason that it would deadlock?  Here's a new commit that reads stderr:

https://github.com/grayjay/cabal/commit/afae3cb33c8136701673ab315c1ba01bef75fe69
