### ISSUE TITLE
Missing dependencies on foreign libraries (Windows 10)

### ISSUE THREAD

**Issue by coder-mike** [haskell/cabal#2887]
I've been trying to install [llvm-general](https://hackage.haskell.org/package/llvm-general) using Cabal, and have been running into [this problem](https://github.com/bscarlet/llvm-general/issues/156). After some digging, we think that it's not related to the llvm-general package, but is related to cabal. I think I've managed to reproduce the issue with a very simple cabal file on my system:

    name:                Cabal-Test
    version:             0.1.0.5
    cabal-version:       >=1.10
    build-type:          Simple

    library
      exposed-modules:     CabalTest
      build-depends:       base >=4.8 && <4.9
      default-language:    Haskell2010
      extra-libraries:
        mylibrary
        libmylibrary
        mylibrary.a
        libmylibrary.a
        C:/testlibdir/libmylibrary.a
        file_that_doesnt_exist
      extra-lib-dirs:
        C:/testlibdir
        "C:\\testlibdir"
      include-dirs:
        C:/testlibdir
        "C:\\testlibdir"

(I added different combinations of directory paths and prefixes according to various sources of information and theories, and from lack of finding documentation that that specifies one way or another)

When I try to install, I get this error:

    $ cabal install .
    Resolving dependencies...
    Configuring Cabal-Test-0.1.0.5...
    Failed to install Cabal-Test-0.1.0.5
    Build log ( C:\Users\elecm.DESKTOP-JQGRHSF\AppData\Roaming\cabal\logs\Cabal-Test-0.1.0.5.log ):
    Configuring Cabal-Test-0.1.0.5...
    setup-Simple-Cabal-1.22.4.0-x86_64-windows-ghc-7.10.2.exe: Missing
    dependencies on foreign libraries:
    * Missing C libraries: mylibrary, libmylibrary, mylibrary.a, libmylibrary.a,
    C:/testlibdir/libmylibrary.a, file_that_doesnt_exist
    This problem can usually be solved by installing the system packages that
    provide these libraries (you may need the "-dev" versions). If the libraries
    are already installed but in a non-standard location then you can use the
    flags --extra-include-dirs= and --extra-lib-dirs= to specify where they are.
    cabal.exe: Error: some packages failed to install:
    Cabal-Test-0.1.0.5 failed during the configure step. The exception was:
    ExitFailure 1

The key lines to me are these:

    Missing dependencies on foreign libraries: 
    * Missing C libraries: mylibrary, libmylibrary, mylibrary.a, libmylibrary.a, C:/testlibdir/libmylibrary.a, file_that_doesnt_exist

The libraries that I'm trying to statically link to in this case are here:

    $ ls C:/testlibdir
    libmylibrary.a  mylibrary.a  mylibrary.c  mylibrary.h  mylibrary.o

The key point is that it lists all the "extra-library" dependencies as missing, regardless of which name I use, and whether or not they exist. 

I created a very basic static library with one function, to minimize the number of experimental variables, and as you can see the header file is in the same directory.

I'm using cabal-install 1.22.6.0 and GHC 7.10.2, which installed with the Haskell Platform. I'm using Windows 10. I've tried these experiments with both Cygwin and from the Windows Cmd.

I've been struggling with this issue for about a month, stuck just trying to install one package that I need. Do you have any ideas that might help diagnose the problem?

**Comment by adbak** [comment]
Any luck with the problem? I'm facing the same difficulties (with llvm-general and exactly the same environment) and nothing seems to work. On the other hand, everything went fine on my Ubuntu. So it looks like cabal have this problem only on Windows (and only the new ones apparently?). Maybe there is at least some workaround to install llvm-general (by modifying Setup.hs in this package or sth like this) despite this error?

**Comment by coder-mike** [comment]
No, I haven't had any luck. Posting the issue here was my last-ditch effort to try get past this problem after weeks of struggling with it and trying many different solutions (I elaborated more about the solutions I tried in [the llvm-general issue](https://github.com/bscarlet/llvm-general/issues/156) that I referenced from here).

If you figure out a work-around, please post it here. I tried various modifications to Setup.hs, with no luck. But I'm a newbie to Haskell (and Cabal), so I may have missed something obvious.

**Comment by adbak** [comment]
I sure will post it here, but sometimes I lose hope it can be work-arounded. However today I discovered something interesting. 

We both have the same environment: Windows 10, newest cabal, Haskell Platform 7.10.2-a, MinGW with gcc 4.8 (if I remember correctly, this particular version was needed to build LLVM, not the old 4.6 one). So MinGW was installed separately, right?

I'm a newie to Haskell (and Cabal) too, so since Cabal didn't want to cooperate, I was trying to install llvm-general package without it (not knowning exactly what I'm doing).

So I downloaded package's tarball, unpacked it, changed directory in cmd and run:
<code>runghc Setup.hs configure --user</code>

Obviously this gave me the same "Missing dependencies on foreign libraries" error.
But then, despite the fact that configure step failed, I run:
<code>runghc Setup.hs build</code>

And the key point of this message is this result:
<code>Setup.hs: warning: tzset from msvcrt is linked instead of imp__tzset</code>
<code>cc1.exe: error: unrecognized command line option **'-std=c++11'**</code>
<code>compiling dist\build\LLVM\General\Internal\LibraryFunction_hsc_make.c failed (exit code 1)</code>
<code>command was: **C:\Program Files\Haskell Platform\7.10.2-a\mingw\bin\gcc.exe** -c dist\build\LLVM\General\Internal\LibraryFunction_hsc_make.c -o dist\build\LLVM\General\Internal\LibraryFunction_hsc_make.o -D__GLASGOW_HASKELL__=710 -Dmingw32_BUILD_OS=1 -Dx86_64_BUILD_ARCH=1 -Dmingw32_HOST_OS=1 -Dx86_64_HOST_ARCH=1 -Isrc -IC:\LLVM\llvm-3.5.2/include -std=c++11 -D_CRT_SECURE_NO_DEPRECATE -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -D_CRT_NONSTDC_NO_WARNINGS -D_SCL_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_WARNINGS -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -Idist\build\autogen -include dist\build\autogen\cabal_macros.h -IC:\Program Files\Haskell Platform\7.10.2-a\lib\bytes_6elQVSg5cWdFrvRnfxTUrH\include -IC:\Program Files\Haskell Platform\7.10.2-a\lib\base_GDytRqRVSUX7zckgKqJjgw\include -IC:\Program Files\Haskell Platform\7.10.2-a\lib\integ_2aU3IZNMF9a7mQ0OzsZ0dS\include -IC:\Program Files\Haskell Platform\7.10.2-a\lib/include -IC:\Program Files\Haskell Platform\7.10.2-a/lib/include/</code>

That's something new. How come --std=c++11 is an unrecognized option? The answer is in the second bolded line. That's not my MinGW directory... Haskell Platform, as shown above, installs his own MinGW, and when I run cmd:
<code>"C:\Program Files\Haskell Platform\7.10.2-a\mingw\bin\gcc.exe" --version</code>
I get:
<code>gcc.exe (rubenvb-4.6.3) **4.6.3**
Copyright (C) 2011 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.</code>

Without this path, and by just simply typing 
<code>gcc --version</code> 
I get:
<code>gcc (GCC) **4.8.1**
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.</code>
Because then the system looks for gcc in PATH variable, which has my separate (and desired one) MinGW installation directory at the beginning.

So maybe this whole problem is not in Cabal per se? This program is well know for not accurate error messages. The problem is in compilation. In fact, llvm-general.cabal file has this line:
<code>cc-options: -std=c++11</code> 
It seems legit, that installing this package needs newer version of gcc (installing LLVM did). However by running Haskell we are stuck with Haskell Platform's own gcc, which is too old. The question is: can we do something about it? Maybe when we upgrade MinGW in Haskell Platform's directory then we will be able to install this package? But I'm not sure how to do that neatly.

;
Obviously this problem doesn't exist on my Ubuntu, because there is only one gcc in the system, and it's version is 4.8 of course.

**Comment by adbak** [comment]
Yup, that was it. It's not a cabal bug at all. I finally installed llvm-general!
Here are the hints how to do that: 
http://stackoverflow.com/questions/33743442/cabal-cant-find-foreign-libraries
It's a long and nasty way, many things may not work. For example this wasn't enough for me.
Package installed but simple hello world:
<pre class="source">module Main where

import LLVM.General.Analysis

main :: IO()
main = do
    putStrLn "Hello World!"</pre>
Didn't want to compile. The problem was in linker. It needs to be g++, not gcc which was (in my environment) default in this case. So I need to type:
<code>ghc -pgml g++ --make Main.hs</code>
Then it compiles and run. Of course some more testing is needed to check if it works in action. But as I wrote, I'm a newbie too and so far I'm at the beginning of writing a compiler and I don't have enough experience to check llvm-general in action. But it should work.

Hope this helps you. Feel free to ask if you need any additional help regarding this subject. I will be happy to help.

As for this issue - it can be closed. The bug is only in misleading message.
