### ISSUE TITLE
Unnecessary rebuilds

### ISSUE THREAD

**Issue by edsko** [haskell/cabal#3014]
I'm still seeing unnecessary rebuilds occasionally, but I have not yet been able to pinpoint under which circumstances this happens (and of course it's always too late to run with `-v3` when it happens). I think adding some kind of on-by-default information why something is being rebuilt is a priority to track this one down.

**Comment by ezyang** [comment]
I see this too, relatively frequently in fact (invariably, GHC concludes that there's nothing to rebuild). I'll try to see what is going on.

**Comment by edsko** [comment]
Hmm, I'm also seeing actual compiles.

**Comment by dcoutts** [comment]
I just fixed one source of these. When you do:

-- make source changes
cabal new-build the-exe
cabal new-build the-lib
-- everything should be up to date now
cabal new-build the-exe
-- oh no, it tries to rebuild the exe

It accumulates a set of the components that have not changed since config/files changed.
