### ISSUE TITLE
"Could not resolve dependencies" does not output anything

### ISSUE THREAD

**Issue by mrkkrp** [haskell/cabal#3026]
OK, it's rather strange. I pushed a cosmetic commit to one project and after that build for GHC 7.6 (Cabal 1.16) fails with this:

https://travis-ci.org/mrkkrp/slug/jobs/99976117#L176

Note that it built OK previously and that commit didn't change dependency list or something. Now, as you can see, Cabal is no longer able to resolve dependencies, and it does not print any information about what exactly it does and what goes wrong. Builds for other GHC/Cabal versions succeed (restarted several times, only GHC 7.6 + Cabal 1.16 case fails). I don't understand what's going on, honestly.

**Comment by ezyang** [comment]
Can you fix this issue by upgrading Cabal first and then building? What happens if you crank up the verbosity?

Looking at your build matrix, this could be an issue with Cabal 1.16, and only Cabal 1.16 (e.g. the error message got improved in a later release.) If that's the case, I'm not really sure what we can do: you should run a less buggy version.

The failure of dependency resolution is consistent with something having changed on Hackage, which caused the solver to stop working. I don't know we have a log of trustee changes.

**Comment by mrkkrp** [comment]
Cabal 1.16 is needed to test with older GHC. So, conclusion here is that dependency resolver can instantly stop working for no apparent reason. I don't understand how it's possible, unless someone has removed older versions of packages from Hackage, which is unlikely.

Where else I can ask what to do with this?

**Comment by mrkkrp** [comment]
It's still a great mystery (maybe it depends on weather or phase of moon), but kind people on `#haskell` told me to try `--reorder-goals` and it worked. Closing.
