### ISSUE TITLE
Remove other-extensions keyword

### ISSUE THREAD

**Issue by seagreen** [haskell/cabal#3081]
It seems like a bad idea to have derivable data in `.cabal` files. Library authors often put something inaccurate in this field, and even when they get it right it's unnecessary work.

Instead we could write a command to show the language extensions used in a project. That command could be made available as a cabal-install flag (or provided separately if it's too much clutter for cabal-install).

**Comment by hvr** [comment]
@seagreen `other-extensions` provides esential meta-information to the cabal solver it couldn't otherwise access, in fact the solver was finally hooked up in #2644 to use this information.

We've recently added the ability to Hackage to  edit `other-extensions` in existing releases to become more accurate. So what you're proposing is going into the exact opposite direction of what we're currently working towards! Personally I consider this de-feature request a wontfix

**Comment by 23Skidoo** [comment]
The ability to automatically derive this info is useful, however. Ideally, Hackage would prevent uploading packages with incorrect `other-extensions`. But I guess we can open a separate ticket for this.

**Comment by hvr** [comment]
@23Skidoo `cabal init` already derives that information automatically when it prefills your initial `.cabal` file, we may want something like the `gen-bounds` feature for `other-extensions`...

**Comment by 23Skidoo** [comment]
> `cabal init` already derives that information automatically 

I guess the main problem with integrating this with `cabal check` is CPP? Though we can make it a warning of course.

**Comment by hvr** [comment]
@23Skidoo fwiw, I'm working on something like `ghc --allowed-extensions=TemplateHaskellQuotes,BinaryLiterals,LambdaCase`, which would turn undeclared `other-extensions` into compile warnings...

**Comment by 23Skidoo** [comment]
That's cool!

**Comment by Blaisorblade** [comment]
> But I guess we can open a separate ticket for this.

Was this ticket opened? Where's a link? Reopening till that happens. Feel free to close again when the new ticket is created.

**Comment by 23Skidoo** [comment]
@Blaisorblade 
There's #1562.
