### ISSUE TITLE
No ability to use --allow-newer when configuring with Setup.hs

### ISSUE THREAD

**Issue by snoyberg** [haskell/cabal#3163]
A number of different systems (Nix, the Stackage curation tool, Stack) use `runghc Setup.hs configure` for configuring their packages. There are various reasons for this; since this bug report is about Stackage curation, the reason we have is to avoid having to manually match the Cabal library and cabal-install versions.

@bgamari asked me to run the latest GHC 8 release candidate through the Stackage gauntlet. Unfortunately, due to the lack of `--allow-newer`, it's quite difficult to do a proper test of GHC 8, which includes a new version of many core libraries. My ultimate workaround is quite ugly: [rewriting the .cabal file with all version bounds stripped out](https://github.com/fpco/stackage-curator/blob/69b15c2c7fb2d4dfba286b1348d8f8c72efa00ce/Stackage/PerformBuild.hs#L773).

For the record, all of this GHC release candidate testing is in the repo https://github.com/fpco/ghc-rc-stackage, which is just a Dockerfile, shell script, and some docs.

**Comment by 23Skidoo** [comment]
Can you use `runghc Setup.hs configure --exact-configuration`? The reason we don't do this in Cabal is because Cabal's built-in solver is fairly primitive. Perhaps once the solver is separated from `cabal-install` (see e.g. #2768), we can make Cabal depend on it and remove its built-in solver, then you'll be able to use all advanced solver features via the `runghc Setup.hs configure` interface.

/cc @dcoutts

**Comment by 23Skidoo** [comment]
Having looked at the code, I think I might be actually able to do something.

**Comment by 23Skidoo** [comment]
@snoyberg See #3165.

**Comment by hvr** [comment]
@23Skidoo I still oppose have Cabal depend on the solver library. See also discussion at https://github.com/haskell/cabal/pull/2768#issuecomment-155005966
