### ISSUE TITLE
[nix-local-build] Enable all components by default

### ISSUE THREAD

**Issue by ezyang** [haskell/cabal#3315]
I propose that we enable all components by default for `new-build` and similar commands. This is slightly inconsistent with the current behavior of `cabal configure` but it seems to make a good deal more sense. Since we don't bother building the test/benchmark/etc dependencies if we aren't building that component, all this means is that we dependency solve with a more expansive set of dependencies.

Even better is if we automatically disable components when we can't dependency solve in their presence. The solver should be able to do this fairly easily.

CC @dcoutts.

**Comment by dcoutts** [comment]
We already optimistically enable testsuites and benchmarks.

What we don't do by default is add testsuites and benchmarks to the set of components that are built if you ask to build the package as a whole, rather than specifying building those components in particular.

That is, this does not build the test suites by default

    cabal new-build ./

but we still solved for them, so without re-solving you can:

    cabal new-build mytestcomponent

You think we ought to build all the tests etc by default? I'm not so sure that's the default people want. But having an "all tests, all everything" target syntax rather than having to remember the name of test components would be good.

**Comment by ezyang** [comment]
Yeah this is bogus; I got confused by #3199.
