### ISSUE TITLE
[nix-local-build] Incorrectly monitoring non-existent pkgconfig file

### ISSUE THREAD

**Issue by ezyang** [haskell/cabal#3351]
On master, I noticed that new-build was repeatedly rerunning the solver. Running with `-v3` revealed:

```
ezyang@sabre:~/Dev/cabal-shake$ cabal new-build cabal -v3 --dry-run
File monitor 'improved-plan' changed: file /usr/local/lib/pkgconfig
File monitor 'elaborated-plan' changed: file /usr/local/lib/pkgconfig
```

which doesn't exist. So it appears somewhere, someone is monitoring a nonexistent file. In fact, I'm not sure why this is happening at all, because if we monitor a file we need to stat it in order to find out its timestamp at least, and read it for its contents; at which point the monitor code should realize that we are testing for non-existence. So maybe there's an API problem too.

**Comment by dcoutts** [comment]
There's no API problem this is behaving as expected. We're saying "please monitor this directory that I expect to exist" and then when we take a snapshot of the filesystem to compare against later, we find that it doesn't exist already, so it's changed already. So when we come to check for changes later then of course it's changed already.

So yes, the file monitor API is behaving as expected. The problem was we were expecting the directory to exist (when in fact we were expecting it to not exist). So the fix in PR #3352 is correct.
