### ISSUE TITLE
Inconsistent travis results with cabal-1.22 and ghc-7.10.3

### ISSUE THREAD

**Issue by mgsloan** [haskell/cabal#3420]
Sorry if this is just noise, but I have no idea what is happening here: https://github.com/commercialhaskell/stack/issues/2121

The strange thing is that this started occuring spontaneously, as far as I can tell not due to any changes to our travis config. Perhaps there are issues with older versions of cabal that cause corrupted packages / missing dbs?

**Comment by 23Skidoo** [comment]
So you got your Travis `.ghc`/`.cabal` borked somehow, which was fixed by clearing the Travis cache. But then the build started failing because `mtl` failed to install [with the following error](https://travis-ci.org/commercialhaskell/stack/jobs/129246293#L337):

```
Failed to install mtl-2.2.1
Build log ( /home/travis/.cabal/logs/mtl-2.2.1.log ):
Configuring mtl-2.2.1...
Building mtl-2.2.1...
Preprocessing library mtl-2.2.1...
/home/travis/.ghc/x86_64-linux-7.10.2/package.conf.d/package.cache: openBinaryFile: does not exist (No such file or directory)
```

I believe that the error comes from `ghc` or `ghc-pkg` since Cabal never reads stuff in `.ghc` directly. I'd try adding a call to `ghc-pkg recache` to your script before the `cabal install` invocation and see if it fixes the error.

**Comment by 23Skidoo** [comment]
One possibility is that there's a race condition in parallel install when one process updates `package.cache` and another tries to read from it. It may be possible to fix it in `ghc-pkg`: e.g., [this fragment](https://github.com/ghc/ghc/blob/master/utils/ghc-pkg/Main.hs#L1067) looks suspicious.

**Comment by 23Skidoo** [comment]
You can also try running `cabal install -v2` or `-v3` and looking at the logs.

**Comment by jneira** [comment]
those version are really old and this issue is somewhat obsolete
@mgsloan feel free to reopen if you continue experiencing the bug with newer versions
