### ISSUE TITLE
Use cabal.project with preinstalled dependencies?

### ISSUE THREAD

**Issue by bennofs** [haskell/cabal#3456]
I am in a situation where all the dependencies required for a project are already installed. Is there a way to still make use of a `cabal.project` file, without reinstalling all dependencies?

**Comment by dcoutts** [comment]
If you construct the same environment you'll get the same dependencies. That said, if we want some way to guarantee this, then the simplest thing would be to copy over a freeze file of some sort to ensure the environment is the same, so that the same deps will be reused.

So I think this depends on a new freeze (or similar) command.

**Comment by bennofs** [comment]
Oh, I meant that the dependencies are already installed system-wide, not using `cabal-install`. Will cabal still detect them as installed?

**Comment by dcoutts** [comment]
@bennofs if they're installed in the global package db then yes the solver will look at them.
