### ISSUE TITLE
Automatically reinstall packages when the pkg-config version changes

### ISSUE THREAD

**Issue by hamishmack** [haskell/cabal#3493]
While trying to work out what to do about https://github.com/haskell-gi/haskell-gi/issues/45, I was wondering if it would be possible for cabal to to track `pkgconfig-depends:` like a `flag` or like `build-depends:` so that if `pkg-config --modversion` has changed the package in the `.cabal/store` will no longer be a suitable match.

For example if:

* `A.cabal` in Hackage that includes `pkgconfig-depends: X -any`
* `B.cabal` locally that has `build-depens: A`:

We can run:

```
$ ls *.cabal
B.cabal
$ pkg-config --modversion X
1.0
$ cabal new-build
```

`A` will be installed.  If we then upgrade `X` and run:

```
$ pkg-config --modversion X
2.0
$ cabal new-build
```

A new `A` would be installed.

**Comment by dcoutts** [comment]
Right, two things we need to do:

* track the content of the `pkg-config` db. Currently we only monitor the `pkg-config` files for additions/removals not changes (though in practice it probably will detect changes since changes are usually done via the atomic rename method)
* include pkg-config version deps in the hash

**Comment by ezyang** [comment]
Well, it's not as simple as that: we also have to tell which `pkgconfig-depends` the package actually depends on, so we only hash the versions of those entries in pkg-config.

**Comment by ezyang** [comment]
Issue subsumed by PR #3787
