### ISSUE TITLE
Add flag to add contents of global db as preferences / constraints

### ISSUE THREAD

**Issue by phadej** [haskell/cabal#3522]
Use case: It would be cool to not reinstall `transformers` for ghc-7.10, even if it's possible. If nothing else, then to help testing packages with bundled dependencies.

**Comment by grayjay** [comment]
It looks like new-build currently prefers installed versions and ignores `--upgrade-dependencies`: https://github.com/haskell/cabal/blob/87bd885bfef2fc3c1f3200ce8a46613b1bb16149/cabal-install/Distribution/Client/ProjectPlanning.hs#L881

**Comment by ezyang** [comment]
@grayjay it's not obvious from the comment: is that a bug or a feature?

**Comment by phadej** [comment]
Looks like missing feature, not an accidental bug.

**Comment by ezyang** [comment]
It's possible what @phadej is seeing, rather, is that there is an installed version of transformers, but the solver decided that it wasn't possible to use that version (e.g., because the packages it is looking at have a higher lower bound on transformers). Then the solver will happily pick a newer version to solve the problem. So I'm not sure if this a request for transformers to "try harder" in this case, or for the solver to emit a warning when it can't use the pre-installed system package (and probably should say where the bad constraint came from!)

**Comment by phadej** [comment]
To be clear: I also want to be able to *constraint* on installed versions, not only *prefer* them. It feels that solver rather picks to install `transformers-0.5` than to use bundled `transformers` and `transformers-compat`...

**Comment by ezyang** [comment]
So it turns out that we already have a constraint form to do this: `constraints: transformers installed`. It will work for anything in the global package db. Give it a try.
