### ISSUE TITLE
CI doesn't ensure cabal install cabal-install from previous major series works

### ISSUE THREAD

**Issue by ezyang** [haskell/cabal#3544]
Self-explanatory. Probably should just make a separate job in the matrix for testing this case.

**Comment by phadej** [comment]
Do you have an example? AFAICS `cabal check` should say aloud if `cabal-version` is too low, also we have `setup-deps`...

**Comment by 23Skidoo** [comment]
To clarify: this means `cabal-install-1.24 install cabal-install-1.26`, not `cabal-install-1.26 install cabal-install-1.24`.

**Comment by 23Skidoo** [comment]
In general, we need a more systematic pre-release testing procedure.

**Comment by ezyang** [comment]
The way the Travis script works is by first bootstrapping `cabal-install` using `bootstrap.sh`, and then using the resulting `cabal` for the rest of the operations. So this won't check if cabal-install-1.24 install cabal-install-1.26 works, as @23Skidoo says. I noticed this when I was working on the internal libraries PR, because for cabal-install to use internal libraries requires a sufficiently new version of Cabal, but the CI wasn't failing.

**Comment by jneira** [comment]
Now github workflows does:
* `cabal-${lastReleaseVersion} v2-build cabal-head`
* uses the cabal-head to run all the tests suites
* `cabal-head v2-build cabal head` (only in windows for now but it will be extended soon, see https://github.com/haskell/cabal/issues/7742)

So the issue request was being done since time ago and we check cabal-head too (As travis did when this issue was opened)
