### ISSUE TITLE
Introduce Distribution.Compat.Prelude

### ISSUE THREAD

**Issue by phadej** [haskell/cabal#3608]
Motivation:
- `Applicative`, `Monoid`, `Traversable` CPP noise could be removed
- `GHC.Generics (Generic)`, `Data.Typeable (Typeable)`, `Control.Monad (unless, when, liftM)` etc often used import noise could be removed. 

There is already over hundred `.hs` files, so we could remove a lot of boilerplate.

Comments? ping @ezyang @dcoutts @23Skidoo

**Comment by 23Skidoo** [comment]
+1.

**Comment by ezyang** [comment]
OK.

**Comment by phadej** [comment]
I'll do this over flight.

**Comment by ezyang** [comment]
Thinking about this some more, here are some preferences I have:

1. Let's have the compat Prelude track the most recent version of GHC. So it's main job is to export extra things that Prelude doesn't normally export on older versions of GHC
2. This will do much of the same things that https://github.com/haskell-compat/base-compat#readme does, but I guess we can't depend on this package?
3. If we define `Prelude` ourselves (don't export it obviously), you can avoid the `NoImplicitPrelude` and `import Distribution.Compat.Prelude` boilerplate, because GHC will pick up a locally named `Prelude`. Don't have to but it's a thought.

**Comment by 23Skidoo** [comment]
Yes, Cabal can only depend on libs that come with GHC. So no `base-compat`.

**Comment by phadej** [comment]
@ezyang I made a fat-prelude, as there is quite a lot of repetition. How shadowing `Prelude` would work in bootstrap case?

**Comment by phadej** [comment]
... Except that parsec (mtl, text) doesn't come with any GHC yet... But that's an exception...

**Comment by ezyang** [comment]
Shadowing Prelude will work fine for bootstrap. It's just another module that GHC picks up, and then will start using for the rest of the modules.

**Comment by phadej** [comment]
I'll try

**Comment by ezyang** [comment]
I mean, if the boilerplate compat prelude import / NoImplicitPrelude is not a problem, then no reason to do something more magical.

**Comment by dcoutts** [comment]
Not a fan, but I'm prepared to be out-voted :-)

**Comment by phadej** [comment]
It's in now. @dcoutts you must to admit it's not only cons.

(it's easy to see where the `head` is used, e.g. Unfortunately we don't have `NonEmpty` to rip the most of them. Things like that aren't super important, but nice anyway)

**Comment by ezyang** [comment]
I do think that it is far better to centralize the CPP in one place. And since some of the CPP is Prelude related, you are inexorably lead to defining your own Prelude. It just makes sense ;)
