### ISSUE TITLE
cabal-install can break installed packages by rebuilding dependents

### ISSUE THREAD

**Issue by bos** [haskell/cabal#364]
(Imported from [Trac #371](http://hackage.haskell.org/trac/hackage/ticket/371), reported by @dcoutts on 2008-10-15)

Install plans sometime involve rebuilding a package. This is not a safe operation however. Rebuilding a package can and does change its ABI.

The ideal solution is to use a persistent package store like nix. That would mean we do not replace any installed package, just add new instances.

In the mean time however one solution would be to extend an install plan the re-installs a package such that it rebuilds all reverse dependencies too.

**Comment by BardurArantsson** [comment]
I believe this is now obsolete since cabal/ghc-pkg/whatever learned that multiple same-named package can coexist? Request close.

**Comment by kosmikus** [comment]
Well, same-named packages could co-exist forever. We still have unsafe destructive reinstalls under certain conditions as of now. Situation certainly has improved since this reports in that we now avoid this more often, and print warnings. Furthermore, people have been and are working on the Nix-style stuff. So it's ok with me to close this, even though "obsolete" is not the right term.
