### ISSUE TITLE
Better messages when constraint from user config makes us not pick a package

### ISSUE THREAD

**Issue by bos** [haskell/cabal#373]
@ezyang: See below, you can specify constraints to exclude packages, the real bug is error messages

---

(Imported from [Trac #380](http://hackage.haskell.org/trac/hackage/ticket/380), reported by guest on 2008-10-23)

Sometimes there are packages on hackage that I don't want to install, perhaps ever.  Maybe there is a buggy release I'm trying to avoid, or something of that nature.

So, my proposal is a user defined blacklist.  I think the version specification could work just like that of a .cabal file.

I also think cabal should tell you when it skips a dependency due to blacklisting.

**Comment by ulysses4ever** [comment]
I think this issue is too vague, and I'd vote for closing it as such. On top of that, constraint solving is a rather complicated process, results of which will always be hard to explain. I'd welcome more focused issues (e.g. #7993) than this one.

**Comment by Mikolaj** [comment]
I think "Make it easier to work with several config files" and "Allow a single config file line to contain a list of constraints" is in a way fixed in #7783. What probably remains unsolved is "Distinguish config file constraints from command-line constraints in error messages". However, given that nobody implemented nor discussed that here in 10 years, if anybody is still interested, please search for newer similar tickets and perhaps open a new ticket with precisely this content, ideally giving a new use case, taking #7783 into consideration and sketching how the errors should look like. Closing this one as stale. Thank you everybody.
