### ISSUE TITLE
Allow "sandbox without project file" functionality in new Cabal.

### ISSUE THREAD

**Issue by danidiaz** [haskell/cabal#3730]
For quick and dirty exploratory programming —usually when testing new versions of packages— I sometimes create a cabal sandbox in a folder, and then install the desired packages, _without bothering to create a cabal file_. I then use `cabal exec` to gain access to the packages.

```
cabal sandbox init
cabal install transformers-0.5.2.0
...
cabal exec -- ghci
```

It would be nice if the new Cabal supported something similar to this. Of course, a possible workaround is to create a dummy project.

**Comment by ezyang** [comment]
Thank you for the report. Do you *just* want GHCi, or do you need the full generality of exec?

If you do `cabal new-repl` at the top-level of a project (#3659), today, something very goofy happens. Maybe this is what *should* happen in that case. It might have to be annoyingly special-cased, however, since the current new-repl relies on a `Setup` script for knowing how to repl a Cabal project. Maybe we can just add a new codepath for it.

CC @dcoutts

**Comment by danidiaz** [comment]
> Do you just want GHCi, or do you need the full generality of exec?

The great majority of times I have used it for GHCi. 

I did have an old use case in which I used `cabal exec` in combination with `--sandbox-config-file` to fix a package environment for a number of scripts that were run with `runhaskell' or compiled with `ghc`. [Here](https://github.com/danidiaz/hs-scripts) is the repo. I later added a cabal file though.

**Comment by danidiaz** [comment]
I wouldn't mind having to write something like a cabal.config file with the required modules (or even a minimal `Setup` file) I just would like to avoid having to name a project and specify other project-related stuff at from the outset, while I'm just tinkering.

**Comment by dcoutts** [comment]
I think the .ghc.environment stuff that I'm adding will cover this use case, since you'll be able to just run ghci anywhere in the project and get an environment that includes all the deps of the things in the project. And once we get the "extra-packages" thing in the project file working too then that should cover it.

We could also make cabal repl when not in any package dir do the equivalent.

**Comment by phadej** [comment]
Currently one can `cabal new-repl -b transformers --constraint=transformers==0.5.2.0` outside the project.

`-b` could accept package-identifiers to make new-repling with a specific package version more convinient, but that would be separate issue.
