### ISSUE TITLE
Check that new-build works with ghc-mod/haskell-mode

### ISSUE THREAD

**Issue by ezyang** [haskell/cabal#3731]
Assuming that you modify these to invoke `cabal new-build` rather than `cabal build`, do they work? Would be good to test.

CC @maxigit

**Comment by 23Skidoo** [comment]
Would be also nice to patch `intero` to make it support `cabal new-build` instead of just `stack`.

**Comment by dcoutts** [comment]
I discussed integration with ghc-mod and leksah with their authors at MuniHac. They're planning to file a ticket discussing what info and interface they'd like to get extra info out of `cabal new-build`, e.g. extensions to the `plan.json` or new hidden `ide` command to get things like the ghc environment / flags etc.

Note that leksah now uses cabal new-build as their default build system so we can ask them for testing & feedback.

**Comment by maxigit** [comment]
Would it not be possible (and probably simpler) to have, either a hacked
version of cabal or a way to configure (per directory) cabal to translate
all basic command (build, install) to their corresponding new version ?

**Comment by ezyang** [comment]
maxigit: Yes, it would be very simple. Or even an environment variable to change the sense of the flags. Actually a fix like that should probably go in 2.0. @maxigit do you think you could take a swing at this?

**Comment by maxigit** [comment]
I'm thinking of a file instead of environment variable because it's allows to be set by project within the same environment. For example, I use Spacemacs, which is run globally and  I switch for one project or another (by switching buffer). I can try to have a go, but I am really busy. I am considering writing a generic wrapper to do a similiar thing but for any executable, as well as changing the executable itself. This will solve the ghc-mod problem, when you need to change the version according to the version of GHC.
It should also allow to swap between cabal and stack transparently. However, I don't really have time for any of this. I can have a try if you let me know which file to look and where would be the best place to add this flag : cabal.config. cabal.project, anything else ?

**Comment by ezyang** [comment]
A generic wrapper sounds like it would be easier for you to do, and would help you do other stuff. We could then mention it in the documentation as a way to interact with new-build.

**Comment by maxigit** [comment]
I've done a generic wrapper, called [Crew](https://github.com/maxigit/crew). It's not battle tested but seems to work for my use case (which is use "cabal build" key binding in spacemacs. Comments are welcome.

**Comment by ezyang** [comment]
Thanks @maxigit!
