### ISSUE TITLE
Miscellaneous Documentation Improvements

### ISSUE THREAD

**Issue by linearray** [haskell/cabal#3791]
This issue is to collect a few todos regarding the new documentation:
- [ ] The GHC documentation defines `object types` for documenting recurring elements, such as command line flags. We should explore which object types or other Sphinx features (directives, roles…) would make sense for Cabal.
- [ ] The sphinx search is still sub-par, case in point: "build-depends". It appears that code blocks are not indexed. Perhaps we need a custom Sphinx search adapter for that.
- [ ] The meta-docs (README.md in Cabal/doc) should include steps for Ubuntu/Debian users.
- [ ] There are a few instances where the converted documentation includes formatting in inline literals, an obvious contradiction. Need to find a way to work around that.
- [ ] A few paragraphs have "Strikeout" prepended to them. Find out what to do with that.
- [ ] All pages that consist solely of a TOC, should indicate that in the filename (e.g. `toc-config-and-install.rst`)
- [ ] Lastly, once all or most of the other improvements are complete, it would not hurt to actually read through all the documentation, to spot rendering bugs and because at least some of the information appears to be outdated.

**Comment by hvr** [comment]
The indexing issue for `build-depends` would be somewhat handled by addressing the first issue, c.f.

```py
    app.add_object_type('ghc-flag', 'ghc-flag',
                        objname='GHC command-line option',
                        parse_node=parse_flag,
                        indextemplate='pair: %s; GHC option',
                        doc_field_types=[
                            Field('since', label='Introduced in GHC version', names=['since']),
                            Field('default', label='Default value', names=['default']),
                            Field('static')
                        ])
```

which implies an index-entry template; we want something like that in the context of Cabal at least for `stanza` and `field` and `flag`. 

/cc @ezyang

**Comment by ezyang** [comment]
@linearray, would you like to drive this effort? If so I'll milestone this for 2.0 :)

**Comment by sopvop** [comment]
Simple `app,add_object_type(...)` is not enough for package fields because of duplicates. For example both test and executable section have `main-is` field.
One workaround is to add `pkg-exec-field`, `pkg-test-field` etc. but that leads to a lot of different directives with different ref roles. sad.
The `.. option::` directive works around this by examining state written by `.. program::` directive, similar trick can be used here too, but that requires some code.

About adding more meta-data to .. option:: directive now used to describe setup interface -
the ObjectDescription directive in sphinx does not require adding fields explicitly for simple stuff, you can actually do

~~~.rst
.. option:: --allow-newer

    :Since: 1.22

    Blah blah
~~~

It will render :Since: or any other field as written between colons, and with with add_object_type (or subclassing ObjectDescription directive) you can label it.

Adding a custom domain while copy-pasting and simplifying some stuff from sphinx should not be hard though, but would add some maintenance burden.
I've done some more docs beautification [here](https://sopvop.github.io/cabal/developing-packages.html#package-properties) but have encountered that duplicate id thing and stopped for now.

**Comment by andreasabel** [comment]
I am afraid this discussion of the state of affairs of the documentation is likely outdated after 5+ years.
