### ISSUE TITLE
Confusing output

### ISSUE THREAD

**Issue by phadej** [haskell/cabal#3808]
Currently:
````
Building profunctors-5.2 lib...
Building semigroupoids-5.1...
```

Shouldn't it be
```
Building profunctors-5.2 lib...
Building semigroupoids-5.1 lib...
```
always?

**Comment by ezyang** [comment]
So, the deal is that semigroupoids uses a Custom setup script, for which we don't support per-component build. Thus, when we build semigroupoids, we *truly are* building everything in it (but since it has no executables, in practice it's just a lib.)

So I guess we could special-case the output so that if the package being built only has a library, we output "lib" even if we didn't /actually/ ask for just the lib to be output. Or we could say something like "(uses Custom, so building all components)"? What ever you want @phadej!

**Comment by 23Skidoo** [comment]
> Or we could say something like "(uses Custom, so building all components)"? 
+1 for this.
