### ISSUE TITLE
Solver fails to honour `other-extensions` in collateral components

### ISSUE THREAD

**Issue by hvr** [haskell/cabal#3847]
I ran into an issue today, where a dependency on `vector` caused a build failure due to `vector`s testsuite requiring `TemplateHaskell` (i.e. it was caught too late during building):

```
Configuring component lib from vector-0.10.12.3
cabal: The package vector-0.10.12.3 requires the following language extensions
which are not supported by ghc-8.0.1: TemplateHaskell
cabal: Failed to build vector-0.10.12.3 (which is required by footools).
The failure occurred during the configure step.
```

Here's a reduced testcase which exhibits the same problem:

```
-- ./cabal.project
packages: foo
packages: bar

package bar
  tests: false
```

```
-- ./foo/foo.cabal
name:                foo
version:             0.1.0.0
build-type:          Simple
cabal-version:       >=1.10

library
  build-depends:       base, bar
  default-language:    Haskell2010
```

```
-- ./bar/bar.cabal
name:                bar
version:             0.1.0.0
build-type:          Simple
cabal-version:       >=1.10

library
  build-depends:       base
  default-language:    Haskell2010

test-suite bar-test
  Default-Language: Haskell2010
  type: exitcode-stdio-1.0
  Main-Is: Main.hs
  other-extensions: SillyWalks
  -- note, the following contradiction has no effect (as expected), even if the `other-extensions` above were commented out
  build-depends: base<0
```

which results in

```
$ cabal new-build
Resolving dependencies...
In order, the following will be built (use -v for more details):
 - bar-0.1.0.0 (lib) (first run)
 - foo-0.1.0.0 (lib) (first run)
Configuring component lib from bar-0.1.0.0
Warning: Unknown extensions: SillyWalks
cabal: The package bar-0.1.0.0 requires the following language extensions
which are not supported by ghc-8.0.1: SillyWalks
cabal: Failed to build bar-0.1.0.0 (which is required by foo). The failure
occurred during the configure step.
```

I would have expected either a solver failure, or better yet, no failure at all, since we only need the lib component.

This is quite a problem, since it means that GHCs w/o TH support run into build failures such as `vector` even though TH support is not even needed to use `vector`.

/cc @ezyang

**Comment by ezyang** [comment]
Here's how it's supposed to work in GHC 8.0

1. Prior to dep-solving, we run `ghc --supported-languages` to get a list of supported language extensions.
2. With this list of available extensions, we run the dep solver. The dep solver should pick versions, flags and stanzas to enable such that unsupported extensions are not in the plan.
3. Profit

I have a few guesses where the problem might stem from. Someone will have to debug properly.

* It may be that the supported extensions are not properly propagated to the solver.
* It may be that the solver isn't actually enforcing language extension support when solving. You can test this and (1) by putting `other-extensions: SillyWalks` in `library`
* It may be that the solver disable tests, but ProjectPlanning turns them on again (due to the sticky test suites hack) and doesn't realize that it can't turn them on due to missing extensions)

**Comment by ezyang** [comment]
Upon further discussion with @hvr, the bug is that per-component builds should not check other-extensions for stanzas that are not enabled. Currently it does, by accident. There probably isn't any problem with new-build (according to the logs we're not trying to build tests.) Make sure this bug doesn't ship with GHC 8.2, that would be embarrassing.
