### ISSUE TITLE
HEAD: Strange warning about "unknown package" (related to build-tools?)

### ISSUE THREAD

**Issue by edsko** [haskell/cabal#3875]
With cabal-install HEAD (@hvr's 1.25+git20160918.1.c9e046e~xenial) I get this warning when I call configure:

```
# cabal configure
Resolving dependencies...
Warning: solver failed to find a solution:
Could not resolve dependencies:
trying: ingest-0.1.0.0 (user goal)
unknown package: ingest-alex-exe.alex (dependency of ingest-0.1.0.0)
fail (backjumping, conflict set: ingest, ingest-alex-exe.alex)
Dependency tree exhaustively searched.
Trying configure anyway.
Configuring ingest-0.1.0.0...
```

This `ingest-alex-exe.alex` dependency is really odd; I have no idea where that is coming from. The only mention of alex in my `.cabal` file is

```
  build-tools:         alex >= 3.1 && < 3.2
```

(and there are some `.x` files in the project).

**Comment by hvr** [comment]
I assume `cabal info alex` is able to find alex?

**Comment by ezyang** [comment]
`ingest-alex-exe.alex` is a qualified executable path, referring to the `alex` build-tools dependency from `ingest`. "unknown package" is the message we get when we can't find the package at all in the index or locally. Is it possible you haven't run `cabal update`? If so we have a regression for detecting when there is not an usable index. If you give us `-v3` output that will also help diagnose.

**Comment by ezyang** [comment]
Reproduced. This error does NOT happen when we dep-solve for new-build.

**Comment by ezyang** [comment]
OK, the bug seems to be in `cabal configure`'s invocation of the solver in `Distribution/Client/Configure.hs`:

```
        $ standardInstallPolicy
            installedPkgIndex
            (SourcePackageDb mempty packagePrefs)
            [SpecificSourcePackage localPkg]
```

We can see that the solver is given an EMPTY source package database. This is because we assume that everything you need from `cabal configure` is taken from the installed package index.

But this is NOT true for executables, which never have an entry in the installed package index. So I guess what we should do is not solve for executables in the legacy codepath, since there isn't anything useful we can do with the info anyway. I guess another solver parameter?

Obviously obsoleted by nix-local-build.
