### ISSUE TITLE
Save old cabal.project.local when new-configure overwrites it

### ISSUE THREAD

**Issue by ezyang** [haskell/cabal#3943]
Something that I think is a little distressing about new-configure is that it blows away the old `cabal.project.local`, even if you've tweaked it by hand and it has some sort of substantial changes. To prevent accidents like this from happening, I think we should save the old local file if we overwrite it. There are two ways to do this: (1) just move it to some backup file e.g. `cabal.project.local-old`, or (2) print out the file contents when we override it.

**Comment by pranitbauva1997** [comment]
@ezyang I am trying to contribute to this repo thus I would like to start with this issue.

I would prefer the second one because it gives the other person more capabilities as to what he wants to do with the old file's contents before the rewrite.

I think I would have to make the edits in `cabal-install/Distribution/Client/ProjectConfig.hs` file. In that specifically in the method `writeProjectLocalExtraConfig`, right?

What do you think?

**Comment by ezyang** [comment]
(2) seems OK to me.

I feel weird modifying `writeProjectLocalExtraConfig` to print out the old contents, it doesn't match the function name and it doesn't really match up with everything else. In any case, it only has one call site at configureAction in CmdConfigure.hs. I'd suggest making the change there instead.
