### ISSUE TITLE
new-build doesn't build tests even when given --enable-tests

### ISSUE THREAD

**Issue by 23Skidoo** [haskell/cabal#3996]
This is with current master. When I try to compile `bloodhound`'s test suite with `new-build --enable-tests` it compiles all dependencies correctly, but ignores the actual test suite. Subsequent attempts to run `cabal new-build` have no effect, `new-build tests` doesn't work either. Maybe has something to do with `bloodhound` using `build-type: Custom`.

**Comment by 23Skidoo** [comment]
Example log:
```
$ cabal new-build -w ghc-7.10.3 --enable-tests
Resolving dependencies...
In order, the following will be built (use -v for more details):
 - QuickCheck-2.9.2 (lib) (requires build)
 - quickcheck-io-0.1.3 (lib) (requires build)
 - doctest-prop-0.2.0.1 (lib) (requires build)
 - hspec-core-2.2.4 (lib) (requires build)
Configuring QuickCheck-2.9.2 (lib)...
Building QuickCheck-2.9.2 (lib)...
Configuring doctest-prop-0.2.0.1 (lib)...
Configuring quickcheck-io-0.1.3 (lib)...
Building doctest-prop-0.2.0.1 (lib)...
Building quickcheck-io-0.1.3 (lib)...
Configuring hspec-core-2.2.4 (lib)...
Building hspec-core-2.2.4 (lib)...
$ cabal new-build -w ghc-7.10.3 --enable-tests    
Up to date
$ cabal new-build -w ghc-7.10.3 --enable-tests tests
Up to date
$ cabal new-build -w ghc-7.10.3 tests               
Resolving dependencies...
Up to date
```

The `-v3` log is [here](https://gist.github.com/23Skidoo/f2a25cc48521b3f7c053bce9a960a1af).

**Comment by dcoutts** [comment]
I think I've seen the same behaviour in a couple other packages. The behaviour appears to be that there's some problematic package and then one pass or other (probably the pruning of the plan to the targets) prunes everything that depends on that problematic package. This may be due to a dep closure failure being treated incorrectly (returning [] rather than failing), or something similar.

The same problem can be observed in the binary-serialise-cbor package, with one of the test suites that depends on the `store` package.

So I suggest tracing the planning code that does the pruning to targets, and perhaps adding some sanity check before pruning to check we don't have any dangling deps or other weirdness.

**Comment by ezyang** [comment]
> This may be due to a dep closure failure being treated incorrectly

Yeah, uh, we should not do that ;)

**Comment by dcoutts** [comment]
So I think I have a diagnosis. At least it's a diagnosis for a similar problem that I can reproduce. It's incorrect construction of the elaborated plan in the first place (cycles).
