### ISSUE TITLE
Add foreign-library to LD_LIBRARY_PATH during cabal exec

### ISSUE THREAD

**Issue by abooij** [haskell/cabal#4049]
Thanks for the work on the new `foreign-library` section. I have started using it for one of my projects, and it seems to work!

My use case is to reimplement a C library's ABI, and run existing binaries written in C against the Haskell version. At development time, this means building my haskell code as a foreign library, adding the relevant directory to `LD_LIBRARY_PATH`, and then running the existing binaries.

It would be convenient if cabal could add the haskell foreign library to `LD_LIBRARY_PATH`. I suppose the `cabal exec` command could be the right place to do this. So instead of

```
$ cabal build
$ LD_LIBRARY_PATH=dist/build/myproject/ /usr/bin/existing-binary
```

one would instead simply:

```
$ cabal exec /usr/bin/existing-binary
```

**Comment by ezyang** [comment]
The motivation seems reasonable. The big question, however, is WHICH paths should get added to LD_LIBRARY_PATH? After all, a foreign library could itself depend on (1) dynamic Haskell libraries that were installed user-wide, or (2) a different foreign library. All of these paths need to be added to LD_LIBRARY_PATH for things to "work" (although I guess we do bake in RPATHs to make sure that things can be found without LD_LIBRARY_PATH).

`cabal run`, as opposed to `cabal exec`, DOES twiddle the `LD_LIBRARY_PATH`, but because it's associated with an actual Haskell package, we know exactly what things need to be added. In your suggested `cabal exec`, this is not known; is the suggestion then that every foreign library of the package be added? (What if you're in a sandbox?) That actually makes a good bit of sense, as `cabal exec` is supposed to add the local sandbox bin directory to your PATH, so similarly, it should add the local sandbox lib directory (doesn't exist yet) to your LD_LIBRARY_PATH. Though, this doesn't help much in the non-sandbox case where PATH doesn't get twiddled (maybe it should: add to the PATH the directory of each executable build product; similarly, add to LD_LIBRARY_PATH the directory of each library build product).

@abooij does this make sense? Would you be interested in implementing this?

**Comment by abooij** [comment]
@ezyang That does make sense. And you are able to make more precise what I was somewhat worried about when I proposed this -- thanks for that.

We discussed this a bit on IRC and I can try to work on this.

**Comment by ezyang** [comment]
OK, I added you to the Cabal project and assigned you this ticket.

**Comment by ezyang** [comment]
@abooij Would you like an architectural overview on this ticket?
