### ISSUE TITLE
bootstrap.sh fully recompiles Setup.hs and Cabal after failure.

### ISSUE THREAD

**Issue by 2bdkid** [haskell/cabal#4194]
I'm trying to bootstrap cabal-install-1.24.0.2 on my Raspberry Pi 2 (Ubuntu MATE) using the bootstrap.sh script. It starts by building Setup.hs in Cabal-1.24.2.0, then compiling the package which ultimately fails due to not enough memory. This is all fine because it will continue after a reboot, but the script rebuilds Setup.hs (wasting about 45min) and tries to completely rebuild Cabal, which leads to another memory shortage.

So the 2 issues:
1. Even though the script builds Setup.hs, there is no Setup executable in the build directory, thus forcing another rebuild.
2. The script does not continue a partial build (at least with Cabal), but does a full recompile

**Comment by ezyang** [comment]
Hi @2bdkid! `bootstrap.sh` was never designed with running OOM midway through the compilation in mind, so it is not too surprising it is not working correctly here.

However, reading the code I think I can guess what the problem is: if you're running bootstrap.sh on a unpacked cabal-install tarball, the code will go and fetch and unpack the Cabal source code whenever we didn't manage to install it. In your case, it didn't install, and we reunpack, which blows away the old directory (see `unpack_pkg`).

I think for the particular case of Cabal, there is an easy way to work around this. Instead of building off of the tarball, get a Git checkout, change to the 1.24.0.2 release tag, and then run bootstrap.sh from the cabal-install. When bootstrap.sh detects a Git repo, it will try to build in place and I think this will avoid the rm -rf. But if you OOM on other packages this won't be sufficient. Probably best to fix unpack_pkg for resuming.

**Comment by 2bdkid** [comment]
Looks like that would work. I ended up installing Cabal by hand, then ran bootstrap.sh. It also ran OOM on cabal-install so I also installed it by hand.

**Comment by 23Skidoo** [comment]
OK, I guess this can be closed, since there's a workaround. Patches improving the UX in this case are welcome, though.
