### ISSUE TITLE
Add flag to cabal to specify requiredInstall packages in modular solver.

### ISSUE THREAD

**Issue by robinp** [haskell/cabal#4209]
In the modular solver at https://github.com/haskell/cabal/blob/2146ea148fc52ee97549b89c1e9bb18c90610670/cabal-install/Distribution/Solver/Modular/Solver.hs#L134, the list of wired-in packages is hardcoded.

When one wants to rebuild one of these packages (see [mail thread about rebuilding `base`](https://mail.haskell.org/pipermail/haskell-cafe/2017-January/125904.html)), the given package needs to be commented out, and cabal rebuilt locally.

It would be nice if the list of packages came from a flag (defaulting to the current set?), which users could override. Or, if it's needed for some reason, keep the list hardcoded but let some packages be removed with a flag.

**Comment by grayjay** [comment]
@robinp I rebased my branch from #3987 and made a PR.  The flag always ignores the whole list of non-installable libraries, because cabal already has "installed" constraints.  For example, `cabal new-build --constraint="base installed" --install-base-libraries` would allow cabal to install template-haskell but not base.

**Comment by grayjay** [comment]
Fixed by #4227.
