### ISSUE TITLE
build-tools breaks builds with old cabals

### ISSUE THREAD

**Issue by phadej** [haskell/cabal#4238]
E.g. travis job: https://travis-ci.org/haskell-servant/servant/jobs/192268593

The `markdown-unlit` is specified also as a `build-depends` so it's in the $PATH

Is it by design that `build-tool-depends` implies `build-tools`?

**Comment by ezyang** [comment]
CC @Ericson2314 

In the future, please paste the erroring Cabal file; when I clicked the link from the PR it looks like you already removed the `build-tools` entry from the PR, because there is no `build-tools` field to induce the error in the build log.

It is indeed by design that you should ONLY place an executable in either `build-tool-depends`  or `build-tools`, but not both. This is because of the behavior you observed here: executables in build-tools with old versions of Cabal must be registered to the ProgramDb, otherwise Cabal will keel over and die. (Newer versions of Cabal handle this gracefully if the program is in the PATH.) So if you're an old version of Cabal it's better to just ignore the field entirely, and hope that the end user put it in the PATH.

Also, it's worth noting that adding something to `build-depends` will NOT cause its executable to be added to the path in new-build. Some packages do this incorrectly, but we would like build-depends to ONLY trigger library dependencies to be built. Those packages should use build-tool-depends instead.

**Comment by phadej** [comment]
`build-tools` is removed in versions spec `3.0`. So I think this is kind of solved.
