### ISSUE TITLE
clarifying semantics of pkg-config field in .cabal files

### ISSUE THREAD

**Issue by cartazio** [haskell/cabal#4242]
@dcoutts @ezyang @hvr   et al,
what are the desired semantics for the 
`pkgconfig: libtls >= bound ... `
stanzas in foo.cabal  package descriptions.

it looks like i, the end user for a package, need to do an 
`export  PKG_CONFIG_PATH=/usr/local/opt/libressl/lib/pkgconfig`
stanza in my terminal to get things to work out ok. Is there any way to hint to pkg-config what paths to look at per platform or must it always be totally user setup? (the current error messages look quite confusing when the stars aren't aligned)

an example might be https://github.com/JustinTulloss/zeromq.node/issues/283#issuecomment-51431863 for another ecosystem. likewise https://groups.google.com/forum/#!topic/haskell-stack/E6zGmRnT3Ls

or perhaps i'm just not understanding what i should be doing :)

**Comment by hvr** [comment]
IMO, `pkg-config` is a system-tool and your environment is responsible to set its configuration up in a way that calling `pkg-config --list-all` shows everything registered w/ pkg-config. The point of `pkg-config` is so that you don't have to know where stuff is installed, cause `pkg-config` keeps that information for you. If you need a specific `PKG_CONFIG_PATH` then either your system installation of `pkg-config` is broken or you have manually installed & setup `pkg-config` and you need to take care yourself in e.g. your `~/.profile` to set the `PKG_CONFIG_PATH` env-var.

**Comment by cartazio** [comment]
This is a valid opinion.  It's just not documented so I had to ask

**Comment by cartazio** [comment]
Also it's hard to find good docs on pkg config or I've been looking in the
wrong places
