### ISSUE TITLE
Both binary and Cabal implements instance Binary Version

### ISSUE THREAD

**Issue by kolmodin** [haskell/cabal#4331]
`binary` is [failing on travis](https://travis-ci.org/kolmodin/binary) due to both `binary` and `Cabal` implementing `instance Binary Version`.
https://travis-ci.org/kolmodin/binary/jobs/202005906

`binary` since version `0.8.0.0`. https://github.com/kolmodin/binary/blob/master/src/Data/Binary/Class.hs#L725

`Cabal-1.24.2.0` has a guard for earlier versions than `0.8.0.0`.
https://hackage.haskell.org/package/Cabal-1.24.2.0/docs/src/Distribution-Version.html

Yet somehow `binary`'s travis fails, but only for GHC 7.8.4. Any clues?

Side note;
`Cabal` head implements its own `Version`, unknown to `binary` (good).

**Comment by kolmodin** [comment]
@hvr Maybe you have some idea?

**Comment by ezyang** [comment]
Are you sure Travis isn't picking up an old version of Cabal which didn't have the guard?

**Comment by kolmodin** [comment]
I can increase the verbosity in the logs and let it run again.

Without verbosity;
```
$ cabal install "bytestring >= 0.10.4" 'Cabal == 1.24.*' -j
Resolving dependencies...
Notice: installing into a sandbox located at
/home/travis/build/kolmodin/binary/.cabal-sandbox
Downloading binary-0.8.4.1...
Configuring binary-0.8.4.1...
Building binary-0.8.4.1...
Installed binary-0.8.4.1
...
Downloading Cabal-1.24.2.0...
Configuring Cabal-1.24.2.0...
Failed to install Cabal-1.24.2.0
Last 10 lines of the build log ( /home/travis/build/kolmodin/binary/.cabal-sandbox/logs/Cabal-1.24.2.0.log ):
cabal: Error: some packages failed to install:
Cabal-1.24.2.0 failed during the configure step. The exception was:
user error (
/tmp/Cabal-1.24.2.0-1409/Cabal-1.24.2.0/Distribution/Version.hs:144:10:
Duplicate instance declarations:
instance Binary Version
-- Defined at
/tmp/Cabal-1.24.2.0-1409/Cabal-1.24.2.0/Distribution/Version.hs:144:10
instance [safe] Binary Version
-- Defined in ‘binary-0.8.4.1:Data.Binary.Class’
)
```

**Comment by kolmodin** [comment]
I ran it with -j1 and then it passed... Something is fishy.

**Comment by ezyang** [comment]
@kolmodin I have a wild guess what's happening. First off, remember that you are building with GHC 7.8, which shipped with Cabal 1.18. Among other things, this version of Cabal did not support the `--dependency` flag which let us pick exactly which dependency we were to use. cabal-install will try its best to convince the setup script to build with the correct version of the dependency by specifying the version using `--constraint`, but if there are two versions of the same package in the store it might pick the wrong one.

My guess as to what's happening is that in parallel mode, a package gets installed to the store earlier than before, and maybe the Cabal package starts picking that one up instead of the other one. We could verify this guess by dumping the state of the package database before and after, and seeing if there are duplicate copies of a package with the same package.

**Comment by kolmodin** [comment]
The version of `cabal-install` to be used is selected in the travis script, not necessarily the one that shipped with GHC.
I'll bump to more modern `cabal-install` and see if that fixes it.

**Comment by kolmodin** [comment]
The problem went away when `cabal-install-1.22` was used. At least for one run. The problem was easily reproducible before, so I assume it's fixed now.
