### ISSUE TITLE
'ghc-options: -O0' is not needed

### ISSUE THREAD

**Issue by lspitzner** [haskell/cabal#4540]
Could the above warning please be removed in the case that the flag already is behind a manual, non-default flag?

(Also, shouldn't _flags_ be the thing that let the user control how a package is built locally? Then a flag should be able to imply --disable-optimization, but that does not seem to be an option..)

**Comment by hvr** [comment]
What's the use-case btw? I'm asking because we are slowly moving away from cluttering `.cabal` files with project-specific configurations, especially manual flags whose whole purpose is to guard `ghc-options` such as  `-Werror` or `-O0`: We now have `cabal.project` files which allow you to inject profiling/optimisation options and more generally `ghc-options` into specific packages.

**Comment by lspitzner** [comment]
ok, i have to consider a cabal.project-based setup.
