### ISSUE TITLE
./bootstrap.sh does not properly detect the presence of `ghc`

### ISSUE THREAD

**Issue by ghost** [haskell/cabal#4645]
GHC was installed from the binary release tar file into `~/.local`. This location is in `$PATH` and `ghc` will invoke the compiler from an interactive shell.

The installation of all bootstrap packages fails with the following:
```
Setup: Cannot find the program 'ghc'. User-specified 'ghc' does not refer
to an executable and the program is not on the system path.
```

I have tried to supply the location of GHC via `GHC=ghc ./bootstrap.sh` but the behavior does not change. Some packages seem to complete successfully. Rerunning bootstrap.sh displays more failures than the first runthrough, and some packages may install properly.

My apologies if this is the wrong place to report this.

**Comment by ezyang** [comment]
Could you post the logs emitted by `bootstrap.sh` by any chance? also, what happens if you specify a full path via `GHC=$HOME/.local/bin/ghc ./bootstrap.sh`?

**Comment by tuncer** [comment]
@R030t1, ping?

**Comment by R030t1** [comment]
Thank you for the ping, @tuncer.

```shell
git clone https://github.com/haskell/cabal
cd cabal/cabal-install
GHC=$HOME/.local/bin/ghc GHC_PKG=$HOME/.local/bin/ghc-pkg ./bootstrap.sh &> output.log
```

Please keep in mind before running `./bootstrap.sh` I must edit it so that the shebang line uses `bash`, not `sh`. I likely should not have closed my other bug but I do not know precisely what the fix is. It seems like autodetection of tools does not work.

In [this log](https://github.com/haskell/cabal/files/1289432/output.txt) the main missing package seems to be haddock. This after I fixed `./bootstrap.sh`'s inability to find `ghc-pkg`. How do I install haddock if I do not have a working Cabal?

**Comment by 23Skidoo** [comment]
@R030t1 Try running `bootstrap.sh` with `--no-doc`, looks like you don't have haddock installed.

**Comment by R030t1** [comment]
Thank you @23Skidoo. I should have looked more closely at the documentation. The command is now:

```shell
GHC=$HOME/.local/bin/ghc GHC_PKG=$HOME/.local/bin/ghc-pkg ./bootstrap.sh --no-doc &> output.log
```

Which produces [this output](https://github.com/haskell/cabal/files/1289464/output.txt). I have tried to give this as close of a look as I can but I do not understand why the base package is missing, which seems to trigger the other errors.

**Comment by jneira** [comment]
bootstrap.sh does not exist anymore, so i am gonna close it optimistically, betting the newbootstrap.py does not suffer the issue 😄
feel free to reopen the issue ifthat is not the case
