### ISSUE TITLE
A strange failure related to CPP (apprently)

### ISSUE THREAD

**Issue by mrkkrp** [haskell/cabal#4647]
Please take a look at:

https://github.com/mrkkrp/path-io/issues/29

I'm testing with GHC 8.2.1 on CI:

https://travis-ci.org/mrkkrp/path-io/jobs/252829902

So it looks like Cabal 2.0 behaves differently with nested CPP blocks (between `#if` and `#endif`) which causes a failure in this particular case.

Any comment?

**Comment by hvr** [comment]
@mrkkrp without having looked into this in more detail, this looks like `path-io.cabal` failed to specify all depedencies for the testsuite component. You're right that Cabal-2.0 behaves differently here, as previous Cabal versions behaved incorrectly, insofar as they broke the invariant that `MIN_VERSION_foo` shall only be defined if `foo`'s modules are actually in scope for a given component. This was fixed in Cabal-2.0. Does this explain the CPP failures you saw?

**Comment by mrkkrp** [comment]
Yep, I think I have already fixed that.
