### ISSUE TITLE
cabal new-run foo should default to exe:foo (same for test and bench)

### ISSUE THREAD

**Issue by nomeata** [haskell/cabal#4676]
If I have a project `foo.cabal` that defines both a library and an executable named `foo`, which is a common situation, then currently
```
$ cabal new-run foo -- some args
```
complains that it does not know whether I want to run `foo` the library or foo the executable, and makes me write
```
$ cabal new-run exe:foo -- some args
```
I see how this behavior makes sense for `cabal new-build` etc, but I do not even know what it means to `cabal new-run` a library. And even if that makes sense, I believe the ambiguity should just be resolved to the executable by default.

**Comment by 23Skidoo** [comment]
@fgaz, can you take a look at this? I think that old-run doesn't have this problem.

**Comment by fgaz** [comment]
Yup, old cabal works. `cabal new-run` without an explicit target also works.

**Comment by fgaz** [comment]
The problem is that the target resolution happens before any new-run code.

The [`Distribution.Client.TargetSelector:matchTargetSelector`](https://github.com/haskell/cabal/blob/a8036999a777505d4a68e499440ab50c1dedb582/cabal-install/Distribution/Client/TargetSelector.hs#L812) function isn't aware of the command and can't filter the targets depending on it.

If no explicit targets are specified, that function doesn't get called at all because, up in the call stack, [`resolveTargetSelectors`](https://github.com/haskell/cabal/blob/a8036999a777505d4a68e499440ab50c1dedb582/cabal-install/Distribution/Client/TargetSelector.hs#L453) matches on `[]` and returns `TargetImplicitCwd` which _then_ can be filtered by `CmdRun.hs`.

If we want to fix this we probably want to pass the action directly to [`readTargetSelectors`](https://github.com/haskell/cabal/blob/a8036999a777505d4a68e499440ab50c1dedb582/cabal-install/Distribution/Client/TargetSelector.hs#L198) in [every `Cmd*.hs`](https://github.com/haskell/cabal/blob/a8036999a777505d4a68e499440ab50c1dedb582/cabal-install/Distribution/Client/CmdRun.hs#L117). But then _what_ do we pass? A `TargetAction`? Then we'll have to add a `RunAction` and do some refactoring. _Another_ action type?

Or maybe we should pass a filtering function like we do in `runProjectPreBuildPhase`.

**Comment by ezyang** [comment]
My suggestion is to add another parameter, but don't try very hard to make it general. Like it could just be `data WhichTargets = AllTargets | ExeTargets`. If you figure out there's a better thing to do later we can refactor again.

**Comment by hvr** [comment]
Does the same issue occur for `new-test` and `new-bench`?

**Comment by fgaz** [comment]
Yes. All `new-*` commands have this issue

**Comment by fgaz** [comment]
@ezyang as per https://github.com/haskell/cabal/issues/4602#issuecomment-398846014, this probably needs a general solution now
