### ISSUE TITLE
nix integration doesn't work with benchmarks

### ISSUE THREAD

**Issue by daig** [haskell/cabal#4762]
when I do `cabal --enable-nix configure --enable-benchmarks` , it's using the dependencies from `testHaskellDepends` rather than `benchmarkHaskellDepends` in `shell.nix` 
This may be an issue with `mkDerivation` rather than cabal? But also in the documentation for cabal it does not list `bench` as a command that works with nix.

**Comment by ttuegel** [comment]
The Haskell infrastructure in Nixpkgs does not by default include benchmark dependencies because Nixpkgs does not run the benchmarks. If you want to enable benchmarks in your `shell.nix`, you can pass `withBenchmarkDepends = true` to `mkDerivation`. cabal-install does not do this automatically because we should not be wedded to a particular Nix expression format, i.e. we want `cabal --enable-nix` to work even if you aren't using `cabal2nix`.

**Comment by fosskers** [comment]
I have three `.nix` files, `default.nix` from `cabal2nix`, a bare-bones `release.nix`, and a `shell.nix` that looks like this:

```nix
(import ./release.nix).scalaz-and-cats.env
```
and I'm trying to figure out where to include `withBenchmarksDepends = true`. Into `default.nix` doesn't seem right, since that's frequently reautogenerated.

**Comment by fosskers** [comment]
Direct addition to my `default.nix` yields:
```
colin@yumi ~/c/s/s/haskell> nix-shell
error: anonymous function at /nix/store/gdqvq8rvbh74fsjijsqkhx3b6h77fhvd-nixpkgs-18.03pre124071.310ad4345bb/nixpkgs/pkgs/development/haskell-modules/generic-builder.nix:6:1 called with unexpected argument ‘withBenchmarkDepends’, at /nix/store/gdqvq8rvbh74fsjijsqkhx3b6h77fhvd-nixpkgs-18.03pre124071.310ad4345bb/nixpkgs/lib/customisation.nix:74:12
```
Instead, changing my `shell.nix` to the following:
```nix
(import ./release.nix).scalaz-and-cats.env // { withBenchmarkDepends = true; }
```
lets me enter the shell fine, but still fails on `cabal configure --enable-benchmarks` with:
```
Resolving dependencies...
Warning: solver failed to find a solution:
Could not resolve dependencies:
rejecting: scalaz-and-cats-0.1.0.0:!bench (constraint from config file,
command line flag, or user target requires opposite flag selection)
trying: scalaz-and-cats-0.1.0.0:*bench
unknown package: text (dependency of scalaz-and-cats-0.1.0.0:*bench)
Dependency tree exhaustively searched.
Trying configure anyway.
Configuring scalaz-and-cats-0.1.0.0...
cabal: Encountered missing dependencies:
criterion >=1.1 && <1.3, text -any
```

**Comment by ttuegel** [comment]
Your `shell.nix` should look like this:
```.nix
 # We need to import Nixpkgs from somewhere. Anywhere will do, but this is simple.
let nixpkgs = import <nixpkgs> {}; in
let inherit (nixpkgs.pkgs) haskell haskellPackages; in

# You could use another Haskell package set instead of the default haskellPackages;
# this is not the important part.
let orig = haskellPackages.callPackage ./default.nix {}; in

# This (haskell.lib.overrideCabal) is the important part:
let
  withBenchs =
    # Use overrideCabal so that withBenchmarkDepends is given to mkDerivation.
    haskell.lib.overrideCabal orig (args: args // { withBenchmarkDepends = true; });
in

withBenchs.env
```

The reason that this
```.nix
(import ./release.nix).scalaz-and-cats.env // { withBenchmarkDepends = true; }
```
won't work is that it creates the shell environment (`scalaz-and-cats.env`) and _then_ sets `withBenchmarkDepends`. In other words, `withBenchmarkDepends` will be a shell variable inside the environment and nothing more. We need that option to go to `mkDerivation` before the environment is created, and so we need to use `overrideCabal`.

> My default.nix references criterion and text as plain as day, so it's very strange to me that cabal can't find it:

Not everything in the call to `mkDerivation` ends up in the builder! (For example, it doesn't set `homepage` or `license` in your shell, either.) It omits `benchmarkHaskellDepends` by default because the Nixpkgs builds don't run the benchmarks and therefore these dependencies are extraneous.

**Comment by fosskers** [comment]
After copy-pasting what you have there and running `nix-shell`, I still get:
```
colin@yumi ~/c/s/s/haskell> nix-shell
error: anonymous function at /nix/store/gdqvq8rvbh74fsjijsqkhx3b6h77fhvd-nixpkgs-18.03pre124071.310ad4345bb/nixpkgs/pkgs/development/haskell-modules/generic-builder.nix:6:1 called with unexpected argument ‘withBenchmarkDepends’, at /nix/store/gdqvq8rvbh74fsjijsqkhx3b6h77fhvd-nixpkgs-18.03pre124071.310ad4345bb/nixpkgs/lib/customisation.nix:74:12
```

**Comment by fosskers** [comment]
Ah ha! The proper line was:
```
    haskell.lib.overrideCabal orig (args: args // { doBenchmark = true; });
```
as referenced [here](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/haskell-modules/lib.nix#L26). This pulled down `criterion` and friends properly.

**Comment by fosskers** [comment]
The final working form:
```nix
let nixpkgs = import <nixpkgs> {};
    orig = nixpkgs.pkgs.haskellPackages.callPackage ./default.nix {};
in (nixpkgs.pkgs.haskell.lib.doBenchmark orig).env
```
