### ISSUE TITLE
More visible warnings that library and executables should not have a common hs-source-dir

### ISSUE THREAD

**Issue by Lysxia** [haskell/cabal#4906]
This is quite an easy situation to run into, some don't even notice they are compiling their library twice and that it can be avoided. Somehow I can't find very good documentation on the topic to point newcomers to. The best reference I have so far is [this SO answer](https://stackoverflow.com/a/6711739/6863749).

- Are the problem and solution better explained somewhere in Cabal's documentation?

- What do you think of adding a warning for this? I think it should be on by default.

**Comment by hvr** [comment]
Well, it's a bit more subtle. There's nothing inherently "wrong" about a package that uses shares the same hs-source- dirs among multiple components (it may be because you need different ghc-options/cpp-options for the same modules). We should only warn in this case if we can detect that a shared `hs-source-dir` can be replaced by an intra-package `build-depends`. But in the presence of cabal conditionals, this seems too complicated to do properly for the general case; and we certainly don't want to err too much on the false positive side, as this is merely an optimisation.

However, the real problem is when you have overlapping modules, e.g. when you `build-depend` on the library component, and at the same time have overlapping `hs-source-dirs` files. This leads into a situation which is more problematic, as it results linking against a library which may have overlapping modules with the current component, potentially running into subtle errors.

**Comment by Lysxia** [comment]
Thank you, this was very informative. I agree with all of it.

**Comment by 23Skidoo** [comment]
So, the tl;dr here is that we should warn when a component and a library it depends on share the same modules.

**Comment by tysonzero** [comment]
#5335

**Comment by jneira** [comment]
Closing in favour of #5335
