### ISSUE TITLE
Use cabal without .cabal file?

### ISSUE THREAD

**Issue by doofin** [haskell/cabal#5091]
Is it possible to avoid write .cabal file for build management and use haskell code for everything?  For example, build.sbt for scala(althought code in sbt file have some little difference with scala code )?

**Comment by 23Skidoo** [comment]
Take a look at https://github.com/ocharles/dhall-to-cabal.

**Comment by doofin** [comment]
That definitely is not what I am asking,I would like to use haskell for build files ,not some other language

**Comment by 23Skidoo** [comment]
That's the closest existing thing I'm aware of.

**Comment by angerman** [comment]
Shake? Shakebuild.com

Hadrian (GHCs new build system) uses shake as build system instead of make

**Comment by gbaz** [comment]
Note: You never never need a cabal file to just build using the Cabal library (although it is convenient). You can always just create a custom Setup.hs script directly and use that. Cabal files are necessary for package bundling and distribution, however. (Though even then, they can have very customized Setup.hs scripts).

**Comment by 23Skidoo** [comment]
Using `lib:Cabal` still requires you to produce a `GenericPackageDescription` (basically a parsed `.cabal` file) to feed to it, though *in theory* you can write a setup script that doesn't depend on `lib:Cabal`.

**Comment by doofin** [comment]
Setup.hs seems to do the thing ,but there is not much information except [https://downloads.haskell.org/~ghc/7.0.2/docs/html/Cabal/builders.html](url) ...

Are there more comprehensive guide on managing haskell project with only Setup.hs file or Shake?

**Comment by gbaz** [comment]
I think there's no guide to just using Setup.hs files because nobody really wants to do it. The haddock documentation of the `Distribution.Simple` hierarchy gives a fair amount of info. In particular, you'll want this function as your entry point: https://hackage.haskell.org/package/Cabal-2.0.1.1/docs/Distribution-Simple.html#v:defaultMainWithHooksNoRead

This repo has code that lets you see how lots of the stuff is set conventionally: https://github.com/TerrorJack/Cabal-playground

That said, I don't know why you'd want to do this, and don't really recommend it. Even if you do need _some_ custom Setup.hs code, the pattern is typically to do the minimum possible there, and seek to put as much information in the cabal file as possible.

Shake isn't a haskell-specific tool. It's a DSL in haskell that gives you a "better make". So if you have experience with makefiles, the shake manual should make some sense to you: http://shakebuild.com/manual

That said, if you wouldn't be comfortable writing a makefile for your Haskell project, it is likely you won't feel comfortable writing a shake build for it either. I.e. you need to have some grasp of the intermediate build-artifacts, etc. -- all the things that cabal very nicely takes care of for you.

**Comment by doofin** [comment]
Thanks for the docs.I do not mean cabal is bad to use , what i want is "haskell" for everything,that is you use it for anything including build specification,without creating separating language or text format.If .cabal file are written in haskell , you get the full power of haskell , not some specific textual representation.

**Comment by doofin** [comment]
I think `defaultMainWithHooksNoRead :: UserHooks -> GenericPackageDescription -> IO ()` is exactly what I am searching for. With a convenient DSL of building `GenericPackageDescription` , which is  just .cabal file,it seems not so cumbersome for a pure haskell approach.
