### ISSUE TITLE
--enable-tests, --enable-documentation defaults

### ISSUE THREAD

**Issue by mcandre** [haskell/cabal#5255]
Unit tests and haddock break when the cabal flags `--enable-tests`, `--enable-documentation` are off, which is the default behavior unfortunately. I think `--enable-tests` should be on by default when running `cabal install` against a local `*.cabal` development package, and `--enable-documentation` should generally be on by default, in order to fix haddock.

As a workaround, I am explicitly supplying `--enable-tests` to my local `cabal install` runs against `*.cabal` files; and doing a lot of `ghc-check` ... `cabal install --force-reinstalls --enable-documentation`... to fix haddock for the dependency packages that were already installed.

**Comment by hvr** [comment]
Can you be more specific in which way "Unit tests and haddock break"?

**Comment by gbaz** [comment]
Also note that you can set these defaults yourself in ~/.cabal/config?

**Comment by 23Skidoo** [comment]
> `--enable-documentation`

Is this about `doctest`? See also the experimental `cabal doctest` command (#4480).

**Comment by gelisam** [comment]
> I think `--enable-tests` should be on by default

Fun fact: `--disable-tests` is not the default either! At least, that's what I conclude from my experimentations. There seems to be a third option, "leave the tests be", which is used when neither `--enable-tests` nor `--disable-tests` is specified. If `--enable-tests` was the default, there would be no way to specify this third option. Which would make me sad, because it's the only configuration under which my project builds at the moment :(

**Comment by gelisam** [comment]
Upon further investigation:

* by default, `cabal new-configure` will pick a build plan which _does_ include the tests, if possible. It might not be possible if the only working build plan includes the library's dependencies but not the test suite's. If that's the case, `cabal new-configure` will silently disable the test, while `cabal new-configure --enable-tests` will complain that it cannot find a build plan. `cabal new-build --disable-tests` disables all the tests.
* by default, `cabal new-build` and `cabal new-build all` only build the libraries and the executables; but if `--enable-tests` was passed to `cabal new-configure`, or if `tests: True` is in `~/.cabal/config`, then it will also build the tests.
* you can build the tests with `cabal new-build all:tests`. if `cabal new-configure` disabled some of the tests, those won't get built.

In my project, I am downloading a local copy of several dependencies and compiling them as local packages. I only want to run my project's tests, not the tests of my dependencies. Some of my dependencies have tests which aren't compatible with my project's build plan. With cabal's current behaviour, I can use `cabal new-configure`, which will disable those incompatible tests, and then `cabal new-build myproject:test:mytest` to build my project's test suite. If `--enable-tests` was the default, I couldn't do that, because `cabal new-configure` wouldn't find a build plan and `cabal new-configure --disable-tests` would disable my project's test suite too.

I see three possibilities:
* make `--enable-tests` the default, and add a new flag (`--only-buildable-tests`?) to tell `cabal new-configure` to disable the tests for which a build plan cannot be found. I think such a flag [should be added anyway](https://github.com/haskell/cabal/issues/5079#issuecomment-380815488).
* keep the current default for `cabal new-configure`, but change the default for `cabal new-build` and/or `cabal new-build all` so that it also builds the (enabled) tests, or add a `cabal new-build ALL` which builds more than `all`. This is [being considered](https://github.com/haskell/cabal/issues/5079#issuecomment-364394740).
* leave the defaults as is, and add `tests: True` to your `~/.cabal/config`

**Comment by 23Skidoo** [comment]
Related: #5079.

**Comment by ulysses4ever** [comment]
From the OP description:

> Unit tests and haddock break when the cabal flags --enable-tests, --enable-documentation are off

`cabal haddock` now implies `--enable-documentation` (#8259), so the second part is addressed now, I think. For the first part (`--enable-tests`), there's #5079. Should we close this ticket?

**Comment by ulysses4ever** [comment]
As no one objected, I'm closing this for reasons described in the previous comment. PLease, feel free to re-open if you think it's necessary. Thank you everyone for insightful discussion!
