### ISSUE TITLE
checkPackageVersions should check upper bound of all packages, not just base

### ISSUE THREAD

**Issue by wereHamster** [haskell/cabal#5317]
There should not be a reason to treat base differently than other packages. For example cabal happily accepts no bounds at all on bytestring, yet it is a boot lib so it should receive the same treatment as base.

**Comment by hvr** [comment]
With my Trustee and PVP maintainer hat on, I strongly support this. I'd want to see `cabal check` to be more configurable, so that you can perform checks for different purposes (e.g. if you work on packages for in-house purposes and don't intend to upload to Hackage, then you may want to disable some checks if you use `cabal check` as part of your CI; however if you upload to Hackage you typically want all quality issues in your meta-data pointed out). We already have the concept of different `cabal check` severities, but this should be made a bit more fine-grained imho, as well as being exposed via the CLI.

**Comment by 23Skidoo** [comment]
Related: #4683

**Comment by grayjay** [comment]
#1930 also suggests comparing the upper bounds against the latest major versions on Hackage.

**Comment by ffaf1** [comment]
Closed by #8361
