### ISSUE TITLE
Allow --allow-newer to be passed to `Setup configure`

### ISSUE THREAD

**Issue by bgamari** [haskell/cabal#5407]
Currently `Setup configure` doesn't support the `--allow-newer` flag. It would be nice if this weren't so.

**Comment by 23Skidoo** [comment]
We actually had this feature and then removed it.

**Comment by 23Skidoo** [comment]
Closing in favour of #3581.

**Comment by angerman** [comment]
@bgamari I'm using the following with `nix`, to generate the proper exact-config values:

https://github.com/angerman/stackage.nix/blob/bfe36ce019846af7899c05e350bd8f92ee2d9136/package-set.nix#L36-L105

**Comment by mpickering** [comment]
`--exact-configuration` seems to not be quite right here if as @angerman notes in his link that automatic flag configuration is not performed when it is turned on. 

The reason why this ticket exists is that jailbreaking on nixos doesn't remove bounds on dependencies in conditionals because it can break automatic flag configuration.
