### ISSUE TITLE
Cabal build fail to import module

### ISSUE THREAD

**Issue by zhengqigao** [haskell/cabal#5593]
System: macOS high sierra version 10.13.6.
Cabal: 2.4.0.0

I have already installed SDL module via `cabal install SDL`. I write a simple script:
 
```
    module Main where
    import qualified SDL
    main :: IO ()
    main = putStrLn "Hello, Haskell!"
```
then I run the following commands.
```
cabal init
cabal configure
```
Next I modify `myproject.cabal` by adding SDL to build_depends. Finally I run:
```
cabal build
```
However, it throws an error:

<img width="520" alt="screen shot 2018-09-26 at 6 27 08 pm" src="https://user-images.githubusercontent.com/22574204/46074322-d0250e00-c1b9-11e8-8703-aee634faedfb.png">

How should I fix it?

**Comment by jneira** [comment]
Hi, the [package SDL](http://hackage.haskell.org/package/SDL) does not have any module named `SDL`.
You could import the main module in this way: `import qualified Graphics.UI.SDL as SDL` so you could use its functions: `SDL.anyFunction`

**Comment by GoldenCheese** [comment]
> Hi, the [package SDL](http://hackage.haskell.org/package/SDL) does not have any module named `SDL`.
> You could import the main module in this way: `import qualified Graphics.UI.SDL as SDL` so you could use its functions: `SDL.anyFunction`

Thanks bro. That works! Moreover, I have two more questions.

1. Why can I run `ghc -o main main.hs` to compile the same script without throwing that "cannot find module"error?

2. Since I am a beginner in haskell, after I fix the error about SDL module using your suggestion, now `import SDL.Vec` throws a similar error : `Could not find module SDL.Vec`. How should I fix this one?

**Comment by GoldenCheese** [comment]
Well, I think I get this. [sdl2](http://hackage.haskell.org/package/sdl2-2.4.1.0/docs/SDL.html#g:3) contains [Graphics.UI.SDL](http://hackage.haskell.org/package/SDL). From [here](https://hackage.haskell.org/package/sdl2-2.4.0.1/changelog), we can see that `Graphics.UI.SDL` has been moved to `SDL.Raw`. To successfully `import SDL`, we can follow [this](https://github.com/andersk/haskell-sdl2). Notice, when you need to run `cabal configure`, please run `cabal configure --ghc-option=-fPIC`.

At least this works for me...

**Comment by jneira** [comment]
Just to avoid posible future confusions: `sdl2` and `SDL` are haskell *packages*, each one of them contains several *modules*.
Coincidentally the name of one of the modules of the `sdl2` package matches the name of the package `SDL`. I guess you installed globally the `sdl2` package (with `cabal install sdl2`), that's why ghc can access its module `SDL`.
Afaik they are independent packages that make bindings to a [c library called (oh my!) SDL](https://www.libsdl.org/) so i think `sdl2` does not "contain" `Graphics.UI.SDL`.
According the README of sdl2 the `cabal configure --ghc-option=-fPIC` command is needed only to let you run `cabal repl`.
