### ISSUE TITLE
`cabal v2-install` error reporting

### ISSUE THREAD

**Issue by hvr** [haskell/cabal#5641]
If `v2-install` fails, it exits with a non-zero exit code, *but* it gives no indication on stdout/stderr:

```
$ cabal v2-install curl
Resolving dependencies...
Build profile: -w ghc-8.4.4 -O1
In order, the following will be built (use -v for more details):
 - curl-1.3.8 (lib:curl) (requires build)
Starting     curl-1.3.8 (all, legacy fallback)
$ echo $?
1
```

only when running with `-j1` one would see what went wrong:

```
$ cabal v2-install curl -j1
Resolving dependencies...
Build profile: -w ghc-8.4.4 -O1
In order, the following will be built (use -v for more details):
 - curl-1.3.8 (lib:curl) (requires build)
Configuring curl-1.3.8...
checking for gcc... /usr/bin/gcc
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables... 
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether /usr/bin/gcc accepts -g... yes
checking for /usr/bin/gcc option to accept ANSI C... none needed
checking how to run the C preprocessor... /usr/bin/gcc -E
configure: error: curl libraries not found, so curl package cannot be built
See `config.log' for more details.
```

Instead, `v2-install` ought to dump a fragment of the output like e.g. `new-build` does when one of its dependencies fails to build.

cc @typedrat

**Comment by fgaz** [comment]
I investigated this a bit and here are some notes:

Here's the problem:
postBuildPhase calls dieOnBuildFailure, which considers the new-install case as "simple":

https://github.com/haskell/cabal/blob/002b3017414920fb8b7a2322ef1c4ef3bfcf2112/cabal-install/Distribution/Client/ProjectOrchestration.hs#L931

...and it simply exits.

Why is it "simple"?

https://github.com/haskell/cabal/blob/002b3017414920fb8b7a2322ef1c4ef3bfcf2112/cabal-install/Distribution/Client/ProjectOrchestration.hs#L996-L1014

Because the failing packages are both "self explanatory" and "root packages" (without reverse deps).

"self explanatory" seems right, so there's two possible solutions:
  * Are install targets really "root packages"? Maybe they shouldn't be considered as such.
  * Add another param to dieOnBuildFailure that disables the simple case / tells it that we are in new-install
