### ISSUE TITLE
cabal new-build silently ignores changes

### ISSUE THREAD

**Issue by maximpichler** [haskell/cabal#5793]
new-build fails to recompile modules not mentioned in the cabal file (exposed/other-modules).

When such a module changes after the executable was previously built, it happily reports "Up to date", misleading the user dangerously.

This behaviour is different with v1-build.

**Comment by hvr** [comment]
@maximpichler  that's by design; a package description with incomplete `*-modules` specification is considered incorrect in the new-build paradigm. To this end we added support to GHC for things like `-Wmissing-home-modules` to help you detect inaccurate/incomplet `*-modules` specification and catch common mistakes.
