### ISSUE TITLE
Recompiling modules is preferred over local package

### ISSUE THREAD

**Issue by ag-eitilt** [haskell/cabal#6036]
I've just tried to move the different components of one of my projects out of their separated source folders (`src/Category/Package/Module` to simply `Category/Package/Module`, but also `test/Category/Package/Module/Test` to `Category/Package/Module/Test`) to work better with direct `runhaskell` invocation -- Cabal's great and still my primary tool, but I don't see the need for lock-in if I can avoid it.  However, while that then allows `runhaskell` to work without any further tweaking, the `cabal new-build` of the test suite winds up failing due to packages not being listed in the build-depends.  *That* is in turn because when Cabal tries to link to the modules from the library component, it sees that there's a module of the same name in the source directory and tries to build it instead, despite not being given any instruction to do so.

Cabal knows it's doing something wrong, even, since it triggers the `-Wmissing-home-modules` message.  What step's missing is that it then doesn't check for that module in any of the build-depends.  I know you'd generally want to prioritize any local modules over ones with the same name imported from elsewhere, to allow authors to override them if necessary, but is there any reason not to restrict that behaviour to occur *only* if the module is listed in either the exposed-modules or the other-modules sections?

In pseudocode, rather than the current

    if moduleName `elem` getContents sourceDir
    then if moduleName `elem` exposedModules ++ otherModules
         then build moduleName
         else do
              warn $ MissingHomeModule moduleName
              build moduleName
    else if searchDepends moduleName
         then link moduleName
         else warn $ UnknownModule moduleName

I'd like to see

    if moduleName `elem` getContents sourceDir
    then if moduleName `elem` exposedModules ++ otherModules
         then build moduleName
         else if searchDepends moduleName
              then link moduleName
              else do
                   warn $ MissingHomeModule moduleName
                   build moduleName
    else if searchDepends moduleName
         then link moduleName
         else warn $ UnknownModule moduleName

I can take a look at creating a patch myself in a few days, if nobody complains, but this seemed like the thing to run by everyone first, and if it's just a couple-line fix, then it might be easier for someone already familiar with the code base rather than me digging into the Haddock.

**Comment by hvr** [comment]
Unless I misunderstand what you're suggesting, what you're asking is technically not possible; Basically this isn't a limitation of Cabal but rather of the respective Haskell compilers; specifically GHC's `ghc --make` mode of operation doesn't (unless I'm missing a trick or GHC feature) give you enough control over the module search logic to prevent GHC from picking up a "local" instance of a module instead of procurring it from one of its `-package`s -- which is in general a good default, except in your use-case. This technical limitation is also why the `-Whome-missing-modules` warning was implemented in GHC, as this was the easiest way detect such build misconfiguration issues where modules leak in unintended ways (and more importantly also because cabal needs to have accurate module<->component information for its rebuild logic to work properly).

**Comment by ag-eitilt** [comment]
Ah, I was afraid of that after a bit more thinking brought up that `-Wmissing-home-modules` is on the GHC side rather than Cabal.  Not having run the compiler directly myself, I was still thinking in terms of C(++) and assuming Cabal passed each module explicitly.  Thanks for getting back anyway!
