### ISSUE TITLE
cabal gets confused if ~/.cabal is a symlink

### ISSUE THREAD

**Issue by Araneidae** [haskell/cabal#6094]
On my system I have `~/.cabal` linked to a separate filesystem (my home directory has a space quota).  When I run, for example, `cabal install alex` I get the following message (edited to elide actual names):

```
Warning: could not create a symlink in ~/.cabal/bin for alex because
the file exists there already but is not managed by cabal. You can create a
symlink for this executable manually if you wish. The executable file has been
installed at /extra/filesystem/dot.cabal/bin/alex
```

Of course, the two directories mentioned above are identical.  This message was from cabal 2.4.1.0.

**Comment by fgaz** [comment]
Does `cabal new-install alex` work?

**Comment by Araneidae** [comment]
Sort of, am not sure:

```
$ cabal new-install alex
Resolving dependencies...
Build profile: -w ghc-8.0.2 -O1
In order, the following will be built (use -v for more details):
 - alex-3.2.4 (exe:alex) (requires build)
Starting     alex-3.2.4 (exe:alex)
Building     alex-3.2.4 (exe:alex)
Installing   alex-3.2.4 (exe:alex)
Completed    alex-3.2.4 (exe:alex)
Symlinking 'alex'
cabal: Path '/home/mga83/.cabal/bin/alex' already exists. Use
--overwrite-policy=always to overwrite.
```

After rerunning with `--overwrite-policy=always` as suggested it has changed the executable copy to a symlink to `../store/ghc-8.0.2/alex-3.2.4-213c4d2557ca0b26f1ab6189aa2202e6dd27949cb230b4a8c6ba557e6dcf2832/bin/alex`, so I guess that does count as working.

So looks like that might be a yes!

**Comment by int-e** [comment]
As far as I can is a consequence of a changed default for `symlink-bindir`; it used to be empty, but was changed to ~/.cabal/bin recently, presumably for the benefit of users of `v2-install` (whch would otherwise have a hard time locating installed binaries). For `v1-install`, the intended value was something like ~/bin, so the semantics of the value has changed...

The warning has nothing to do with ~/.cabal being a symbolic link, and I've checked that setting `symlink-bindir` to an empty string makes it disappear.

**Comment by gbaz** [comment]
closing based on above discussion

**Comment by fgaz** [comment]
Moreover, `--symlink-bindir` was changed to `--installdir`
