### ISSUE TITLE
--no-run-solver option

### ISSUE THREAD

**Issue by tseenshe** [haskell/cabal#6204]
As discussed in https://github.com/haskell/cabal/issues/6203 it can be beneficial to workflows (e.g. large projects with many local packages) to run the solver rarely and to receive an error in preference to cache invalidation.

It would be good if this could be put behind a flag, e.g. `--no-run-solver` with the ability to go in `cabal.project.local`, and a `--run-solver` overriding.

Workflow: a developer could run the solver when they rebase their branch, then forgetting some trivial flag like `-O0` or `--enable-tests` will cause an error rather than a (time costly) cache invalidation that requires another invalidation to fix.

**Comment by phadej** [comment]
FWIW, you can add `optimization: False` and `tests: True` to `cabal.project.local` so they aren't "trivially' forgotten.

**Comment by DanielG** [comment]
Indeed but the specific problem @tseenshe has is that on their rather large projects the solver takes around a minute to run and since this happens without user consent it can be irritating depending on the workflow.

I actually think there's another use-case for this flag. When you `cabal update` normally v2-build will just start using newer dependencies but sometimes you might want to just stick to the old ones which this would let you do.

**Comment by phadej** [comment]
@DanielG for that you should really use `index-state`

**Comment by DanielG** [comment]
That's one option, sure.

However for the workflow I'm thinking of that's not really the nicest thing. As far as I can see there's no option to say "pin the index state to the current one" I can do `=HEAD` but that'll just hardcodes `HEAD` in cabal.project.local but that's another issue.

Anyways the main use-case is still a valid one I think. Being able to opt-out of a potentally long running computation when it's really not absolutely required to keep working seems like a no-brainer to me.

**Comment by tseenshe** [comment]
Closing because I no longer feel the need to use such a flag.
