### ISSUE TITLE
Update docs for 3.x release: remove `v2-` prefix and unflag as experimental 

### ISSUE THREAD

**Issue by gbaz** [haskell/cabal#6213]
The cabal users guide still describes the v2- stuff with the prefix and says it is experimental.

https://cabal.readthedocs.io/en/latest/nix-local-build.html

Now that it is the standard path, shouldn't we at least do a small update to the docs to get rid of all the v2- prefix stuff and indicate that this is the normal mode of operation?

**Comment by m-renaud** [comment]
See #6194 for some ideas I had to improve the docs, this would include at the minimum updating everything for `v2-` as the default without the prefix.

**Comment by gbaz** [comment]
I think that's a great proposal. But we have a cabal out _today_ that the docs don't explain correctly. We should fix that first, and independently worry about making the docs better. For now let's just make sure they're correct :-)

**Comment by m-renaud** [comment]
Reviving this thread :) @gbaz are there specific concerns you have about updating docs to move to 3.0 now considering how long it has been the default?

To me fixing any incorrectness in existing docs and switching to 3.0 seem completely orthogonal to one another. If you can give me some specific actionable changes you'd like to see I can take a look at those, otherwise I'd like to decouple them and move forward with updating the references to v2. Let me know!

**Comment by ulysses4ever** [comment]
Looks like it will be closed by #9087.
