### ISSUE TITLE
UNEXPECTED FAIL: cabal-testsuite\PackageTests\CustomPreProcess\setup.test.hs in `master`

### ISSUE THREAD

**Issue by phadej** [haskell/cabal#6219]
cc @23Skidoo @hvr

**Comment by phadej** [comment]
https://github.com/haskell/cabal/commit/49cefe85fbc5d7cc8eb0bc6cab77a98a39526ea9 seems to be the first commit breaking.

But as it's a merge commit, it's very hard to say what's wrong. That code was in `master` already...

**Comment by hvr** [comment]
so this is actually a Windows-specific segfault?

```
Linking .\setup.cabal.dist\work\dist\setup\setup.exe ...
C:\projects\cabal\cabal-testsuite\PackageTests\CustomPreProcess\setup.cabal.dist\work\dist\setup\setup.exe configure --verbose=verbose +nowrap +markoutput --builddir=setup.cabal.dist\work\dist --ghc --with-compiler=C:\ProgramData\chocolatey\lib\ghc\tools\ghc-8.0.2\bin\ghc.exe --prefix=C:\projects\cabal\cabal-testsuite\PackageTests\CustomPreProcess\setup.cabal.dist\usr --global --package-db=clear --package-db=global --package-db=C:\SR\ghc-8.0.2\package.db --package-db=C:\projects\cabal\dist-newstyle\packagedb\ghc-8.0.2 --enable-deterministic --ipid=internal-preprocessor-test-0.1.0.0 --dependency=base=base-4.9.1.0 --dependency=base=base-4.9.1.0 --dependency=base=base-4.9.1.0 --dependency=directory=directory-1.3.0.0 --disable-tests --exact-configuration --disable-benchmarks --with-ghc=C:\ProgramData\chocolatey\lib\ghc\tools\ghc-8.0.2\bin\ghc.exe --with-haddock=C:\ProgramData\chocolatey\lib\ghc\tools\ghc-8.0.2\bin\haddock.exe
Segmentation fault/access violation in generated code
```

Maybe @Mistuke might have some ideas...?

**Comment by Mistuke** [comment]
That's too little information to go on, `8.0.2` is quite old though... is it possible to try with a newer GHC? The sudden unexplained failure feels like the stack overflow failure I fixed in 8.6.3. There's a bug in GHC's liveliness analysis that makes it think it needs a ton of stack space for a few Cabal modules (allocated but never used), but older GHC's couldn't allocate unmapped pages correctly so it would segfault. It would sometimes work depending on what the TEB was set to when the program started.

**Comment by 23Skidoo** [comment]
I guess we can try upgrading GHC on AppVeyor.

**Comment by phadej** [comment]
GHC upgraded, this doesn't happen anymore.
