### ISSUE TITLE
backpack breaks --enable-coverage

### ISSUE THREAD

**Issue by vmchale** [haskell/cabal#6397]
**Describe the bug**

Running `cabal build --enable-coverage` does not work when depending on backpack-ified packages; `cabal build --enable-profiling` does work

**To Reproduce**

In my [archive-backpack](https://github.com/vmchale/archive-backpack/) repo:

```
rm -rf dist-newstyle
cabal v2-build all -w ghc-8.6.5 --enable-coverage
...
Configuring hstar-0.1.0.0...
Error:
    The following packages are broken because other packages they depend on are missing. These broken packages must be rebuilt before they can be used.
planned package hstar-0.1.0.0 is broken due to missing package archive-sig-0.2.0.2-inplace+5LcY8JHokyDHyTjA8czqM

cabal: Failed to build hstar-0.1.0.0. The failure occurred during the
configure step.
...

```

**Expected behavior**

Build would not fail

**System information**
 - Linux, x86_64

```
cabal-install version 3.0.0.0
compiled using version 3.0.0.0 of the Cabal library 
```
 - GHC 8.6.5

Thanks :)

**Comment by alt-romes** [comment]
#9464 will make it so that backpack no longer *breaks* --enable-coverage, so that it will now work and emit coverage reports. However, the indefinite modules will not be included in the reports -- as far as I know, HPC does not support backpack in the sense that it's unclear what it means to cover an indefinite module with multiple instantiations...

So, as I see it, #9464 should close this?

**Comment by gbaz** [comment]
I think its fine to close this issue with that -- but might be worth opening an issue for HPC just to note the conceptual problem to be solved.

**Comment by alt-romes** [comment]
Since #9464, we no longer consider backpack signatures and instantiations while generating an HPC report.
Ultimately, I'm fairly certain HPC does not yet support backpack, so I created a ticket to track that [hpc#12](https://gitlab.haskell.org/hpc/hpc/-/issues/12).
When fixed, we should revisit Cabal HPC report generation to include instantiated units and or signatures.

**Comment by Mikolaj** [comment]
@alt-romes: thank you very much!
