### ISSUE TITLE
Add Windows GitHub action job

### ISSUE THREAD

**Issue by phadej** [haskell/cabal#6486]
Maybe blocked on https://github.com/actions/virtual-environments/issues/30

**Comment by jneira** [comment]
Have you considered use azure pipelines? It has 10 concurrent jobs with no build time limit and no cache/artifacts limit (for now, he). Recently we added it to [haskell-ide-engine](https://dev.azure.com/hvriedel/hvriedel/_build/results?buildId=27&view=results) (running a total of 42 jobs)

**Comment by phadej** [comment]
@jneira, yes, however
- GitHub actions run on the same (i suspect) azure cloud
- 20 concurrent jobs
- 6 hours per job

https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#usage-limits

**Comment by phadej** [comment]
And to clarify, we already run Linux and MacOS jobs on GitHub actions. They work well.

**Comment by jneira** [comment]
good to know, we tried it and we had some problems with the cache limit: https://github.com/haskell/haskell-ide-engine/pull/1435#issuecomment-555577150
But recently they have increased the limit from 400 mb to 2gb: https://github.com/actions/cache/issues/6#issuecomment-571290282

**Comment by Mistuke** [comment]
re Github actions I have added the support in cabal nightlies https://github.com/Mistuke/CabalChoco/blob/master/nightly/cabal/tools/chocolateyInstall.ps1#L304

I will push to stable with next cabal release (or sooner if people are depending on it).

@jneira The issue you've reported is also fixed with https://github.com/Mistuke/CabalChoco/blob/master/nightly/cabal/tools/chocolateyInstall.ps1#L263

I've also created two new issues #6492 and #6493 for some pain points I have w.r.t. smooth configuration of cabal.

**Comment by phadej** [comment]
Done in #6482
