### ISSUE TITLE
Cabal website download links are outdated and down

### ISSUE THREAD

**Issue by Olius** [haskell/cabal#6656]
I would have created this issue on [the cabal-website Github page](https://github.com/haskell/cabal-website), but it doesn't seem to correspond to the latest version of the website and in fact doesn't seem very active.

The binary download links on the website are outdated and lead to a 404 error page.  The reason is that they point to downloads for `cabal-install` version 3.0.0.0 at
https://downloads.haskell.org/~cabal/cabal-install-latest,
but the binaries in there are currently for version 3.2.0.0.

**Comment by m-renaud** [comment]
Hey @Olius, thanks for the report. The cabal-website Github repo is the one that drives http://www.haskell.org/cabal/ so I think that's where the issue should be filed, although looking closer you're very much right about the contents (at least the downloads page) not corresponding to what's in the repo:

On https://www.haskell.org/cabal/download.html:
```
Binary download for Linux (x86-64, requires glibc 2.12 or later)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

In the Github repo (https://github.com/haskell/cabal-website/blob/master/download.html#L39):
```
Binary download for Linux (x86, dynamically linked against libc):
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

@23Skidoo do you know what's going on there?

I do know that at least the index page was being updated from that repo since I recently added the cabal favicon which now shows up on the website.

**Comment by 23Skidoo** [comment]
I probably haven't checked in the latest version of download.html.

**Comment by 23Skidoo** [comment]
Should be fixed now.

**Comment by Olius** [comment]
Looks good.  Thanks!
