### ISSUE TITLE
What is purpose of `bootstrap.sh`?

### ISSUE THREAD

**Issue by phadej** [haskell/cabal#6701]
I understand it as a way to get `cabal-install` on a new environment, similarly how GHC has [unregisted builds](https://gitlab.haskell.org/ghc/ghc/-/wikis/building/unregisterised).

Yet, there seems to be an understanding in larger community that `bootstrap.sh` is **the way** to install `cabal-install` from source. (For example `ghcup` uses it).

I'm ok with either interpretation, but currently `bootstrap.sh` is a really crappy script which is definitely not up to the latter interpretation. We can make it so, but it has to be conscious decision and we must put effort into it.

I hope that @hvr, @23Skidoo weight in. Until then I'll continue to reply on `bootstrap.sh` related issues using my first interpretation: *don't use it*.

**Comment by hvr** [comment]
Well, there's a group of security-conscious people who want or even need to build as much from source as possible. But I've  been thinking for a while that it might be easier to have a much easier approach if we just had some `plan.json` to shell-script conversion tool; then you could grab a plan.json file from downloads.haskell.org/cabal/cabal-install-3.2.0.0 and generate your own shell script for your respective platform.

What I'm trying to say is that I'm not sure it ought to be our burden to have to maintain bootstrap.sh instead of providing the people who need want the tools to generate one themselves -- if that's feasible.

**Comment by phadej** [comment]
The existence of that tool would be nice, and I my `cabal-bundler` is indeed kind of a something of that spirit...

but what we should do with `bootstrap.sh` until such tool exists (`cabal-bundler` is at the moment tool for myself, and I not intend it for general public use in any foreseeable future).

**Comment by bgamari** [comment]
See #6719

**Comment by jneira** [comment]
It seems `bootsrap` was rewritten in the merged #6979 so the decision seemed to be continue using it.
Not sure there is something more actionable here so maybe should be closed
