### ISSUE TITLE
Make a release (buildable with GHC-8.10.1)

### ISSUE THREAD

**Issue by phadej** [haskell/cabal#6799]
The 3.2 branch is buildable with GHC-8.10.1 so we should make a release.

At the moment this is the only issue in 3.2.1.0 milestone. But if we need something backported, please speak up!

**Comment by fendor** [comment]
I think it would be great if the patch https://github.com/haskell/cabal/pull/6623 would be backported. 
It would be a huge benefit for `hie-bios`, since it simplifies the cabal cradles immensely, and therefore it would directly benefit `ghcide`, `haskell-ide-engine` and `haskell-language-server`.

--- 

Sorry if I am being pushy and annoying regarding this :/

**Comment by fgaz** [comment]
The hack for #5119 should definitely be backported

**Comment by phadej** [comment]
why that hack cannot be turned into a proper fix. I don’t like the idea of indefinitely backporting hack. Please make a PR to master with a commit to master who it should be fixed and why it cannot be fixed now. It’s annoying but not deadly.

No long-lived hacks, Please.

**Comment by phadej** [comment]
I released `Cabal-3.2.1.0`. We don't have resources to make `cabal-install-3.2.1.0`, and `cabal-install-3.4.0.0` is almost out of the door anyway.

Therefore closing.
