### ISSUE TITLE
cabal-install-3.0.1.0 not on Hackage

### ISSUE THREAD

**Issue by iliastsi** [haskell/cabal#6850]
cabal-install-3.0.1.0 is not on Hackage. This is causing a problem for Debian, where we want to update to LTS Haskell 15.13, since neither cabal-install-3.0.0.0 nor cabal-install-3.2.0.0 work.

Please consider uploading cabal-install-3.0.1.0 to Hackage. Thanks!

**Comment by 23Skidoo** [comment]
It's not on downloads.haskell.org either...

/cc @hvr

**Comment by 23Skidoo** [comment]
Looks like it just hasn't been released.

**Comment by phadej** [comment]
On 2020-04-02 Herbert sent a mail to us

> Quick update:
>
>- Bindists for linux, macOS & win32 completed:
>   https://downloads.haskell.org/~cabal/cabal-install-3.2.0.0/
>
>   This time is the first time I also stored .plan.json and
>.licences.html files along each binary distribution
>
>- I also update ghcup to install cabal-install-3.2 by default
>
>- Tamar intends to wire up the win32 bindists he created (and I
>uploaded to downloads.h.o) into chocolatey later today

I think he run out of time and steam to work through pending releases backlog. And therefore there is no tag because there is no release (I'm in favor of tagging only after release is done, and using -rc tags before that) **NOTE that 3.0 branch is advanced past cabal-install-3.0.1.0-rc4 tag**, it includes changelog updates.

**Comment by gridaphobe** [comment]
Any update on this? I'm having the same issue as @iliastsi trying to upgrade our internal Haskell distribution to the LTS 16 series. 

The only issue seems to be that cabal-install-0.3.0.0 has restrictive bounds on `base` and `hackage-security`. If those could be lifted with an x-revision I think the existing upload of cabal-install-0.3.0.0 would work just fine against LTS 16.

**Comment by gbaz** [comment]
obsolete
