### ISSUE TITLE
Remove show-build-info stuff from Cabal

### ISSUE THREAD

**Issue by phadej** [haskell/cabal#6892]
I was told that it doesn't need to be there.

**Comment by DanielG** [comment]
Can you elaborate on this?

**Comment by phadej** [comment]
@bubba could

**Comment by bubba** [comment]
@DanielG I've reworked the `cabal-install show-build-info` command part so that it no longer calls `Setup.hs`, which alleviates the need for the weird json munging and temporary files, and helps with custom setups. This means that it will only work for v2-style builds. But as far as I am aware I don't know of anything using `show-build-info` directly within Setup.hs?

**Comment by bubba** [comment]
Either way @phadej was mentioning that it reduces the churn on having show-build-info being tied to Cabal. If there are any caveats though to doing this all within `cabal-install` though I'm all ears

**Comment by DanielG** [comment]
I was going to use the Setup.hs interface in cabal-helper as a transitional mechanism though I'm not sure how relevant that still is.

I do wonder how you can even implement s-b-i with custom setups without a part in Setup.hs though?

**Comment by phadej** [comment]
I'd say that whatever first iteration is, it can just not work with `build-type: Custom`. If you want nice stuff, don't use `build-type: Custom`.

I really don't want to make compromises because someone wants to use `unsafePerformIO` kind of escape-hatch.

**Comment by phadej** [comment]
Oh, `show-build-info` is already in `Cabal-3.2`. Well, the ship has sailed.
