### ISSUE TITLE
Ask about (or at least signpost!) init --interactive

### ISSUE THREAD

**Issue by tom-audm** [haskell/cabal#7100]
I'm finding `cabal init` defaulting to non interactive insanely frustrating, particularly because there's no indication for users of how to get the interactive behavior. No note when the init happens, no documentation in `cabal --help`.

If you want to, say, init a library, and don't have all the required fields memorized, you probably want to use "--interactive". This is a basic need. Making basic tinkering with libraries more difficult just creates a subclass of users who are unable to contribute.

__What I think is best__

```
$ cabal init
Create automatically using sensible defaults? (y/n): y
Initializing using sensible defaults. You can make "cabal init" default to this by [...]
[...]
```

__Bare minimum__
```
$ cabal init
Defaulting to non-interactive init. To use interactive instead, use "cabal init --interactive". You can set the default in [...]
```

**Comment by gbaz** [comment]
👍 This should be an easy PR to do the "bare minimum" -- care to go for it?

**Comment by hvr** [comment]
I'd argue that `cabal init` invoked without any flags in non-interactive mode is *very* unlikely to be what you want. In fact, if you accidentally invoke it in the wrong folder you get no warning and you end up with a couple of files written in your current folder.

Consequently, since using `cabal init` non-interactively almost always involves supplying CLI flags to be useful, it doesn't seem too onerous to me to have `cabal init` default to *interactive* IMO, which as you seem to imply would be your preferred outcome.

For completeness, as you know there was quite a bit of controverisal discussion in #5902 which motivated for better or worse switching  `cabal init` to non-interactive mode.

**Comment by emilypi** [comment]
I would be more in favor of switching to back to interactive by default, and providing a note that tells you how to switch off the flag. Having non-interactive be the default is incredibly onerous to me because if i mess up and don't switching on the non-interactive flag, nothing happens. If i forget to switch to `--interactive`, it dumps crap immediately into whatever directory i'm in.

**Comment by gbaz** [comment]
I believe that init is now back to interactive by default, so closing on that basis?

**Comment by Mikolaj** [comment]
Yes, it is, in 3.6.

**Comment by gbaz** [comment]
Wait, this doesn't appear to be the case in 3.6 after all? I'm very confused.

**Comment by Mikolaj** [comment]
@gbaz: you are right, I mixed up `master` with `3.6`. It's not interactive in 3.6, but will be in 3.8. I hope I got it right this time?

**Comment by gbaz** [comment]
ok, just checked master and indeed its changed on master. closing again :-)
