### ISSUE TITLE
Question: defining language extensions for local packages in cabal.project

### ISSUE THREAD

**Issue by akrmn** [haskell/cabal#7118]
I'm wondering if it's possible to have a section of `cabal.project` in which to set the language extensions to be used for compiling the local packages. Perhaps there's already a way to do this, but I haven't been able to find it. If there isn't, but others would be interested in seeing it added, I would be happy to contribute dev time towards implementing it.

**Comment by phadej** [comment]
This doesn't make sense to me. The set of extensions needed is something everyone would need, wouldn't they, so why you don't use `default-extensions`?

Or is the problem is that you don't want to copy them to each `.cabal` file?

If that is the case, I would recommend using some tool which supports out-of-package includes. E.g. `cabal-fmt` has fragments: https://github.com/phadej/cabal-fmt/blob/master/fixtures/fragment-section.cabal (but unfortunately don't have proper documentation).

The philosophy here is that packages can be independently uploaded to e.g. `Hackage`, that's why `.cabal` files cannot have "out-of-package" includes built-in.

**Comment by akrmn** [comment]
Thanks for the quick response!

> Or is the problem is that you don't want to copy them to each `.cabal` file?

This is exactly the problem, I'd like to have a consistent set of extensions for the packages in my project, and would like to avoid having to go through each `.cabal` file to ensure this. 

> If that is the case, I would recommend using some tool which supports out-of-package includes. E.g. `cabal-fmt` has fragments: https://github.com/phadej/cabal-fmt/blob/master/fixtures/fragment-section.cabal (but unfortunately don't have proper documentation).

that sounds like a good tool for what I need, thank you!

> The philosophy here is that packages can be independently uploaded to e.g. Hackage, that's why .cabal files cannot have "out-of-package" includes built-in.

painfully obvious when you put it that way!
