### ISSUE TITLE
Investigate why GHC-8.8.4 job fails on windows.

### ISSUE THREAD

**Issue by phadej** [haskell/cabal#7145]
8.6.5 job doesn't seem to fail that often at all.

Maybe 8.10.3 would be more stable. Let's add it when it is released, and if it's only 8.8.4 which fails, we can simply remove that job.

**Comment by jneira** [comment]
afaik ghc-8.8.4 was broken in windows and it throwed lot of, sometimes transient, compiler segfaults: https://gitlab.haskell.org/ghc/ghc/-/issues/18496
i've checked it again here: https://github.com/jneira/cabal/runs/5441095315?check_suite_focus=true and it throwed lot of

```
 Access violation in generated code when executing data at 0x208

 Attempting to reconstruct a stack trace...

   Frame	Code address
 * 0x6eddd60	0x208
```

They were fixed in 8.10 so i would simply exclude ghc-8.8 from the workflow
