### ISSUE TITLE
Internal library named like "foo-42" is rejected

### ISSUE THREAD

**Issue by ethercrow** [haskell/cabal#7161]
When I try to `cabal build` this:

```
library advent-of-code-2019
  build-depends: base
  hs-source-dirs: advent-of-code-2019
  exposed-modules:
    AOC_2019_1

executable olympics
    import: common-options
    main-is:          Main.hs
    build-depends:
        base >= 4.14, advent-of-code-2019
    hs-source-dirs: app
    default-language: Haskell2010
```

I get

```
unexpected end of input

   25 |     build-depends:
   26 |         base >= 4.14, advent-of-code-2019
      |                                          ^

```

However, if I change the name of the internal library to `advent-of-code2019` (without the last `-`) it works fine. Is this intentional? I failed to find an answer in the docs.

**Comment by phadej** [comment]
This is intentional. Elsewhere `foo-42` looks like package named `foo` of version `42`. In particular in those (`PackageIdentifier`) contexts, bare `foo` may be interpreted as "package `foo` of any version". Therefore, to avoid possible confusion/ambiguity the all digits package name parts are forbidden.

The syntax of package name is in https://cabal.readthedocs.io/en/3.4/buildinfo-fields-reference.html#non-terminals (the `unqual-name`), though the reasoning is omitted. PRs to make that more clear or/and discoverable via search are welcome.

**Comment by ethercrow** [comment]
I think cabal should say something like "invalid library name" and point to the `library foo-42` line instead of at the usage site inside `build-depends` of another component.

**Comment by phadej** [comment]
@ethercrow good point. Note that `executable foo-42` is fine, but indeed `library` name can be made stricter.
