### ISSUE TITLE
Clarify why cabal-install does not use a freer license

### ISSUE THREAD

**Issue by Franciman** [haskell/cabal#7196]
Hi, I noticed that cabal is a binary that uses the BSD3 license, why did you choose this license? Wouldn't it be better to use some version of GPL or AGPL in order to make this piece of software have copyleft rights for the community? In this way anyone who wants to improve cabal, must give back the code to the whole community. Also, since cabal is an executable, a stronger GPL license would not have any consequence on the software built using it.

**Comment by phadej** [comment]
I sympathize with an idea, but I don't think whether it's good, or would change anything.

I don't know why the BSD-3-Clause was chosen (over a decade ago).

`Cabal` is a library, used e.g. by `ghc-pkg` (part of GHC distribution) and `stack` and importantly `custom-setup` scripts. So I don't see how it can be licensed under non-permissive license. Also code between `Cabal` and `cabal-install` can and does migrate, there are patches changing both at the same time.

Worrying about not polluting permissive `Cabal` with copyleft `cabal-install` originated code, that I think, will harm contribution. Whether `Cabal`-the-library can be changed to use GPL. I *guess*, but you really should ask wider community.

This issue is wrong place to discuss this anyway. Maybe `haskell-cafe` or `hf-discussion` mailing lists.
