### ISSUE TITLE
Please give some way to disable specific cabal warnings...

### ISSUE THREAD

**Issue by ekmett** [haskell/cabal#7286]
... or at least suppress the : in package name and phantom internal version bound ones. 

**Describe the bug**
cabal 3.4 makes it possible (nay, necessary) to use : in some package names.

However, as of 3.4.0.0: this results in a veritable flood of

```
Warning: unlifted.cabal:55:27: colon specifier is experimental feature (issue
#5660)
```

notifications.

Similarly, there appears to be phantom internally made up constraints on any internal library you build:

```
Warning: The package has an extraneous version range for a dependency on an
internal library: unlifted:{core, def, reps} ((>=0 && ==0) && ==0) && ==0,
unlifted:core ((>=0 && ==0) && ==0) && ==0. This version range includes the
current package but isn't needed as the current package's library will always
be used.
```

There's no way to suppress these either. In my current project I get something like 100k worth of build spam output... from just these two warnings alone.

**To Reproduce**

```
git clone https://github.com/ekmett/unlifted.git
cd unlifted
git checkout 09b4b1d037fff2
cabal build
```

with ghc 9.0.1 and cabal 3.4.0.0-rc4 (or rc7)

**Expected behavior**
I'd like to see the actual build messages and real errors.

**System information**
- OSX
- cabal 3.4.0.0-rc4, cabal 3.4.0.0-rc7, cabal 3.4.0.0
- ghc 9.0.1

**Additional information**
I expect to increase the amount of backpack usage in the project 10-fold, which will result in about a megabyte of logs spewed to my screen in the current configuration.

[updated with cabal 3.4.0.0 final release, which didn't change the situation.]

**Comment by ptkato** [comment]
Those warnings seem to be easy enough to suppress, since they're all properly identified within their "warningness" structure. However, I'm not sure how it would impact everything else.

For a quick reference to the involved code: phantom version [here](https://github.com/haskell/cabal/blob/master/Cabal/src/Distribution/PackageDescription/Check.hs#L533), experimental colon [here](https://github.com/haskell/cabal/blob/master/Cabal/src/Distribution/Types/Dependency.hs#L144) and [here](https://github.com/haskell/cabal/blob/master/Cabal/src/Distribution/Types/Mixin.hs#L66).

Taking a look at the code, I do believe it's possible to boost up the `--verbose` flag, without much hassle, to accept not only a range from `0` to `3`, but also specific warning types. But once again, it might have unforeseen consequences. @fgaz, could you give some insights?

**Comment by recursion-ninja** [comment]
@ptkato Any progress on saving my eyes? I've been dealing with the same usability issue as @ekmett for the last two years. 

Is there a roadmap for either:

  1. The "colon specification" and "visibility fields" to stop being experimental?
  2. The warnings related to using these features being suppressible?

**Comment by fgaz** [comment]
> The "colon specification" and "visibility fields" to stop being experimental?

Will happen in 3.8

**Comment by ekmett** [comment]
Great! Looking forward to being able to write Haskell again.
