### ISSUE TITLE
Missing file notification from cabal-install doesn't specify if it's a warning or error.

### ISSUE THREAD

**Issue by AndreasPK** [haskell/cabal#7331]
**Describe the bug**

When running cabal install:
```
$ cabal install
cabal.exe: filepath wildcard 'ChangeLog.md' does not match any files.
```

The output: cabal.exe: filepath wildcard 'ChangeLog.md' does not match any files.
does not give a clear indication if this is an error or an warning. Nor if the executable was installed or not.

**Expected behavior**
Since it seems this prevents installation of the package the string should be prefixed with "error:"

**Comment by AndreasPK** [comment]
This is with cabal-3.4

**Comment by andreasabel** [comment]
I suppose that the minimal fix for this issue is to add "error" somewhere in the error message.

Note that error reporting is in general not in a good state.
E.g. if I remove the `.cabal` file and then try `cabal install`, I get the cryptic (in version 3.6):
```
cabal: Invalid package ID: .
"<eitherParsec>" (line 1, column 2):
unexpected all digits or a dot in a portion of package name
expecting "-"
```
(Maybe the latter should be its own issue.)

Maybe in general, we could insert "error:" after "cabal:".

**Comment by Mikolaj** [comment]
Related older issue: #5820.
