### ISSUE TITLE
Cabal should complain if you give an upperbound on Cabal-Version

### ISSUE THREAD

**Issue by bos** [haskell/cabal#736]
(Imported from [Trac #746](http://hackage.haskell.org/trac/hackage/ticket/746), reported by @igfoo on 2010-10-04)

Some packages (e.g. <tt>NaturalSort-0.2.1</tt>) give an upper-bound on <tt>Cabal-Version</tt>. This doesn't make sense for this field, so Cabal should complain about it (or perhaps even reject it).

**Comment by jsl** [comment]
In commit 520b34812f0177f5d7d9a766a1fcbf0b31931c02 (Cabal 1.10) behavior was changed to ignore upper bounds on cabal-version. There is also a message along the following lines if an invalid range is specified:

```
The following warnings are likely affect your build negatively:
* Packages relying on Cabal 1.10 or later must only specify a version range of
the form 'cabal-version: >= x.y'. Use 'cabal-version: >= 1.10'.

Hackage would reject this package.
```

Since it seems like this has been addressed, I propose we close this issue and re-open a new one if there are other issues related to specifying upper bounds in the cabal-version.
