### ISSUE TITLE
`cabal init --tests`  does not create any tests if not using --lib{andexe}

### ISSUE THREAD

**Issue by kindaro** [haskell/cabal#7410]
**Describe the bug**

`cabal init --tests`  does not create any tests.

**To Reproduce**

```
% cabal init --tests
Warning: The package list for 'hackage.haskell.org' is 23 days old.
Run 'cabal update' to get the latest list of available packages.

Guessing dependencies...

Generating LICENSE...
Warning: unknown license type, you must put a copy in LICENSE yourself.
Generating CHANGELOG.md...
Generating app/Main.hs...
Generating example.cabal...

Warning: no synopsis given. You should edit the .cabal file and add one.
You may want to edit the .cabal file and add a Description field.
% tree
.
├── app
│   └── Main.hs
├── CHANGELOG.md
└── example.cabal

1 directory, 3 files
```

**Expected behavior**

A directory is created with some tests. The tests are wired into `example.cabal` as appropriate.

**System information**

```
% cabal --version
cabal-install version 3.4.0.0
compiled using version 3.4.0.0 of the Cabal library 
% uname
Linux
```

**Comment by fgaz** [comment]
That's because you initialized an executable, and:

```
--tests                        Generate a test suite for the library.
```

`cabal init --libandexe --tests` works. Pheraps `--tests` without `--lib` or `--libandexe` should error out

**Comment by kindaro** [comment]
> This issue is happening because by default cabal initializes a package with only an executable, and there is no way to wire tests directly to an executable without a library in the middle, as far as I can see.

However, observe that you can have a test suite without either a library or an executable, and the default test suite being generated by `cabal init` does not depend in any way on either. Simply run `cabal init --lib --tests` and edit out the library stanza — the test suite still builds and runs!

That is to say, the test suite is not and does not need to be wired to any other stanza.

**Comment by fgaz** [comment]
That is true, but what would such a testsuite test? Answering that myself: other packages in a project, maybe in combination. Or there could be an overlap in the source directories, though I think that's discouraged.

So maybe it would be best to generate the testsuite but also point out in a warning/notice that the user may want to use `--libandexe` to test the code in the same package without rebuilding stuff due to overlapping src-dirs.

/cc @emilypi @ptkato

**Comment by fgaz** [comment]
> and the default test suite being generated by cabal init does not depend in any way on either

this may be another issue. when generating a lib+exe, the exe is made to depend on the lib since that's what one usually wants, so maybe the same should apply to lib+test

**Comment by kindaro** [comment]
My case is such that I needed a package with exactly one `test-suite` stanza. I was having an issue with property checks in a big project, and I wanted to write some small examples separately. That is to say, a feature of generating a standalone test suite would not be without use.

**Comment by emilypi** [comment]
Unless I'm misunderstanding, this was fixed in #7344: 

```bash
λ P temp → λ git master → ../dist-newstyle/build/x86_64-osx/ghc-8.10.4/cabal-install-3.5.0.0/x/cabal/noopt/build/cabal/cabal init --simple --libandexe --tests

Using cabal specification: 3.0

Warning: unknown license type, you must put a copy in LICENSE yourself.
Creating CHANGELOG.md...
Creating file CHANGELOG.md...
Creating directory ./src...
Creating file src/MyLib.hs...
Creating directory ./app...
Creating file app/Main.hs...
Creating directory ./test...
Creating file test/Main.hs...
Creating file temp.cabal...

Warning: no synopsis given. You should edit the .cabal file and add one.
You may want to edit the .cabal file and add a Description field.
λ P temp → λ git master → ls
CHANGELOG.md app          cabal.tix    src          temp.cabal   test
λ P temp → λ git master → tree
.
├── CHANGELOG.md
├── app
│   └── Main.hs
├── cabal.tix
├── src
│   └── MyLib.hs
├── temp.cabal
└── test
    └── Main.hs

3 directories, 6 files
λ P temp → λ git master → 
```

**Comment by emilypi** [comment]
Hmmm. First off, I would not call this a bug @fgaz, since it's explicitly the behavior of the `init` script to disallow creating test suite stanzas without an associated library. Primarily because `init` is for initializing new projects in the sense of libraries or executables. Second, I can see this behavior being legitimate, but it is very non-standard. We'd have to add a flag that explicitly built a test-suite only project, since `--tests`, despite its historical naming convention, only provides a flag for initializing test suites. It doesn't tell the script that it wants to create a test stanza as a _project type_. To get this behavior, we probably want to fold a check for initializing test suites in the package type prompt. 

This is a relatively simple enhancement. It took 5 minutes: 

```
λ P temp → λ git master* → ../dist-newstyle/build/x86_64-osx/ghc-8.10.4/cabal-install-3.5.0.0/x/cabal/noopt/build/cabal/cabal init --simple --tests --minimal

Using cabal specification: 3.0

Warning: unknown license type, you must put a copy in LICENSE yourself.
Creating CHANGELOG.md...
Creating file CHANGELOG.md...
Creating directory ./test...
Creating file test/Main.hs...
Creating file temp.cabal...

Warning: no synopsis given. You should edit the .cabal file and add one.
You may want to edit the .cabal file and add a Description field.
λ P temp → λ git master* → tree
.
├── CHANGELOG.md
├── cabal.tix
├── temp.cabal
└── test
    └── Main.hs

1 directory, 4 files
λ P temp → λ git master* → rm cabal.tix 
λ P temp → λ git master* → tree        
.
├── CHANGELOG.md
├── temp.cabal
└── test
    └── Main.hs

1 directory, 3 files
λ P temp → λ git master* → cat temp.cabal 
cabal-version:   3.0
name:            temp
version:         0.1.0.0
license:         NONE
build-type:      Simple
extra-doc-files: CHANGELOG.md

test-suite temp-test
    default-language: Haskell2010
    type:             exitcode-stdio-1.0
    hs-source-dirs:   test
    main-is:          Main.hs
λ P temp → λ git master* → 
```

**Comment by kindaro** [comment]
Please understand: I use Cabal as a tool to get the job done. Not a guru developer, not an occasional user either. So:

* It is not mine to have opinions as to how command line flags should be interpreted. I cannot account for backwards compatibility, difficulties of implementation, and so on. I only ever used maybe a tenth of all the variety of flags Cabal provides overall in its plethora of sub-commands.
* I can see when a given flag does not make sense — it makes me spend time adding other flags and reading help messages. This waste of time can be justified, say by demands of backwards compatibility, but it cannot be said to be good. It might be a wontfix, but it is still a bug. It being documented, briefly or extensively, does not make it any less a fault.

If you show me the results of _«hallway testing»_ where people figure out to invoke `cabal init --simple --test-suite --minimal` sooner than `cabal init --tests` when they want Cabal to initialize a test suite, I shall be surprized, but I shall accept my experience to be an exception. _(Or re-do the study.)_ But so far I am your _«hallway»_.

I do not mean this as saying that I am somehow special and entitled. If you have other means of measuring the goodness of user experience, please go for it. I am fine with any behaviour as long as it is clear and consistent. All I can say is that, when I type `cabal init --tests` and it gives me an executable, it is neither clear nor consistent. _(Compare with `cabal init --lib` which initializes a library!)_

Cabal already has a myriad of flags that work or do not work depending on their exact combination. Especially since `cabal init` is a convenience feature, it better be convenient!

**Comment by emilypi** [comment]
Ah no I think you misunderstand - I provided a minimal example as a POC for what this workflow might look like if we added `--test-suite` as a flag. It doesn't exist currently, and I'm suggesting we can add it to handle your use case.

**Comment by ptkato** [comment]
I'm fine with whatever option, as long there's an actual use case (which it does have), however I'm inclined towards supporting the first option more than the others.

**Comment by emilypi** [comment]
Okay, so just so spec that option out, here's my problem with 1:

- To say `--tests` it so specify "a package type with a test suite", but not "a package whose package type is 'test suite'". Imagine this scenario: you pass `cabal init --simple --tests`. How do you indicate here that you want a test suite vs. a package type like `--lib` with tests? 
- Having the `--tests` flag set creates an ambiguity of intent: should we enter in the prompt and ask what people want for a package type, or do we take their word for it that they want just tests? This is semantically different than something like `--lib-with-tests` or `--libexe-with-tests`. 
- How do we mark the difference in intent without coming up with a set of flags like `--lib-with-tests` in order to describe that intent? The difference in intent is a dependent type: the behavior of `--tests` depends on the package type. 

So, a solution would go like this: 

1. If package type is defined, `--tests` corresponds with a boolean value that toggles the "initialize test suite" behavior we already have. 
2. If package type is not defined, `--tests` corresponds with the package type. 

And we'd modify the following workflows: 

- **Simple:** we add test suites to lib and lib+exe by default, or we prompt. Then, if `--tests` is supplied, we consider it to be a package type *only*, and do not prompt in that case. Here, the tradeoff is we now always prompt for tests on `--lib` and `--libexe` unless they're passed explicitly. Before we could pass `--tests` and save ourselves a prompt in those workflows.
- **Interactive:** `--tests` corresponds with a test suite package type by default, and we now always prompt for tests on  `--lib` and `--libexe` by default. Before, we could pass `--tests` and save ourselves a prompt. 
- **Non-interactive**: The heuristics will need to cover the inferrance of test-suite only projects. I leave this one to you.

**Comment by ptkato** [comment]
>     * **Non-interactive**: The heuristics will need to cover the inferrance of test-suite only projects. I leave this one to you.

That boils down to assuming defaults and checking the working directory for existing files. I believe with minimal alterations, what already is in place could work great.

**Comment by tonyday567** [comment]
I have to separate tests out all the time as users complain about the extra dependencies that it adds to the package.

How about `--tests-only`?

You won't find it by intuition, but coming across it in the docs, the name would help clarify the usage provisos involved, and listed near --lib, would help distinguish this different use-case.
