### ISSUE TITLE
Cabal init: It is unclear which prompts are optional

### ISSUE THREAD

**Issue by fendor** [haskell/cabal#7464]
**Describe the bug**
When using `cabal init --exe` (but I think that generalises to all fields), it is unclear which prompts are actually optional.

**To Reproduce**
Take this example interaction:
```
> cabal init --exe
Please choose version of the Cabal specification to use:
   1) 1.24  (legacy)
   2) 2.0   (+ support for Backpack, internal sub-libs, '^>=' operator)
   3) 2.2   (+ support for 'common', 'elif', redundant commas, SPDX)
   4) 2.4   (+ support for '**' globbing)
 * 5) 3.0   (+ set notation for ==, common stanzas in ifs, more redundant commas, better pkgconfig-depends)
   6) 3.4   (+ support for 'pkg:sublib' syntax, active repo configuration, rich index-state syntax)
Your choice? [default: 3.0] 
Package name? [default: test-dir] 
Package version? [default: 0.1.0.0] 
Please choose a license:
   1) BSD-2-Clause
   2) BSD-3-Clause
   3) Apache-2.0
   4) MIT
   5) MPL-2.0
   6) ISC
   7) GPL-2.0-only
   8) GPL-3.0-only
   9) LGPL-2.1-only
  10) LGPL-3.0-only
  11) AGPL-3.0-only
  12) GPL-2.0-or-later
  13) GPL-3.0-or-later
  14) LGPL-2.1-or-later
  15) LGPL-3.0-or-later
  16) AGPL-3.0-or-later
  17) Other (specify)
Your choice? 
Empty input is not a valid choice.
Your choice? 4
Author name? 
Maintainer email? 
Project homepage URL? 
Project synopsis? 
Project category:
   1) Codec
   2) Concurrency
   3) Control
   4) Data
   5) Database
   6) Development
   7) Distribution
   8) Game
   9) Graphics
  10) Language
  11) Math
  12) Network
  13) Sound
  14) System
  15) Testing
  16) Text
  17) Web
  18) Other (specify)
Your choice? [default: (none)] 
What is the main module of the executable:
 * 1) Main.hs
   2) Main.lhs
   3) Other (specify)
Your choice? [default: Main.hs] 1
Application directory:
 * 1) app
   2) exe
   3) src-exe
   4) Other (specify)
Your choice? [default: app] 1
Choose a language for your executable:
 * 1) Haskell2010
   2) Haskell98
   3) Other (specify)
Your choice? [default: Haskell2010] 
Add informative comments to each field in the cabal file. (y/n)? [default: y] 

Using cabal specification: 3.0


Creating LICENSE...
Creating file LICENSE...
Creating CHANGELOG.md...
Creating file CHANGELOG.md...
Creating directory ./app...
Creating file app/Main.hs...
Creating file test-dir.cabal...

Warning: no synopsis given. You should edit the .cabal file and add one.
You may want to edit the .cabal file and add a Description field.
``` 

I basically hammered "enter" until once it told me, I couldn't. 
I am unable to tell that the fields 
```
Author name? 
Maintainer email? 
Project homepage URL? 
Project synopsis? 
Project category:
```
are basically optional, but it would be nice if it was.

**Expected behavior**
Communicate to the user which prompts are actually optional

**System information**
 - Arch linux
 - `cabal HEAD`.

**Comment by jneira** [comment]
@fendor oops, we clicked it in sync

**Comment by Mikolaj** [comment]
So what do we do? Add [mandatory] or [optional] (or [not mandatory] to make clear this is a boolean) to each choice that has no default? What about choices with a default, but where empty field is accepted and results in incorrect .cabal file (are there any?)? Can any of this be reflected nicely in types or asserts so that the problem does not crop up in the future?

**Comment by ptkato** [comment]
For what is worth, all prompts which are optional, without default values, receive `String`s. They'll all go through this line:

https://github.com/haskell/cabal/blob/f0d0594bae4f8e3e1ae1bdacef6217a4fc4e136d/cabal-install/src/Distribution/Client/Init/Prompt.hs#L64

However we can't just slap an `" [optional] "` there and call it the day, because it would also affect the license prompt, which is not optional. Now, we have a few options, that is to flesh out this `mkDefPrompt` function a bit more to contextualise it to optional fields, or simply manually append a `"[optional]"` to each optional message individually, which is not really ideal, but affects less code overall.

**Comment by Mikolaj** [comment]
Your call. However, in this rare case I'd nor worry about "affects less code overall", because for the time being you have a mastery of this code and also this general functionality has been rewritten recently, so it's not yet old trusty code on the quirks of which others depend.
