### ISSUE TITLE
Give better error message when GHC/Setup script segfaults

### ISSUE THREAD

**Issue by bos** [haskell/cabal#767]
(Imported from [Trac #777](http://hackage.haskell.org/trac/hackage/ticket/777), reported by philips on 2010-12-12)

I am getting `ExitFailure?` 11 when trying to install hledger on Debian and openSUSE. I reported this to the hledger author, Simon, and he said he is experiencing this on his machines too and for other packages, not just hledger.

Log file attached. Summary below:

<pre class="wiki">ledger:~/ $ cabal install -v3 hledger
Lots of debug output (see attached)...
hledger-0.13 failed during the configure step. The exception was:
ExitFailure 11
ledger:~/ $ cabal --version
cabal-install version 0.8.2
using version 1.8.0.2 of the Cabal library
ledger:~/ $ ghc --version
The Glorious Glasgow Haskell Compilation System, version 6.12.1
</pre>

**Comment by Blaisorblade** [comment]
FWIW, ExitFailure 11 still causes spurious failed builds on Travis, often solved by restarting.

**Comment by ezyang** [comment]
Hey @Blaisorblade, the most reasonable resolution I can think of for this ticket would be to improve the message when the Setup script or GHC segfaults. O/w, there's not much Cabal can do? Would that be sufficient to close this?

**Comment by ezyang** [comment]
I made a simple test case with a segfaulting Setup script:

```
ezyang@sabre:~/Dev/cabal-tmp/cabal-install/tests/IntegrationTests/custom/segfault$ cabal configure
Resolving dependencies...
[1 of 1] Compiling Main             ( dist/setup/setup.hs, dist/setup/Main.o )
Linking ./dist/setup/setup ...
Segmentation fault (core dumped)
ezyang@sabre:~/Dev/cabal-tmp/cabal-install/tests/IntegrationTests/custom/segfault$ cabal install
Resolving dependencies...
cabal: Entering directory '.'
cabal: Leaving directory '.'
Failed to install plain-0.1.0.0
cabal: Error: some packages failed to install:
plain-0.1.0.0-KouPJgq5LZvF2QoUa1N272 failed during the configure step. The
exception was:
ExitFailure (-11)
```

**Comment by Blaisorblade** [comment]
That thing would be good.

The other question is "why compiling correct code sometimes segfaults/produces segfaulting binaries"*. Not 

*Beyond Travis spurious failures, I can witness that incremental compilation produces crashing binaries and that's sometimes fixed by clean recompilation. Can't make a useful bug report though.

**Comment by ezyang** [comment]
Related: https://ghc.haskell.org/trac/ghc/ticket/7229

Also #971. Should be possible to get out the signal info from the process exit info.

**Comment by ezyang** [comment]
@Blaisorblade You don't have any Travis logs of things failing in this way, do you? Could it be an instance of https://ghc.haskell.org/trac/ghc/ticket/10161 (seems unlikely; this only happens if it's ABI compatible)? Do you ever get a core dump in these cases?

**Comment by Blaisorblade** [comment]
@ezyang I'll try sending those logs your way when I get them again, instead of triggering a rebuild and destroying them (I knew that was bad).

> Could it be an instance of https://ghc.haskell.org/trac/ghc/ticket/10161 (seems unlikely; this only happens if it's ABI compatible)?

Sounds unlikely... my assumption is about this happening with ABI incompatibilities. Though maybe you can exploit that bug to get a SIGSEGV with a (correct) `unsafeCoerce`?

The only recompilation problem I could debug is https://ghc.haskell.org/trac/ghc/ticket/12180. (For extra fun, I'm both Blaisorblade and pggiarrusso on Trac).

> Do you ever get a core dump in these cases?

I never had those enabled. I'll try to do that if this happens again.

**Comment by Blaisorblade** [comment]
Actually, https://ghc.haskell.org/trac/ghc/ticket/10296 affects 7.8 and 7.10. Something like that could explain better the segfaults on Travis (since the builds are mostly clean modulo cache).
The recompilation issues are probably a different problem.
