### ISSUE TITLE
Bad errors from getProgramInvocationOutput and friends

### ISSUE THREAD

**Issue by bos** [haskell/cabal#776]
(Imported from [Trac #786](http://hackage.haskell.org/trac/hackage/ticket/786), reported by @igloo on 2011-01-08)

In [http://hackage.haskell.org/trac/ghc/ticket/4883](http://hackage.haskell.org/trac/ghc/ticket/4883) <tt>ghc-cabal</tt> gives an unhelpful error:

<pre class="wiki">ghc-cabal:
</pre>This comes from <tt>getProgramInvocationOutput</tt>:

<pre class="wiki">  (output, errors, exitCode) &lt;- rawSystemStdInOut verbosity
                                  path args
                                  Nothing utf8
  when (exitCode /= ExitSuccess) $
    die errors
</pre>as there was nothing on <tt>stderr</tt>. There are several similar functions in <tt>Cabal</tt>.

Cabal ought to also say what it was running and what the error code was, without needing a verbosity flag to be given.

**Comment by jsl** [comment]
There have been improvements to error messages since this ticket was filed in 2011, including one to the function in question on this ticket from 2014 in b19d2dd3ae9fc2c9084aa4b5b3af03c176e8ba96. Also, a link with more information on the original error is dead.

I propose closing this ticket, and opening a new one with pointers to more specific error reports if this is still an issue. Thoughts?
