### ISSUE TITLE
Regression on master: building hashable-1.3.0.0 fails with `Duplicate modules in benchmark`

### ISSUE THREAD

**Issue by andreasabel** [haskell/cabal#7776]
Current master (e74a53b3d8b1a52cb86a8232e2e745d1bd64a8d7) of cabal-install fails to build `hashable-1.3.0.0`:
```
$ cabal install hashable-1.3.0.0
Resolving dependencies...
Build profile: -w ghc-8.6.5 -O1
In order, the following will be built (use -v for more details):
 - hashable-1.3.0.0 (lib) (requires build)
Configuring library for hashable-1.3.0.0..
Error: cabal: Duplicate modules in benchmark: Data.Hashable.RandomSource

Error: cabal: Failed to build hashable-1.3.0.0. The failure occurred during
the configure step.

$ cabal --version
cabal-install version 3.7
compiled using version 3.7.0.0 of the Cabal library 
```

Build succeeds with version 3.6:
```
$ cabal-3.6 install -w ghc-8.10.7 hashable-1.3.0.0
...
Installing library in /Users/abel/.cabal/store/ghc-8.10.7/incoming/new-49369/Users/abel/.cabal/store/ghc-8.10.7/hshbl-1.3.0.0-02ec191e/lib

$ cabal-3.6 --version
cabal-install version 3.6.0.0
compiled using version 3.6.1.0 of the Cabal library 
```

Build also succeeds with `Setup.hs`:
```
$ cabal get hashable-1.3.0.0
$ cd hashable-1.3.0.0
$ runhaskell Setup.hs configure
$ runhaskell Setup.hs build
```
(However, `runhaskell Setup.hs configure --enable-benchmarks` does not succeed to construct a build plan.)

This is the content of the `cabal.project.local` file:
```
$ cat cabal.project.local 
ignore-project: False
benchmarks: True
```

**Comment by gbaz** [comment]
Hrm, on reflection I'm surprised this stuff was working before, as I thought the patch in question made the checks strictly less strong.

I guess it strengthened some things and rendered others weaker. As such, yeah, I agree there's a problem here. If someone can explain how cabal's prior checks ever accepted examples such as above I'd appreciate it -- it seems to me that `flattenPackageDescription` should necessarily have created duplicate modules in such cases: https://downloads.haskell.org/~ghc/latest/docs/html/libraries/Cabal-3.6.0.0/Distribution-PackageDescription-Configuration.html#v:flattenPackageDescription

Perhaps the semigroup combination of package lists is sort of funny?

Either way, I think I can just change this check so that it runs an optimistic check with an error and a pessimistic check with a warning, without intensely more work, and I'll try to get on that.

**Comment by Mikolaj** [comment]
I think we do have an agreement here to be obnoxious when warning, but lax when erroring out.

So it's just the matter of implementing it.
