### ISSUE TITLE
Test 'Check dependenciesHeuristics output` fails locally

### ISSUE THREAD

**Issue by Mikolaj** [haskell/cabal#7785]
**Describe the bug**

When running `cabal test cabal-install:unit-tests` locally, I'm getting a single failure:

            Check dependenciesHeuristics output
              base version bounds is correct:                                                    FAIL
                tests/UnitTests/Distribution/Client/Init/NonInteractive.hs:1221:
                expected: OrLaterVersion (mkVersion [0])
                 but got: MajorBoundVersion (mkVersion [4,14,3,0])
                Use -p '/base version bounds is correct/' to rerun this test only.

I'm worried that it fails and also that CI does not fail similarly (is this test run on CI?).

**To Reproduce**

`cabal test cabal-install:unit-tests` on fresh repo.

**Expected behavior**

All tests pass.

**System information**

Ubuntu, GHC 8.10.7, cabal from master branch.

**Additional context**

Initially reported by @tomjaguarpaw at #7080.

**Comment by ptkato** [comment]
That has to do with how the test is composed:

https://github.com/haskell/cabal/blob/8760e3d32939c0e7f813c56cdf56709d43e9cf22/cabal-install/tests/UnitTests/Distribution/Client/Init/NonInteractive.hs#L1173-L1183

https://github.com/haskell/cabal/blob/8760e3d32939c0e7f813c56cdf56709d43e9cf22/cabal-install/tests/UnitTests/Distribution/Client/Init/Utils.hs#L53-L60

When I fashioned this solution, I was very aware that it would bite me in the arse later on. Since the ghc version is not the same as the base version, I took the most straightforward approach: ad-hoc galore. Any run that is done using a ghc version outside of what is defined in `baseVersion'` will fail. It's pretty much a moving target.

Now, we have 3 options: find a right way to approach that, keep updating that function every time a new ghc release comes out, or drop that test entirely.

**Comment by Mikolaj** [comment]
This actively confused a new user of the test suite (a PR contributor that I molested to add tests), so I think we should fix it. Can't the existing machinery that processes test logs blotting out paths, etc. be used here? In the worst case, can we check that the GHC version matches the expectation and *not* run the test otherwise?
