### ISSUE TITLE
world-file in cabal config shouldn't warn

### ISSUE THREAD

**Issue by gbaz** [haskell/cabal#7894]
As discussed in https://github.com/haskell/cabal/pull/7746 we ripped out world files but people still will have old configs that mention them and we shouldn't warn on those parse problems.

**Comment by fgaz** [comment]
I think it shouldn't stay silent either. Maybe it should issue a deprecation warning

**Comment by ptkato** [comment]
What would that entail? Because as of now it seems that the parser has no notion of deprecation, it simply throws that warning when it doesn't recognises a field, it's quite generic. It could be as easy as simply adding a condition to plaster a `"Deprecated"` in the warning message when necessary, but that's very ad-hoc; on the other hand it would be nice to have an actual structure to handle such cases properly.

**Comment by gbaz** [comment]
See discussion in the other ticket -- also, again, a _ton_ of people will both have this field in their config file, and never in their life have touched their config file. Warning all of them by default will be confusing to them, and serve no purpose.

**Comment by ptkato** [comment]
I tend to agree with you, and could this even be considered a deprecation? The field was wholly removed.
