### ISSUE TITLE
--package-db clear does not seem to work

### ISSUE THREAD

**Issue by farao** [haskell/cabal#7926]
**Description**
I would like to run cabal only from a user defined package database and ignore the `global` (as I understood systemwide) and `local` (as I understood ~/.cabal) ones.

First, I would expect `cabal v2-build --package-db=clear` not to build at all (because of missing dependencies) and (second) `mkdir database; cabal v2-build --package-db=clear --package-db=database/` to download the missing dependencies to the database/ directory.

Unfortunately, in both cases, cabal downloads the missing dependencies to `~/.cabal`. Is my understanding of the `--package-db` option wrong or does it simply not work?

**System information**
 - Fedora Linux 35
 - cabal 3.6.0.0, ghc 8.10.5

**Comment by Mikolaj** [comment]
Hi! Package database is a GHC concept that v2 barely uses (v1 used it for the lack of something better). What is it exactly that you'd like to accomplish? Why is standard workflow not sufficient for your use case? Could you let us know the documentation that led you to this workflow so that we can perhaps fix anything that is misleading?

**Comment by farao** [comment]
Thanks for the quick answer.

My use case: I want (if possible) to develop my cabal project on my (and other) developer machines and then push it to a local server that has no internet connection but needs to build the project.

Thus, my idea was to create a "local package database" in a directory, check the directory into git and push the whole project including the local database to that (local) server, so that it has all dependencies that it needs to build.

The documentation which led me to this is simply the documentation of `--package-db` in `cabal v2-build --help` which sounded as if this is the function to accomplish it.

**Comment by Mikolaj** [comment]
Thank you for the details. Indeed, some old flags don't quite work with v2 commands and the documentation about that is not up to date. There are already tickets about that, I think. 

I have no idea if you can make it work the way you do, perhaps using v1 while it's still (sort of) working and is not removed. Anybody? The tricky part may be the distinction between a db of compiled library object files and a db of package source tarballs. These are different things and GHC package db is more of the former kind (I guess, plus some metadata?).

I know people accomplish something like that from another end, by building a Hackage or Stackage mirror on a machine the server can connect to and then using cabal as usual. Perhaps there are better ways.

Another way might be via freeze files and caches of packages downloaded based on a freeze file. I don't remember how it's done, right now, and it has improved since I did it years ago.

Please note down in this issue (regardless if you close it or not) what worked for you so that people searching the issue tracker may find a solution. If the experience shows something in cabal can be improved, please let us know as well.

**Comment by fgaz** [comment]
We are about to add `--package-db` to `cabal-install`: #7676

Still, I think what you want to do could be better accomplished by copying the _sources_ of the dependencies and building it all on the target machine. You could do that with by running `cabal fetch` or `cabal build --only-download` and copying just `~/.cabal/packages`.

Another approach is to use `cabal get` to get all the dependencies, then either set up a [file+noindex](https://cabal.readthedocs.io/en/3.6/installing-packages.html#local-no-index-repositories) repository or put them all in `cabal.project` under `packages:`.

**Comment by jneira** [comment]
@farao given there is an issue about adding that option and some way to get your final goal I think we could close this one, feel free to reopen or post any question here, thanks!
