### ISSUE TITLE
`cabal init` should include `build-type: Simple` in the generated `.cabal` file

### ISSUE THREAD

**Issue by andreasabel** [haskell/cabal#7947]
Atm, I cannot `cabal run` the default executable generated by `cabal init`, as the field `build-type` is not initialized.
The error I get on `cabal run` could be a bit cryptic for newcomers:
```
Errors encountered when parsing cabal file ./foo-bar.cabal:

foo-bar.cabal:0:0: error:
Since cabal-version: 1.24 specifying custom-setup section is mandatory
```
This is actually not even true, `build-type: Simple` does the job as well.

ATTN @ptkato

**Comment by fgaz** [comment]
Didn't we just add a test that checks that a cabal-inited package is buildable? Why didn't it fail?

**Comment by phadej** [comment]
This is "the same" bug as #7942 and #7946, as `build-type` is `Simple` by default since `cabal-version: 2.2` https://cabal.readthedocs.io/en/3.6/file-format-changelog.html#cabal-version-2-2

**Comment by ptkato** [comment]
Hello, do you have a reproducible example? As in the commands you used to get to that error.

**Comment by ptkato** [comment]
@fgaz, the test is only checking for the default values in non-interactive mode, I shall expand upon that; now, the problem seems to be that for `cabal-version < 2.2`, we default to nothing, and `checkForUndefinedCustomSetup` ends up throwing that error.

https://github.com/haskell/cabal/blob/96940364e800a9c86f1936d4878c6296e3071789/cabal-install/src/Distribution/Client/Init/Format.hs#L362-L364

@emilypi, do you recall why we ended up doing that for `build-type`?

**Comment by phadej** [comment]
> @fgaz, the test is only checking for the default values in non-interactive mode, I shall expand upon that; now, the problem seems to be that for `cabal-version < 2.2`, we default to nothing, and `checkForUndefinedCustomSetup` ends up throwing that error.
> 
> https://github.com/haskell/cabal/blob/96940364e800a9c86f1936d4878c6296e3071789/cabal-install/src/Distribution/Client/Init/Format.hs#L362-L364
> 
> @emilypi, do you recall why we ended up doing that for `build-type`?

That conditional seems to be wrong way around.
