### ISSUE TITLE
Support transformers-0.6 and mtl-2.3

### ISSUE THREAD

**Issue by phadej** [haskell/cabal#8144]
Looks like that relaxing bounds is enough.

**Comment by Mikolaj** [comment]
Actually, to have (full) effect, this requires a bump in hackage-security and a release or revision of it: https://github.com/haskell/hackage-security/issues/272

**Comment by Mikolaj** [comment]
That seems to be the case for cabal-install, but in CI it affects all, because they are built together, so old versions are forced, because cabal-install depends on hackage-security that depends on old transformers and mtl. Oh well.

**Comment by phadej** [comment]
that what e.g. https://github.com/haskell/cabal/blob/48bf10787e27364730dd37a42b603cee8d6af7ee/cabal-dev-scripts/src/GenValidate.hs#L31 job did, similar lib-only jobs were used for most recent GHC at the time too.

Implementation wise it was to run a subset of `validate.sh` steps, so shouldn't be difficult to (re)implement if it gone missing.

**Comment by andreabedini** [comment]
We can, see https://github.com/haskell/cabal/pull/8151

**Comment by Bodigrim** [comment]
@Mikolaj what are the next steps here? Unless `Cabal` package allows `transformers-0.6`, the latter cannot be bundled as a GHC boot library, so almost everyone is tied to `transformers-0.5`, which is a shame, because `transformers-0.6` has been around since July 2021.

At this point we do not really care about `cabal-install` or `hackage-security`, they may stick to older infrastructure for a while. But to bump a GHC submodule all boot libraries must be compatible with each other, and I believe `Cabal` is the last blocker for this to happen.

**Comment by Mikolaj** [comment]
@Bodigrim: current master branch is fine, right? So it's the matter of including it in GHC? I have no problem with including today's snapshot in GHC, for now, but the final version for GHC 9.6 is tracked at https://github.com/haskell/cabal/issues/8571.

**Comment by Mikolaj** [comment]
Oh, I see, master branch is fine after we merge https://github.com/haskell/cabal/pull/8610.

Still. Is that all or may I help further?
