### ISSUE TITLE
Cabal check incorrectly assumes package has -Wall -Werror

### ISSUE THREAD

**Issue by turion** [haskell/cabal#8257]
**Describe the bug**

In some cases (I believe when `ghc-options: -Werror` is given), `cabal check` reports a warning about `'ghc-options: -Wall -Werror'`, although `-Wall` is not set. This makes it, for example, impossible to upload such a package to hackage (see https://github.com/haskell/hackage-server/issues/1088).

**To Reproduce**

```
$ mkdir tmp
$ cd tmp
$ cabal init
$ echo "    ghc-options: -W -Werror" >> tmp.cabal
$ cabal check
Warning: These warnings may cause trouble when distributing the package:
Warning: No 'category' field.
Warning: The following errors will cause portability problems on other
environments:
Warning: No 'synopsis' or 'description' field.
Warning: The 'license' field is missing or is NONE.
Warning: 'ghc-options: -Wall -Werror' makes the package very easy to break
with future GHC versions because new GHC versions often add new warnings. Use
just 'ghc-options: -Wall' instead. Alternatively, if you want to use this,
make it conditional based on a Cabal configuration flag (with 'manual: True'
and 'default: False') and enable that flag during development.
Warning: Hackage would reject this package.
```

Let us disregard the warnings about the missing fields, those are fine. I'm worried about `Warning: 'ghc-options: -Wall -Werror' makes the package very easy to break [...]`.

**Expected behavior**

Either no warning, or a correct warning message (e.g. warning about `-Werror` together with any enabled warning flag). I think it's fairer to have no warning here. `-W -Werror` is less likely to break in future GHC versions than `-Wall -Werror`, and should be allowed. (Maybe even good practice.)

**System information**
 - Operating system: NixOS unstable
```
$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 9.0.2

$ cabal --version
cabal-install version 3.6.2.0
compiled using version 3.6.3.0 of the Cabal library 
```

**Comment by gbaz** [comment]
The text can be improved, but we should not change behavior: this is as intended. See: https://github.com/haskell/cabal/blob/dd0523beaec1be57baa4446f342da0e4b80f823e/Cabal/src/Distribution/PackageDescription/Check.hs#L1577

In fact, packages with `-Werror` are treated this way even without `-W` or `-Wall` on (if you look at subsequent lines.

The logic is that -Werror is a flag for developers, not end users. If a developer uploads a package, it should be in a condition that they are comfortable with. Later requiring that users also compile it warning free doesn't make much sense -- the developer already resolved all the warnings they wanted. The only way new warnings could emerge is with new ghc versions, and this would simply mean that packages that used to work ceased working, because ghc got better at providing information.

**Comment by turion** [comment]
I see.

https://github.com/haskell/cabal/blob/dd0523beaec1be57baa4446f342da0e4b80f823e/Cabal/src/Distribution/PackageDescription/Check.hs#L1630

Probably this is also slightly confusing naming.

Also, the warning message for `-Werror` is very similar to the one for `-Werror -W`. Maybe it makes sense to collapse both into a single warning message triggering on `-Werror`?

**Comment by ffaf1** [comment]
Indeed similar, the difference seems in «easy to break» vs «very easy to break».

If noone comes up with a good reason to keep them distinct, I will update my PR.
