### ISSUE TITLE
Should cabal-install use text-2.0?

### ISSUE THREAD

**Issue by ulysses4ever** [haskell/cabal#8377]
The question [comes from Reddit](https://www.reddit.com/r/haskell/comments/wm656h/just_released_cabal_3810/ik97kj4). Perhaps it may bring some benefit? Even if only in terms of popularizing text-2.0...

**Comment by avanov** [comment]
It saves Nix build times if my dependency graphs do not have to depend on two versions of `text` whenever I want to try out new GHC versions (for which I need to compile most of the packages locally)

**Comment by Bodigrim** [comment]
`cabal-install` does not really use `Text` much, it can certainly relax `text` bounds.

**Comment by Mikolaj** [comment]
We have

    text         (>= 1.2.3.0  && < 1.3) || (>= 2.0 && < 2.1),

in Cabal.cabal on branch master, so it's probably only cabal-install.cabal that is excluding text 2 and probably for no good reason.

**Comment by andreasabel** [comment]
I relaxed to `text-2.0` locally, but it is not picked up by the constraint solver.  AFICT, it is because we depend on `Cabal-3.6`: https://github.com/haskell/cabal/blob/a97e1f13bdb28a3f761d55845f14a9072bee17ca/cabal-testsuite/cabal-testsuite.cabal#L112-L117
Forcing it with `-c text >= 2.0` it is used in most places, though, `cabal-plan` then only shows usage of `text-1.2.5.0` for `Cabal-3.6.3.0` then.
