### ISSUE TITLE
Cabal-3.6.3.0 isn't listed under https://downloads.haskell.org/~cabal/

### ISSUE THREAD

**Issue by andreasabel** [haskell/cabal#8380]
Cabal-3.6.3.0 isn't listed under https://downloads.haskell.org/~cabal/, is this intended?

**Comment by Mikolaj** [comment]
I don't think so. Looks like an oversight. The links from https://www.haskell.org/cabal/download.html go to Hackage directly, but it doesn't work for 3.8.1.0, where the link destination should also include Cabal-syntax, which is a related error. Similarly cabal-install tool source download should point to a directory due to cabal-install-solver source archive.

**Comment by Mikolaj** [comment]
The original issue is fixed and a follow-up PR is at https://github.com/haskell/cabal-website/pull/35
