### ISSUE TITLE
--cabal-file needs to go

### ISSUE THREAD

**Issue by ulysses4ever** [haskell/cabal#8395]
As discussed in #6880, `--cabal-file` has never been used for what people think it's meant. The best way forward, seemingly, is to remove the option (edit by @fgaz: from cabal-install). This follows up on not only #6880 but also #7225.

## Alternatives

Different people want different things from `--cabal-file`, e.g.:

1. Call `cabal` out of the package directory (#7940).
2. Call `cabal` inside of the package directory but with a cabal file located outside of the directory (#6880, #7225).

The second scenario is not supported currently. The first one can be worked around with another option: `--project-file`. In particular, you can create a project file along with the package of interest (if there's none currently), and point to it calling `cabal` from anywhere. In that case the respective package will be built/ran/installed. Beware of a current bug not allowing to use relative paths with `--project-file`: use absolute path until #7749 (or analogous fix) is merged.

**Comment by andreasabel** [comment]
Yes, option `--cabal-file` should be replaced by a `--cwd` / `--directory` option as suggested in:
- #8037

Alternatively, it could be fixed to mean these two things (conjunction):
1. Set the project root to the location of the given `--cabal-file`.
2. Disambiguate in case there are several `.cabal` files in this directory.

**Comment by fgaz** [comment]
-1 to giving it some other behaviour, +1 to removing it.

if an option to select a cabal file is needed, we could make [`packages`](https://cabal.readthedocs.io/en/stable/cabal-project.html#cfg-field-packages) a valid cli option.

**Comment by andreasabel** [comment]
I played a bit with removing the option.  It seems to be used in the testsuite.  So most work in removing this option would go into restructuring the test that currently use it.
E.g. here are several `.cabal` files in the same directory, and selected using the `--cabal-file` option: https://github.com/haskell/cabal/tree/a97e1f13bdb28a3f761d55845f14a9072bee17ca/cabal-testsuite/PackageTests/ReexportedModules/p

**Comment by fgaz** [comment]
Those look like Setup.hs tests though, so removing the option from `cabal-install` should be fine

**Comment by andreabedini** [comment]
I had a go myself [here](https://github.com/andreabedini/cabal/tree/remove-cabal-file). I am a bit confused (not new :joy:). The option `--cabal-file` is (originally) a Cabal option. The options of Cabal and cabal-install (both v1 and v2 commands) are all jumbled up and this is how it becomes a cabal-install option.

Do we want to remove it from Cabal or only from cabal-install?

AFAIU we do have a [mechanism](https://github.com/haskell/cabal/blob/d89526f9818bf8969f4a774738ea187a0ae301cd/cabal-install/src/Distribution/Client/NixStyleOptions.hs#L60-L70) to hide some Cabal flags when we use them from cabal-install. But that's also a bit messed up because it's duplicated in a [few](https://github.com/haskell/cabal/blob/d89526f9818bf8969f4a774738ea187a0ae301cd/cabal-install/src/Distribution/Client/Setup.hs#L852-L857) [places](https://github.com/haskell/cabal/blob/d89526f9818bf8969f4a774738ea187a0ae301cd/cabal-install/src/Distribution/Client/Config.hs#L1140-L1141) and doesn't really inspire confidence.

Also Cabal's cabalFilePath gets passed to what I understand is the Hooks API (haddockCabalFilePath, hscolourCabalFilePath, copyCabalFilePath, installCabalFilePath, regCabalFilePath, cleanCabalFilePath, ...) and there's some warning in the code about breaking that API.

**Comment by fgaz** [comment]
From cabal-install. Yes I think we can just hide it

**Comment by Mikolaj** [comment]
The ticket got closed via the excellent PR by @andreabedini. Is there anything left here to do? If so, maybe let's move it to other tickets with clear scopes?
