### ISSUE TITLE
rtd: text on images is unhelpful

### ISSUE THREAD

**Issue by ulysses4ever** [haskell/cabal#8453]
I reach to [Test Suite Fields docs](https://cabal.readthedocs.io/en/latest/buildinfo-fields-reference.html#test-suite-fields) and see:
![2022-09-04_20-09-1662339042](https://user-images.githubusercontent.com/6832600/188340705-f840766f-681d-4ece-8115-0709a58b0f44.png)
I'd really love to copy and paste the exitcode stuff but I can't because it's a picture. Generally this page seems to overuse images. I propose we put copy-pasteable bits (words) in plain text, if possible.

**Comment by Mikolaj** [comment]
I agree, even at the cost of making it less beautiful.

**Comment by kukimik** [comment]
FWIW, when I right-click on the image, a context menu shows up, which allows me to use another renderer instead of SVG. If I choose one of the HTML renderers, I can select and copy the text. (I'm using Firefox.)

![image](https://github.com/haskell/cabal/assets/53443372/b520af00-3fd2-41e2-8e67-a0b798faa129)

**Comment by kukimik** [comment]
This the line responsible for setting the SVG renderer as the default:

https://github.com/haskell/cabal/blob/a260cde00be9d0febd24dae958f7b45484249107/doc/conf.py#L106

But it would be good to understand why the line was added (see https://github.com/haskell/cabal/commit/90b14ae63d49e62b8fff4b686a47685068aacad8), for which I don't have the time.

**Comment by ulysses4ever** [comment]
@kukimik thanks for investigating! I think we should try it: 
- #9361
