### ISSUE TITLE
Should existence of $XDG_CONFIG_HOME/cabal/config override existence of $HOME/.cabal?

### ISSUE THREAD

**Issue by athas** [haskell/cabal#8577]
Somewhere in #7386 it was brought up that the current backwards compatibility mode, where the mere presence of a `~/.cabal` directory disables the XDG behaviour, is fragile because older tools may accidentally create this directory, which will cause subsequence `cabal` invocations to change their behaviour.  It was suggested to add another wrinkle:

* If `$XDG_CONFIG_HOME/cabal/config` exists, then XDG behaviour is enabled (and this config file used), regardless of whether `~/.cabal` (and `~/.cabal/config`) exists.

The idea here is that it is unlikely for `$XDG_CONFIG_HOME/cabal/config` to be created accidentally, while `~/.cabal` can more easily be created accidentally by older tools that are not aware of the XDG behaviour.

Opinions?  It would not be particularly difficult to implement; just another case in the existing compatibility functions.

**Comment by athas** [comment]
`CABAL_DIR` should always overrule anything, as that's never going to be set by accident.

I think it is is unlikely that new tools will create a cabal config file (why should they?) the way older tools might create a `~/.cabal` directory to put something *else* in there (or maybe just by accident when they're looking for something in there).

**Comment by mouse07410** [comment]
> `CABAL_DIR` should always overrule anything, as that's never going to be set by accident.

Thank you!

> I think it is is unlikely that new tools will create a cabal config file (why should they?) the way older tools might create a `~/.cabal` directory to put something else in there

I say - if there are tools on the system that insist on using the old convention, then you ought to honor it as well. Otherwise - I worker want to be the one who had to untangle the mess of done stuff going to the old and some - to the new...

> or maybe just by accident when they're looking for something in there

Impossible. Looking fur something (as opposed to _creating_ something _new_) in a non-existing directory always returns an error, and does not create a directory. What have you the reason to assume otherwise???

**Comment by Mikolaj** [comment]
Perhaps let's just see how it's used in the wild and what the user-reported real use cases and pitfalls are. If users are motivated enough to report them, I think it's worth fixing according to their report.

**Comment by andreasabel** [comment]
> Perhaps let's just see how it's used in the wild and what the user-reported real use cases and pitfalls are.

Now we have some:
- https://github.com/haskell/actions/issues/210
- #8855

**Comment by ulysses4ever** [comment]
One issue popped up because the idea presented in this thread wasn't implemented in 3.10: 

- https://github.com/haskell/actions/issues/203

This is now featured in the [release announcement thread](https://discourse.haskell.org/t/just-released-cabal-3-10-1-0/5978/3).

On the last cabal meeting this week, people seemed to agree that:

1. Implementing this idea in 3.10.2.0 is desirable.
2. If two cabal directories are found, cabal should issue a **warning** describing the situation, and making suggestion to the user to remove either of directories manually and do `cabal update` manually.

@athas would you be interested in working on this?

**Comment by athas** [comment]
Sure, I can take a shot at it.  The (2) warning cannot be specific to `cabal update`, though, since the code looking for the directory is generic.

Incidentally, my own protection from this issue is to create a `~/.cabal` *file*, which new `cabal`s will ignore but will cause old `cabal`s to crash.  This is less viable in CI setups though, where it seems the issue is most common.

**Comment by ulysses4ever** [comment]
>  The (2) warning cannot be specific to cabal update

It doesn't have to be, I think. I think it's fine for every command to complain about it because it's an undesirable state of things.

As for workarounds: several has been proposed but the idea of this approach is that it should work more reliably for people who don't necessarily understand the problem and are not aware of any workarounds.

**Comment by mouse07410** [comment]
@ulysses4ever I support your idea.

**Comment by Mikolaj** [comment]
I will take any reasonable solution as long as it's quick, so that we can release 3.10.2.0 soon.

**Comment by athas** [comment]
I am not in favour of hiding XDG behaviour behind an environment variable.  It would be a mess if every program required that.

**Comment by hasufell** [comment]
> I am not in favour of hiding XDG behaviour behind an environment variable.  It would be a mess if every program required that.

GHCup does, stack does.

XDG is already a mess. It took a couple of decades to support binary directory and now it's defined without a way to change it, breaking configurability, which was the entire point of XDG.

I don't see a good argument why we should disrupt CI systems or the majority of users who don't care about XDG.

It will never be consistently supported by all tools anyway. And it has serious drawbacks too (sharing of bindir is one).

**Comment by athas** [comment]
Why is it that XDG support disrupts CI systems?  I can see that caches built for pre-XDG cabal may interact poorly with XDG cabal, but that sounds like an issue that will resolve itself quickly, as CI caches don't tend to live that long.

Normal users will probably not be disrupted much.  The only case I can think of where confusion occurs if if you do a `cabal update` with XDG-cabal, then copy in an older/stale/incomplete `~/.cabal` from somewhere else.  This can happen in CI systems, but I find it unlikely outside of them.  Some users may be confused not to find a `~/.cabal` at all, of course.

**Comment by mouse07410** [comment]
+1 to Julian.

If env car is set - it becomes the ultimate authority. 

And in general, the one thing we should want to avoid is ambiguity.

**Comment by athas** [comment]
We already have one of those: if `CABAL_DIR` is set, it is the ultimate authority.

**Comment by hasufell** [comment]
> We already have one of those: if `CABAL_DIR` is set, it is the ultimate authority.

Sure. I can make ghcup set it by default to avoid some of the fallout.

**Comment by Mikolaj** [comment]
@hasufell: I'm in favour, regardless of whether it's a good default long term, because here we have a short term emergency and no resources to handle it the way it should be handled (e.g., communicate with all CI, devenv and tool maintainers and test with all passively maintained tools ourselves and fix as needed).

**Comment by Mikolaj** [comment]
The PR is now merged and backported. Shall we close the ticket?

**Comment by ulysses4ever** [comment]
Indeed. Excited to see how it pans out in practice!

**Comment by hasufell** [comment]
> Why is it that XDG support disrupts CI systems?

https://github.com/haskell-actions/setup/issues/62
