### ISSUE TITLE
PVP major version bump guideline

### ISSUE THREAD

**Issue by ju1m** [haskell/cabal#8652]
The [decision tree of the Haskell Package Versioning Policy](https://pvp.haskell.org/#decision-tree) states this guideline:
![image](https://user-images.githubusercontent.com/21160136/210187376-c980d7f9-6fdf-48ab-a207-5f79db3d3322.png)
Which neither resets C to zero (or empty) when incrementing B, nor resets B and C to zero when incrementing A. It likely should to be what's generally expected.

Besides, I can't find a guideline about whether one should increment A or B.
A [possible guideline](https://mastodon.online/@nomeata/109615086838999261) could be:
- when B increments: “there is a breaking change, but if it still compiles, it's probably fine”
- when A increments: “there is a semantic change, please do read the changelog”

Thanks.

**Comment by gbaz** [comment]
the former is in an update to the pvp, but a new version has not been published: https://github.com/haskell/pvp/issues/31

The latter is purposefully unspecified, because it is not a uniform convention. I'm going to close because further discussion on this or any related issue should be in the pvp repo (which is e.g. where the above issue lives).
