### ISSUE TITLE
Coming to a decision regarding the short to medium-term future of `cabal format`

### ISSUE THREAD

**Issue by Kleidukos** [haskell/cabal#8797]
https://github.com/haskell/cabal/issues/5734 is still relevant in cabal-install 3.9.0.0 and this is a rather shameful footgun. There are today alternatives to it, like [@phadej/cabal-fmt](https://github.com/phadej/cabal-fmt), which performs much better.

In parallel, we do not even show `format` in the `cabal --help` message. 

I would like us to take a decision regarding what we make of the `format` option.

@phadej Although I understand that the "goal of [this] project is to iterate independently of cabal-install"[¹], would you say that it has reached suitable maturity for integration? I use the auto-expander syntax these days and I'm satisfied of how it works.

Personally I'd like see cabal-fmt as a new code path for `cabal format`. This can be advertised as being experimental, but in the end a clear improvement for the users.

[¹]: http://oleg.fi/gists/posts/2019-08-11-cabal-fmt.html#conclusion

**Comment by Kleidukos** [comment]
Upon seeing the command used by an innocent victim, I think we have to change a couple of things about its presentation.

From off-site:

> hahaha what the actual fuck, TIL that `cabal format` expands out `common` stanzas
> and also whatever "standard style" the command help says it uses, it's objectively bad

Clearly we violate a number of principles with this command, including the principle of least surprise.
I'll open a PR to better manage the expectations of the users and remove references to non-existent standards.

**Comment by fendor** [comment]
It seems the "standard style" is more like a pretty-printed normalised form of a cabal file.
It even eats comments in the sources (which is not surprising, since we don't have an exactprinter or anything).

In my opinion, `cabal format` should be re-branded as not being a formatter but an internal tool for uniformly presenting cabal files, maybe for tooling, or something like that. Not for human developers trying to prettify their .cabal or cabal.project files.

However, I am uncertain if we should have a formatting tool shipping with .cabal at all. I don't think other tools do that (although admittedly, most other langs I know have no custom formats for package specification), and it'd be much better to spend time on a potential exactprinter, such as https://github.com/haskell/cabal/pull/7626. This would foster friendly competition between multiple formatting libs with different design goals (minimal diffs vs vertical alignment, etc...). Similar to the haskell formatters that are out there already.
Additionally, exactprinter would be great for [HLS's cabal plugin](https://github.com/haskell/haskell-language-server/pull/2954) ;)

**Comment by gbaz** [comment]
The `format` command is not listed in `cabal --help` nor in the cabal readthedocs precisely because it isn't in great shape given the lack of an exactprint or the like. The one thing that could be done simply is changing the `cabal format --help` message itself to indicate it is an experimental or partially implemented command. But outside of that, it isn't advertised anywhere as something for people to use.
