### ISSUE TITLE
Cabal haddock can't find documentation for basic libraries

### ISSUE THREAD

**Issue by Lev135** [haskell/cabal#9022]
**Describe the bug**
I'm trying to build haddock for my lib. I've added `documentation: True` to my cabal config file and run `cabal install --reinstall`. Most of the packages has been reinstalled except basic ones. And than, while running `cabal haddock` it can not find documentation for these packages:
```
Build profile: -w ghc-9.2.7 -O1
In order, the following will be built (use -v for more details):
 - monadic-lens-0.1.0.0 (lib) (configuration changed)
Configuring library for monadic-lens-0.1.0.0..
Preprocessing library for monadic-lens-0.1.0.0..
Running Haddock on library for monadic-lens-0.1.0.0..
Warning: The documentation for the following packages are not installed. No
links will be generated to these packages: array-0.5.4.0, base-4.16.4.0,
binary-0.8.9.0, bytestring-0.11.4.0, containers-0.6.5.1, deepseq-1.4.6.1,
exceptions-0.10.4, filepath-1.4.2.2, ghc-bignum-1.2, ghc-boot-th-9.2.7,
ghc-prim-0.8.0, mtl-2.2.2, pretty-1.1.3.6, stm-2.5.0.2,
template-haskell-2.18.0.0, text-1.2.5.0, transformers-0.5.6.2
```
I've opened cabal store directory and don't see any of these libraries there. It seems like it reuses them from ghcup, but can't find the documentation for them (while it exist in ghcup directory).

**To Reproduce**

I don't actually know, what to specify here, except that I've already written above

**Expected behavior**

I'd like the docs with links for types and functions from basic libraries to be generated, like for all others.

**System information**
 - Operating system: Windows
  - `cabal`, `ghc` versions
cabal-install version 3.8.1.0
compiled using version 3.8.1.0 of the Cabal library 
The GHCup Haskell installer, version 0.1.19.2
ghc-9.2.7
**Additional context**

**Comment by mpilgrem** [comment]
@Lev135, this is most likely due to a bug in versions of GHC from 9.0.1 to 9.8.1 (to date) on Windows which affects the boot packages provided with GHC. See the warning in Stack's documentation here: https://docs.haskellstack.org/en/stable/build_command/#-no-haddock-flag and https://gitlab.haskell.org/ghc/ghc/-/issues/23476. This will be fixed in the GHC 9.10 series. Until then, you have to manually edit the `*.conf` files provided with GHC in order to patch GHC. (You can do that relatively quickly in, say, Visual Studio Code by using its find and replace function for files.)

**Comment by jasagredo** [comment]
If this has the label `resolution: not our bug`, then shouldn't we close this?

**Comment by jasagredo** [comment]
Closing, please re-open if you disagree.
