### ISSUE TITLE
ghc-boot is reinstallable

### ISSUE THREAD

**Issue by mpickering** [haskell/cabal#9064]
~~#8489~~ #8501 added `ghc-boot`  to the `nonUpgradeablePackages` list but I don't see why `ghc-boot` is not reinstallable. It is a normal dependency of `ghc` like `containers` (which is reinstallable). 

It would be good to document what a `nonUpgradeablePackage` is to avoid additional packages being added here in future.

**Comment by andreabedini** [comment]
I think the PR is https://github.com/haskell/cabal/pull/8501 and the commit that made the change is https://github.com/haskell/cabal/commit/09c90de378273ae2f08fb605ea03e857ec2b8720 that made the change. Reading through https://github.com/haskell/cabal/pull/8501 and https://github.com/haskell/cabal/issues/8489 I have the impression nobody here is sure about what should be non-reinstallable (or non-upgradeable? or whatever this means)

Can GHC provide guidance and a source of truth for the list of relevant packages?

**Comment by ulysses4ever** [comment]
I have the same impression as Andrea.

@grayjay may be interested to opine on this issue.

**Comment by grayjay** [comment]
I agree that no one knew how to determine the list of non-upgradable packages. It looks like `ghc` was the only non-ugradable package that was causing a problem in #8489.

**Comment by gbaz** [comment]
Yes, please somebody who knows what they are doing take ownership of this and help! :-)

**Comment by bgamari** [comment]
My understanding is that the set of non-reinstallable packages should only includes those which cannot be rebuilt using a GHC installation and Hackage-published source distribution. There are a few reasons why this might be true:

 * the package overrides its unit ID with `-this-unit-id`, which would result in multiple indistinguishable packages (having potentially different ABIs) with the same unit ID after reinstallation
 * definition of wired-in declarations which tie the package to a particular compiler (e.g. we can't build link against `base-4.18.0.0` using GHC 9.6.1
 * packages that rely on configuration provided by GHC's build system; in the future such configuration should be fixed to rather be defined by a `configure` script or custom `Setup`.

This list should currently include:

 * `ghc`, since we are still working on making [ghc#19896](https://gitlab.haskell.org/ghc/ghc/-/issues/19896) feasible (see [ghc#20742](https://gitlab.haskell.org/ghc/ghc/-/issues/20742))
 * `ghc-prim` (due to use of `-this-unit-id` and wired-in declarations)
 * `base` (due to use of `-this-unit-id` and wired-in declarations)
 * `rts` (due to strong ABI dependence)
 * `template-haskell` (due to use of `-this-unit-id`)
 * `ghc-bignum` (due to use of `-this-unit-id`)

**Comment by ulysses4ever** [comment]
@bgamari thanks a lot, that's very clear. Do you have an idea about non-reinstallable vs. non-upgradable? Is there a slightest difference between the two notions do you think? Our guess is that there may be none, [see this thread](https://github.com/haskell/cabal/pull/8712#discussion_r1096461398).

**Comment by bgamari** [comment]
> @bgamari thanks a lot, that's very clear. Do you have an idea about non-reinstallable vs. non-upgradable? Is there a slightest difference between the two notions do you think? Our guess is that there may be none, [see this thread](https://github.com/haskell/cabal/pull/8712#discussion_r1096461398).

My sense is that currently there should be no difference between non-upgradeable and non-reinstallable packages. Moreover, at the moment I don't see why we would need such a distinction in the future.

However, in the future (when `ghc` is a reinstallable package) we may need some notion of constraints on compile-time dependencies arising from the compiler being used. Specifically, consider a package `p` which uses a compiler plugin in its build process. `cabal-install` must someone ensure that the `ghc` library linked against by the plugin is the same as that linked by the `ghc-bin` executable used for the build.

**Comment by bgamari** [comment]
I have opened https://github.com/haskell/cabal/pull/9092 addressing this.
