### ISSUE TITLE
A late profiling options doesn't seem to work: `--profiling-detail=late-inline`

### ISSUE THREAD

**Issue by Mikolaj** [haskell/cabal#9182]
`--profiling-detail=late-inline` results in a wrong profile, different than when specifying `--ghc-options="-fprof-late-inline"`. This should work: https://downloads.haskell.org/ghc/9.4.6/docs/users_guide/profiling.html?highlight=profiling

Tested with GHC 9.4.6 and cabal 3.10.1.0.

OTOH, I see this among the tests:

    cabal-testsuite/PackageTests/ProfLate/setup.test.hs:        --  ["--enable-profiling", "--profiling-detail=late-toplevel"]

which is not a valid option AFAIC, so perhaps the options changed at the last moment. Cabal documentation is lacking, too: https://cabal.readthedocs.io/en/latest/setup-commands.html#cmdoption-runhaskell-Setup.hs-configure-profiling-detail

We could start by updating the test, then fix it, then document.

**Comment by Mikolaj** [comment]
Wiring in the author of this indispensable GHC feature: @AndreasPK

**Comment by AndreasPK** [comment]
> --profiling-detail=late-inline results in a wrong profile, different than when specifying --ghc-options="-fprof-late-inline".

Best I can tell `--profiling-detail=late-inline` isn't a valid option so that's not surprising. It should be `late` or `late-toplevel`.

`-fprof-late-inline` is a flag for niche cases that I didn't expose via cabal at all. So it's not surprising that you get odd results.

> which is not a valid option AFAIC, so perhaps the options changed at the last moment. Cabal documentation is lacking, too: https://cabal.readthedocs.io/en/latest/setup-commands.html#cmdoption-runhaskell-Setup.hs-configure-profiling-detail

It seems the profiling detail documentation exists in two places: `cabal-project.rst` and `setup-commands.rst`

The former has the documentation: https://cabal.readthedocs.io/en/latest/cabal-project.html#cfg-flag---profiling-detail I was not aware of the later so didn't update it at the time.

---------------

Some background:

From GHC's side there are two kinds of late cost centre profiling:

a) Late cost centres are included in unfoldings. It might be useful for more detailed profiles but comes with more overhead and is almost never what one wants.
b) Late cost centres are inserted only in the actual code but not included in unfoldings. Better for performance/overhead but a functions which are completely inlined are more likely to disappear from a profile. But that hardly ever matters and using this is almost always the right answer.

* In the first ghc released with late cost centres `-fprof-late` was the only option and gave you option a.
* In later releases `-fprof-late` defaults to b) but the flag `-fprof-late-inline` was added to enable the old behavior.

I don't remember which ghc release exactly made the switch. But cabal with --profiling-detail=late will give you:

* b) for "newer" ghc releases, 
* a) for the first ghc release with late cost centre profiling 
* the old top level profiling for ghc-9.2 and earlier iirc

**Comment by Mikolaj** [comment]
OK, thank you, that makes sense. If I really want to try `-fprof-late-inline` I can always do `--ghc-options="-fprof-late-inline"`.
