### ISSUE TITLE
setup.Cabal constraints don't apply transitively

### ISSUE THREAD

**Issue by mpickering** [haskell/cabal#9322]
If you have a transitive dependency on something via a custom setup-depends then `setup.*` constraints don't apply to it.

* If you write `setup.Cabal >= ...`, this constraint will apply to a direct Cabal dependency of the setup component
* If you write `Cabal >= ...` this constraint will apply to transitive dependencies of the setup component.

So if you really want to ensure that you are using a specific version of `Cabal` you need to specify both `setup.Cabal` and `Cabal` constraints, this seems to negate the point of the `setup.Cabal` constraint form in the first place.

**Comment by andreabedini** [comment]
I tried to reproduce this but I am not sure I understand.

I created a scratch package with
```
custom-setup
  setup-depends: base, Cabal
```
No other dependencies beside base and no bounds.

base, Cabal are direct dependencies of setup; Cabal's own dependencies (e.g. parsec) are transitive dependencies of setup. 

```
❯ cabal build -w ghc-9.4.7 --dry-run && cabal-plan tred
Build profile: -w ghc-9.4.7 -O1
In order, the following would be built (use -v for more details):
 - cabal-issue9322-0.1.0.0 (lib:cabal-issue9322) (first run)
[cabal-issue9322-0.1.0.0:all]
 ├─ cabal-issue9322-0.1.0.0
 │   └─ base-4.17.2.0
 │       └─ ghc-bignum-1.3
 │           └─ ghc-prim-0.9.1
 │               └─ rts-1.0.2
 └─ [setup]
     └─ Cabal-3.8.1.0
         ├─ Cabal-syntax-3.8.1.0
         │   ├─ directory-1.3.7.1
       --8<--8<--
         │   └─ parsec-3.1.16.1
         │       ├─ mtl-2.2.2
         │       │   └─ transformers-0.5.6.2
         │       │       └─ base-4.17.2.0 ┄┄
         │       └─ text-2.0.2
         │           └─ binary-0.8.9.1
         │               ├─ bytestring-0.11.5.2 ┄┄
         │               └─ containers-0.6.7
         │                   └─ template-haskell-2.19.0.0 ┄┄
         └─ process-1.6.17.0
             └─ directory-1.3.7.1 ┄┄
```
The solver picks all the preinstalled versions (e.g. parsec-3.1.16.1). which is what I would expect.

Now I try to add a constraint to setup's transitive dependency on parsec.
```
❯ cabal build -w ghc-9.4.7 --dry-run --constraint 'setup.parsec >= 3.1.17.0' && cabal-plan tred
Build profile: -w ghc-9.4.7 -O1
In order, the following would be built (use -v for more details):
 - parsec-3.1.17.0 (lib) (requires download & build)
 - Cabal-syntax-3.10.1.0 (lib) (requires build)
 - Cabal-3.10.1.0 (lib) (requires build)
 - cabal-issue9322-0.1.0.0 (lib:cabal-issue9322) (first run)
[cabal-issue9322-0.1.0.0:all]
 ├─ cabal-issue9322-0.1.0.0
 │   └─ base-4.17.2.0
...
 └─ [setup]
     └─ Cabal-3.10.1.0
         ├─ Cabal-syntax-3.10.1.0
...
         │   └─ parsec-3.1.17.0
...
```
You can see parsec has changed version and Cabal & Cabal-syntax need to be recompiled.

So far so good.

Where I get confused is
> Cabal >= ... this constraint will apply to transitive dependencies of the setup component

Do you mean a transitive dependency of setup on Cabal? (setup -> pkg-a -> Cabal?). Assuming setup also depends on Cabal, I can hardly believe this because you would have two different versions of Cabal linked togheter in setup.

Also
>     If you write Cabal >= ... this constraint will apply to transitive dependencies of the setup component.

This is not true. If you add to cabal-issue9322 a dependency on parsec, then the constraint `parsec >= 3.1.17.0` will not apply to setup.

```
❯ cabal build -w ghc-9.4.7 --dry-run --constraint 'parsec >= 3.1.17.0' && cabal-plan tred
Resolving dependencies...
Build profile: -w ghc-9.4.7 -O1
In order, the following would be built (use -v for more details):
 - parsec-3.1.17.0 (lib) (requires download & build)
 - cabal-issue9322-0.1.0.0 (lib:cabal-issue9322) (first run)
[cabal-issue9322-0.1.0.0:all]
 ├─ cabal-issue9322-0.1.0.0
 │   └─ parsec-3.1.17.0
...
 └─ [setup]
     └─ Cabal-3.8.1.0
         ├─ Cabal-syntax-3.8.1.0
...
         │   └─ parsec-3.1.16.1
...
```

Do you have a reproducible example?

Note: Just to remind us of the possible syntaxes (which I always have to look up :joy: [here](https://cabal.readthedocs.io/en/stable/setup-commands.html#cmdoption-runhaskell-Setup.hs-configure-constraint)).
- `setup.parsec` means parsec in the dependency tree of any setup
- `cabal-issue9322:setup.parsec` means parsec in the dependency tree of cabal-issue9322's setup
- `any.parsec` means parsec anywhere in the build plan (dependency forest?)
Note that `cabal-issue9322:parsec` or `cabal-issue9322:any.parsec` are not valid constraints.

**Comment by andreabedini** [comment]
@mpickering Does the above works for you?

**Comment by andreabedini** [comment]
Feel free to reopen.
