### ISSUE TITLE
Incorrect error messages for non-existing dependencies

### ISSUE THREAD

**Issue by bos** [haskell/cabal#941]
(Imported from [Trac #951](http://hackage.haskell.org/trac/hackage/ticket/951), reported by guest on 2012-05-15)

When the build-depends-field contains non-existing packages, cabal-install sometimes does not report that these packages could not be found but complains about other constraints being unsolvable.

The attached cabal-file contains a dependency for a non-existing package called "bogus". This is what I get:

<pre class="wiki">$ cabal install --only-dependencies --dry-run
Resolving dependencies...
cabal: Could not resolve dependencies:
next goal: foo (user goal)
rejecting: foo-1.0 (global constraint requires ==0.1.0.0)
trying: foo-0.1.0.0
trying: heist-0.8.0 (dependency of foo-0.1.0.0)
trying: transformers-0.3.0.0 (dependency of heist-0.8.0)
next goal: mtl (dependency of heist-0.8.0)
rejecting: mtl-2.1.1, 2.1 (conflict: heist =&gt; mtl&gt;=2.0 &amp;&amp; &lt;2.1)
rejecting: mtl-2.0.1.0, 2.0.0.0 (conflict: transformers==0.3.0.0, mtl =&gt;
transformers==0.2.*)
rejecting: mtl-1.1.1.1, 1.1.1.0, 1.1.0.2, 1.1.0.1, 1.1.0.0, 1.0 (conflict:
heist =&gt; mtl&gt;=2.0 &amp;&amp; &lt;2.1)
</pre>When removing "bogus" from the build-depends, cabal-install is able to come up with a working install plan.

Used versions:

<pre class="wiki">$ cabal --version
cabal-install version 0.14.0
using version 1.14.0 of the Cabal library
</pre>

**Comment by grayjay** [comment]
I have an idea for improving the summary in cases like this.  We could run the solver once to try to find a solution.  Then, if it fails, we could run it again, but have it prefer goals from the first run's top-level conflict set.  The solver would use the log from the second run, up to the first error, as the summary.

The errors from the second run could be more relevant, because they are likely to come from the final conflict set, which explains why the whole tree has no solution.  In this example, the conflict set is probably {bogus, foo}.  So the error message would show the solver trying `foo` and then `bogus`.

**Comment by grayjay** [comment]
See #4139 for another example of a misleading first error message.

**Comment by grayjay** [comment]
#5012 should improve the error message in this case.  The -v3 message from https://github.com/haskell/cabal/issues/941#issuecomment-5893463 shows that the final conflict set contained just `bogus` and `foo`, so #5012 should only show the conflict between those two packages.
