### ISSUE TITLE
Continuous integration failed to detect bug in solver Hackage benchmarks

### ISSUE THREAD

**Issue by grayjay** [haskell/cabal#9495]
#6447 added a short run of the solver Hackage benchmark to CI to test that it can run without errors. However, I noticed a bug where the benchmark fails to run when the cabal config files have not been initialized (#9494). This issue is for checking whether CI is still correctly testing the benchmark.

**Comment by Mikolaj** [comment]
For a start, does the test run when testing cabal locally according to the relevant instructions?

**Comment by grayjay** [comment]
@Mikolaj Which instructions are you referring to? CONTRIBUTING.md doesn't mention the Hackage benchmark, though it probably should. The benchmark should be able to run locally after #9494.

**Comment by grayjay** [comment]
#9500 (85415147639c1cbb85dcc34ffcce56fd55ac85f3) showed that CI still passes when the benchmark calls `die` at the start.

**Comment by grayjay** [comment]
c3320329c2e81766d7f8177463cb539f6ee973a8 showed that CI fails when the benchmark doesn't compile.

**Comment by Mikolaj** [comment]
> EDIT: The step "Validate build" of the job "Validate ubuntu-latest ghc-9.2.8" failed, though all other "Validate" jobs were cancelled.

That's normal. When one job fails, others get cancelled. So this case is fine.

**Comment by Mikolaj** [comment]
Good detective work. Yes, I confirm in the raw log from https://github.com/haskell/cabal/actions/runs/7109262010/job/19402640597?pr=9494 that benchmarks are built for GHC 9.2.8. However, they are not tested nor run, because `validate.sh` is no longer run as whole, to execute all the steps, but instead `validate.yml` decides which steps to execute and calls `validate.sh` for each separately. Unfortunately, it seems somebody did not cover the benchmark test and run steps in `validate.yml` (nor the `time-summary` step that should come after; no idea if it's still useful).

So this looks like an omission in `validate.yml` and it's hard to detect because of the duplication with `validate.sh`, where the benchmark steps are not omitted. I think we should just add the relevant steps to  `validate.yml`, running them conditionally, probably just with the `if [[ ${{ matrix.ghc }} == ${{ env.GHC_FOR_SOLVER_BENCHMARKS }} ]];` condition.

**Comment by grayjay** [comment]
@Mikolaj Thanks for the advice! I made the change that you suggested in #9625, and now CI fails with the error about a missing config file from #9494.

**Comment by grayjay** [comment]
I tried introducing a failure into the benchmark unit tests now that #9625 has been merged (5655b8957a5f5da0b2d63603453206efa7c8e194), and it caused the CI to fail, as expected.

**Comment by Mikolaj** [comment]
> I tried introducing a failure into the benchmark unit tests now that #9625 has been merged ([5655b89](https://github.com/haskell/cabal/commit/5655b8957a5f5da0b2d63603453206efa7c8e194)), and it caused the CI to fail, as expected.

Amazing! Success!
