### ISSUE TITLE
Generate haddock for multiple (sub)libraries at once

### ISSUE THREAD

**Issue by 414owen** [haskell/cabal#9577]
Currently, running `cabal haddock --haddock-for-hackage` seems to produce a tarball containing the docs for one library.

If you pass it the name of a sublibrary, it will generate the docs for that sublibrary only.

Hackage seems to overwrite the docs when you upload a new tarball, so it seems people would need to either fiddle with tarballs manually, or have only one library documented.

Note that when [this change](https://github.com/haskell/hackage-server/pull/1279) is deployed, hackage will list the modules of multiple libraries, so a lack of docs will become quite visible.

**Comment by geekosaur** [comment]
Should have been closed by #9821.

**Comment by Mikolaj** [comment]
I'm afraid this issue is not fixed in the sense that both `cabal haddock --haddock-for-hackage` and `cabal haddock-project --whatever-options` can't generate the tarball that one could upload to Hackage (and that contains more than the last component of the package). Hackage internally creates the archive by hand, not using `cabal`: https://github.com/haskell/hackage-server/blob/8389c13ffaa816efceeb5d9fd44947b9de88e553/exes/BuildClient.hs#L801
